package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AApprovalType generated by hbm2java
 */
@Entity
@Table(name="a_approval_type")
public class AApprovalType  implements java.io.Serializable {


     private Long idApprovalType;
     private Company company;
     private Users users;
     private String name;
     private String description;
     private Date creationTime;
     private Set<AApprovalProcess> AApprovalProcesses = new HashSet<AApprovalProcess>(0);

    public AApprovalType() {
    }

    public AApprovalType(Company company, Users users, String name, String description, Date creationTime, Set<AApprovalProcess> AApprovalProcesses) {
       this.company = company;
       this.users = users;
       this.name = name;
       this.description = description;
       this.creationTime = creationTime;
       this.AApprovalProcesses = AApprovalProcesses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_approval_type", unique=true, nullable=false)
    public Long getIdApprovalType() {
        return this.idApprovalType;
    }
    
    public void setIdApprovalType(Long idApprovalType) {
        this.idApprovalType = idApprovalType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="AApprovalType")
    public Set<AApprovalProcess> getAApprovalProcesses() {
        return this.AApprovalProcesses;
    }
    
    public void setAApprovalProcesses(Set<AApprovalProcess> AApprovalProcesses) {
        this.AApprovalProcesses = AApprovalProcesses;
    }




}


