package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AApprovalCcId generated by hbm2java
 */
@Embeddable
public class AApprovalCcId  implements java.io.Serializable {


     private Long idApprovalPhase;
     private Long idUser;

    public AApprovalCcId() {
    }

    public AApprovalCcId(Long idApprovalPhase, Long idUser) {
       this.idApprovalPhase = idApprovalPhase;
       this.idUser = idUser;
    }
   

    @Column(name="id_approval_phase", nullable=false)
    public Long getIdApprovalPhase() {
        return this.idApprovalPhase;
    }
    
    public void setIdApprovalPhase(Long idApprovalPhase) {
        this.idApprovalPhase = idApprovalPhase;
    }

    @Column(name="id_user", nullable=false)
    public Long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AApprovalCcId) ) return false;
		 AApprovalCcId castOther = ( AApprovalCcId ) other; 
         
		 return ( (this.getIdApprovalPhase()==castOther.getIdApprovalPhase()) || ( this.getIdApprovalPhase()!=null && castOther.getIdApprovalPhase()!=null && this.getIdApprovalPhase().equals(castOther.getIdApprovalPhase()) ) )
 && ( (this.getIdUser()==castOther.getIdUser()) || ( this.getIdUser()!=null && castOther.getIdUser()!=null && this.getIdUser().equals(castOther.getIdUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdApprovalPhase() == null ? 0 : this.getIdApprovalPhase().hashCode() );
         result = 37 * result + ( getIdUser() == null ? 0 : this.getIdUser().hashCode() );
         return result;
   }   


}


