package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AApplicationPhase generated by hbm2java
 */
@Entity
@Table(name="a_application_phase"
    ,catalog="jms3"
)
public class AApplicationPhase  implements java.io.Serializable {


     private AApplicationPhaseId id;
     private SysDicD sysDicD;
     private AApplication AApplication;
     private AApprovalPhase AApprovalPhase;
     private Date actionTime;
     private String comment;

    public AApplicationPhase() {
    }

	
    public AApplicationPhase(AApplicationPhaseId id, AApplication AApplication, AApprovalPhase AApprovalPhase) {
        this.id = id;
        this.AApplication = AApplication;
        this.AApprovalPhase = AApprovalPhase;
    }
    public AApplicationPhase(AApplicationPhaseId id, SysDicD sysDicD, AApplication AApplication, AApprovalPhase AApprovalPhase, Date actionTime, String comment) {
       this.id = id;
       this.sysDicD = sysDicD;
       this.AApplication = AApplication;
       this.AApprovalPhase = AApprovalPhase;
       this.actionTime = actionTime;
       this.comment = comment;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idApplication", column=@Column(name="id_application", nullable=false) ), 
        @AttributeOverride(name="idApprovalPhase", column=@Column(name="id_approval_phase", nullable=false) ) } )
    public AApplicationPhaseId getId() {
        return this.id;
    }
    
    public void setId(AApplicationPhaseId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SysDicD getSysDicD() {
        return this.sysDicD;
    }
    
    public void setSysDicD(SysDicD sysDicD) {
        this.sysDicD = sysDicD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_application", nullable=false, insertable=false, updatable=false)
    public AApplication getAApplication() {
        return this.AApplication;
    }
    
    public void setAApplication(AApplication AApplication) {
        this.AApplication = AApplication;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_approval_phase", nullable=false, insertable=false, updatable=false)
    public AApprovalPhase getAApprovalPhase() {
        return this.AApprovalPhase;
    }
    
    public void setAApprovalPhase(AApprovalPhase AApprovalPhase) {
        this.AApprovalPhase = AApprovalPhase;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="action_time", length=19)
    public Date getActionTime() {
        return this.actionTime;
    }
    
    public void setActionTime(Date actionTime) {
        this.actionTime = actionTime;
    }
    
    @Column(name="comment", length=512)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


