package com.jms.domain.db;
// Generated 2015-8-22 18:08:00 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApprovalType generated by hbm2java
 */
@Entity
@Table(name="approval_type"
    ,catalog="jms"
)
public class ApprovalType  implements java.io.Serializable {


     private Long idApprovalType;
     private Company company;
     private Users users;
     private String name;
     private String description;
     private Date creationTime;
     private Set<ApprovalProcess> approvalProcesses = new HashSet<ApprovalProcess>(0);

    public ApprovalType() {
    }

    public ApprovalType(Company company, Users users, String name, String description, Date creationTime, Set<ApprovalProcess> approvalProcesses) {
       this.company = company;
       this.users = users;
       this.name = name;
       this.description = description;
       this.creationTime = creationTime;
       this.approvalProcesses = approvalProcesses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_APPROVAL_TYPE", unique=true, nullable=false)
    public Long getIdApprovalType() {
        return this.idApprovalType;
    }
    
    public void setIdApprovalType(Long idApprovalType) {
        this.idApprovalType = idApprovalType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMPANY")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATOR")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="NAME", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATION_TIME", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="approvalType")
    public Set<ApprovalProcess> getApprovalProcesses() {
        return this.approvalProcesses;
    }
    
    public void setApprovalProcesses(Set<ApprovalProcess> approvalProcesses) {
        this.approvalProcesses = approvalProcesses;
    }




}


