package com.jms.domain.db;
// Generated 2015-7-5 10:54:07 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * ApprovalProcess generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "approval_process")
@Entity
@Table(name="approval_process"
    ,catalog="jms"
)
public class ApprovalProcess  implements java.io.Serializable {


     private Long idApprovalProcess;
     private Document document;
     private ApprovalType approvalType;
     private String name;
     private String description;
     private Set<Application> applications = new HashSet<Application>(0);
     private Set<ApprovalPhase> approvalPhases = new HashSet<ApprovalPhase>(0);

    public ApprovalProcess() {
    }

    public ApprovalProcess(Document document, ApprovalType approvalType, String name, String description, Set<Application> applications, Set<ApprovalPhase> approvalPhases) {
       this.document = document;
       this.approvalType = approvalType;
       this.name = name;
       this.description = description;
       this.applications = applications;
       this.approvalPhases = approvalPhases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_APPROVAL_PROCESS", unique=true, nullable=false)
    public Long getIdApprovalProcess() {
        return this.idApprovalProcess;
    }
    
    public void setIdApprovalProcess(Long idApprovalProcess) {
        this.idApprovalProcess = idApprovalProcess;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOCUMENT")
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_APPROVAL_TYPE")
    public ApprovalType getApprovalType() {
        return this.approvalType;
    }
    
    public void setApprovalType(ApprovalType approvalType) {
        this.approvalType = approvalType;
    }
    
    @Column(name="NAME", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", length=1024)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="approvalProcess")
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="approvalProcess")
    public Set<ApprovalPhase> getApprovalPhases() {
        return this.approvalPhases;
    }
    
    public void setApprovalPhases(Set<ApprovalPhase> approvalPhases) {
        this.approvalPhases = approvalPhases;
    }




}


