package com.jms.domain.db;
// Generated 2015-8-15 16:28:29 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApprovalCc generated by hbm2java
 */
@Entity
@Table(name="approval_cc"
    ,catalog="jms"
)
public class ApprovalCc  implements java.io.Serializable {


     private ApprovalCcId id;
     private Users users;
     private ApprovalPhase approvalPhase;
     private NotiMethod notiMethod;

    public ApprovalCc() {
    }

	
    public ApprovalCc(ApprovalCcId id, Users users, ApprovalPhase approvalPhase) {
        this.id = id;
        this.users = users;
        this.approvalPhase = approvalPhase;
    }
    public ApprovalCc(ApprovalCcId id, Users users, ApprovalPhase approvalPhase, NotiMethod notiMethod) {
       this.id = id;
       this.users = users;
       this.approvalPhase = approvalPhase;
       this.notiMethod = notiMethod;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idApprovalPhase", column=@Column(name="ID_APPROVAL_PHASE", nullable=false) ), 
        @AttributeOverride(name="idUser", column=@Column(name="ID_USER", nullable=false) ) } )
    public ApprovalCcId getId() {
        return this.id;
    }
    
    public void setId(ApprovalCcId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USER", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_APPROVAL_PHASE", nullable=false, insertable=false, updatable=false)
    public ApprovalPhase getApprovalPhase() {
        return this.approvalPhase;
    }
    
    public void setApprovalPhase(ApprovalPhase approvalPhase) {
        this.approvalPhase = approvalPhase;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_NOTI_METHOD")
    public NotiMethod getNotiMethod() {
        return this.notiMethod;
    }
    
    public void setNotiMethod(NotiMethod notiMethod) {
        this.notiMethod = notiMethod;
    }




}


