package com.jms.domain.db;
// Generated 2015-7-5 10:54:07 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * Apps generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "app")
@Entity
@Table(name="apps"
    ,catalog="jms"
)
public class Apps  implements java.io.Serializable {


     private Long id;
     private String appName;
     private String description;
     private Long scope;
     private String appKey;
     private String appSecret;
     private String url;
     private Set<CompanyApp> companyApps = new HashSet<CompanyApp>(0);
     private Set<UserApp> userApps = new HashSet<UserApp>(0);
     private Set<JmsEvent> jmsEvents = new HashSet<JmsEvent>(0);

    public Apps() {
    }

    public Apps(String appName, String description, Long scope, String appKey, String appSecret, String url, Set<CompanyApp> companyApps, Set<UserApp> userApps, Set<JmsEvent> jmsEvents) {
       this.appName = appName;
       this.description = description;
       this.scope = scope;
       this.appKey = appKey;
       this.appSecret = appSecret;
       this.url = url;
       this.companyApps = companyApps;
       this.userApps = userApps;
       this.jmsEvents = jmsEvents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="APP_NAME", length=20)
    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }
    
    @Column(name="DESCRIPTION", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SCOPE")
    public Long getScope() {
        return this.scope;
    }
    
    public void setScope(Long scope) {
        this.scope = scope;
    }
    
    @Column(name="APP_KEY", length=64)
    public String getAppKey() {
        return this.appKey;
    }
    
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }
    
    @Column(name="APP_SECRET", length=64)
    public String getAppSecret() {
        return this.appSecret;
    }
    
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }
    
    @Column(name="URL", length=512)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="apps")
    public Set<CompanyApp> getCompanyApps() {
        return this.companyApps;
    }
    
    public void setCompanyApps(Set<CompanyApp> companyApps) {
        this.companyApps = companyApps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="apps")
    public Set<UserApp> getUserApps() {
        return this.userApps;
    }
    
    public void setUserApps(Set<UserApp> userApps) {
        this.userApps = userApps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="apps")
    public Set<JmsEvent> getJmsEvents() {
        return this.jmsEvents;
    }
    
    public void setJmsEvents(Set<JmsEvent> jmsEvents) {
        this.jmsEvents = jmsEvents;
    }




}


