package com.jms.domain.db;
// Generated 2015-8-22 18:08:00 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.jms.domain.db.AbstractSecuredEntity;
import com.jms.domain.db.Users;

/**
 * Apps generated by hbm2java
 */
@Entity
@Table(name="apps"
    ,catalog="jms"
)
public class Apps extends AbstractSecuredEntity implements java.io.Serializable {


     private Long idApp;
     private String groups;
     private String appName;
     private String description;
     private Long scope;
     private String appKey;
     private String appSecret;
     private Long seq;
     private String url;
     private Set<JmsEvent> jmsEvents = new HashSet<JmsEvent>(0);

    public Apps() {
    }

    public Apps(String groups, String appName, String description, Long scope, String appKey, String appSecret, Long seq, String url, Set<JmsEvent> jmsEvents) {
       this.groups = groups;
       this.appName = appName;
       this.description = description;
       this.scope = scope;
       this.appKey = appKey;
       this.appSecret = appSecret;
       this.seq = seq;
       this.url = url;
       this.jmsEvents = jmsEvents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_APP", unique=true, nullable=false)
    public Long getIdApp() {
        return this.idApp;
    }
    
    public void setIdApp(Long idApp) {
        this.idApp = idApp;
    }
    
    @Column(name="GROUPS", length=64)
    public String getGroups() {
        return this.groups;
    }
    
    public void setGroups(String groups) {
        this.groups = groups;
    }
    
    @Column(name="APP_NAME", length=20)
    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }
    
    @Column(name="DESCRIPTION", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SCOPE")
    public Long getScope() {
        return this.scope;
    }
    
    public void setScope(Long scope) {
        this.scope = scope;
    }
    
    @Column(name="APP_KEY", length=64)
    public String getAppKey() {
        return this.appKey;
    }
    
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }
    
    @Column(name="APP_SECRET", length=64)
    public String getAppSecret() {
        return this.appSecret;
    }
    
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }
    
    @Column(name="SEQ")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }
    
    @Column(name="URL", length=512)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="apps")
    public Set<JmsEvent> getJmsEvents() {
        return this.jmsEvents;
    }
    
    public void setJmsEvents(Set<JmsEvent> jmsEvents) {
        this.jmsEvents = jmsEvents;
    }

    @Override @Transient
    public Long getId() {
        return this.getIdApp();
    }
   @Override  @Transient
  	public Users getUser() {
  		return this.getUser();
  	}



}


