package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuyRecord generated by hbm2java
 */
@Entity
@Table(name="buy_record"
    ,catalog="jms3"
)
public class BuyRecord  implements java.io.Serializable {


     private Long id;
     private Company company;
     private Service service;
     private Receipt receipt;
     private Date buyTime;
     private Date invalidTime;
     private Long requireInvoice;
     private String invoiceDescription;
     private String paymentNumder;
     private String orderNumber;
     private Float payment;
     private Long payMethod;

    public BuyRecord() {
    }

    public BuyRecord(Company company, Service service, Receipt receipt, Date buyTime, Date invalidTime, Long requireInvoice, String invoiceDescription, String paymentNumder, String orderNumber, Float payment, Long payMethod) {
       this.company = company;
       this.service = service;
       this.receipt = receipt;
       this.buyTime = buyTime;
       this.invalidTime = invalidTime;
       this.requireInvoice = requireInvoice;
       this.invoiceDescription = invoiceDescription;
       this.paymentNumder = paymentNumder;
       this.orderNumber = orderNumber;
       this.payment = payment;
       this.payMethod = payMethod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_service")
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_receipt")
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="buy_time", length=19)
    public Date getBuyTime() {
        return this.buyTime;
    }
    
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="invalid_time", length=19)
    public Date getInvalidTime() {
        return this.invalidTime;
    }
    
    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }
    
    @Column(name="require_invoice")
    public Long getRequireInvoice() {
        return this.requireInvoice;
    }
    
    public void setRequireInvoice(Long requireInvoice) {
        this.requireInvoice = requireInvoice;
    }
    
    @Column(name="invoice_description", length=512)
    public String getInvoiceDescription() {
        return this.invoiceDescription;
    }
    
    public void setInvoiceDescription(String invoiceDescription) {
        this.invoiceDescription = invoiceDescription;
    }
    
    @Column(name="payment_numder", length=64)
    public String getPaymentNumder() {
        return this.paymentNumder;
    }
    
    public void setPaymentNumder(String paymentNumder) {
        this.paymentNumder = paymentNumder;
    }
    
    @Column(name="order_number", length=64)
    public String getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }
    
    @Column(name="payment", precision=12, scale=0)
    public Float getPayment() {
        return this.payment;
    }
    
    public void setPayment(Float payment) {
        this.payment = payment;
    }
    
    @Column(name="pay_method")
    public Long getPayMethod() {
        return this.payMethod;
    }
    
    public void setPayMethod(Long payMethod) {
        this.payMethod = payMethod;
    }




}


