package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="jms4"
)
public class City  implements java.io.Serializable {


     private Long idCity;
     private Province province;
     private String city;
     private String postcode;
     private Set<District> districts = new HashSet<District>(0);

    public City() {
    }

	
    public City(Long idCity) {
        this.idCity = idCity;
    }
    public City(Long idCity, Province province, String city, String postcode, Set<District> districts) {
       this.idCity = idCity;
       this.province = province;
       this.city = city;
       this.postcode = postcode;
       this.districts = districts;
    }
   
     @Id 
    
    @Column(name="id_city", unique=true, nullable=false)
    public Long getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(Long idCity) {
        this.idCity = idCity;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_province")
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    
    @Column(name="city", length=32)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="postcode", length=20)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="city")
    public Set<District> getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set<District> districts) {
        this.districts = districts;
    }




}


