package com.jms.domain.db;
// Generated 2015-6-6 20:38:20 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="jms"
)
public class City  implements java.io.Serializable {


     private Integer idCity;
     private Province province;
     private String city;
     private String postcode;
     private Set<District> districts = new HashSet<District>(0);

    public City() {
    }

    public City(Province province, String city, Set<District> districts) {
       this.province = province;
       this.city = city;
       this.districts = districts;
    }
   
     @Id 
    
    @Column(name="ID_CITY", unique=true, nullable=false)
    public Integer getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(Integer idCity) {
        this.idCity = idCity;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROVINCE")
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    
    @Column(name="CITY", length=32)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="city")
    public Set<District> getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set<District> districts) {
        this.districts = districts;
    }

    @Column(name="POSTCODE", length=20)
	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}




}


