package com.jms.domain.db;
// Generated 2015-6-6 20:38:20 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name="district"
    ,catalog="jms"
)
public class District  implements java.io.Serializable {


     private Integer idDistrict;
     private City city;
     private String district;
     private Set<Company> companies = new HashSet<Company>(0);

    public District() {
    }

    public District(City city, String district, Set<Company> companies) {
       this.city = city;
       this.district = district;
       this.companies = companies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_DISTRICT", unique=true, nullable=false)
    public Integer getIdDistrict() {
        return this.idDistrict;
    }
    
    public void setIdDistrict(Integer idDistrict) {
        this.idDistrict = idDistrict;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CITY")
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    
    @Column(name="DISTRICT", length=32)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="district")
    public Set<Company> getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set<Company> companies) {
        this.companies = companies;
    }




}


