package com.jms.domain.db;
// Generated 2015-6-25 9:56:24 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * Document generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "document_AUD") 
@Entity
@Table(name="document"
    ,catalog="jms"
)
public class Document  implements java.io.Serializable {


     private Long idDocument;
     private Document document;
     private String fileName;
     private String name;
     private String description;
     private String relativePath;
     private Long size;
     private Set<TaskDoc> taskDocs = new HashSet<TaskDoc>(0);
     private Set<IssueDoc> issueDocs = new HashSet<IssueDoc>(0);
     private Set<ProjectDoc> projectDocs = new HashSet<ProjectDoc>(0);
     private Set<Document> documents = new HashSet<Document>(0);
     private Set<Company> companiesForLogo = new HashSet<Company>(0);
     private Set<Company> companiesForLicense = new HashSet<Company>(0);
     private Set<Users> userses = new HashSet<Users>(0);

    public Document() {
    }

    public Document(Document document, String fileName, String name, String description, String relativePath, Long size, Set<TaskDoc> taskDocs, Set<IssueDoc> issueDocs, Set<ProjectDoc> projectDocs, Set<Document> documents, Set<Company> companiesForLogo, Set<Company> companiesForLicense, Set<Users> userses) {
       this.document = document;
       this.fileName = fileName;
       this.name = name;
       this.description = description;
       this.relativePath = relativePath;
       this.size = size;
       this.taskDocs = taskDocs;
       this.issueDocs = issueDocs;
       this.projectDocs = projectDocs;
       this.documents = documents;
       this.companiesForLogo = companiesForLogo;
       this.companiesForLicense = companiesForLicense;
       this.userses = userses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_DOCUMENT", unique=true, nullable=false)
    public Long getIdDocument() {
        return this.idDocument;
    }
    
    public void setIdDocument(Long idDocument) {
        this.idDocument = idDocument;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARENT")
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
    
    @Column(name="FILE_NAME", length=256)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="NAME", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="RELATIVE_PATH", length=256)
    public String getRelativePath() {
        return this.relativePath;
    }
    
    public void setRelativePath(String relativePath) {
        this.relativePath = relativePath;
    }
    
    @Column(name="SIZE")
    public Long getSize() {
        return this.size;
    }
    
    public void setSize(Long size) {
        this.size = size;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="document")
    public Set<TaskDoc> getTaskDocs() {
        return this.taskDocs;
    }
    
    public void setTaskDocs(Set<TaskDoc> taskDocs) {
        this.taskDocs = taskDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="document")
    public Set<IssueDoc> getIssueDocs() {
        return this.issueDocs;
    }
    
    public void setIssueDocs(Set<IssueDoc> issueDocs) {
        this.issueDocs = issueDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="document")
    public Set<ProjectDoc> getProjectDocs() {
        return this.projectDocs;
    }
    
    public void setProjectDocs(Set<ProjectDoc> projectDocs) {
        this.projectDocs = projectDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="document")
    public Set<Document> getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set<Document> documents) {
        this.documents = documents;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="documentByLogo")
    public Set<Company> getCompaniesForLogo() {
        return this.companiesForLogo;
    }
    
    public void setCompaniesForLogo(Set<Company> companiesForLogo) {
        this.companiesForLogo = companiesForLogo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="documentByLicense")
    public Set<Company> getCompaniesForLicense() {
        return this.companiesForLicense;
    }
    
    public void setCompaniesForLicense(Set<Company> companiesForLicense) {
        this.companiesForLicense = companiesForLicense;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="document")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


