package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EAnswerType generated by hbm2java
 */
@Entity
@Table(name="e_answer_type"
)
public class EAnswerType  implements java.io.Serializable {


     private Long idAnswerType;
     private String answerType;
     private Set<EAnswer> EAnswers = new HashSet<EAnswer>(0);

    public EAnswerType() {
    }

	
    public EAnswerType(Long idAnswerType) {
        this.idAnswerType = idAnswerType;
    }
    public EAnswerType(Long idAnswerType, String answerType, Set<EAnswer> EAnswers) {
       this.idAnswerType = idAnswerType;
       this.answerType = answerType;
       this.EAnswers = EAnswers;
    }
   
     @Id 
    
    @Column(name="id_answer_type", unique=true, nullable=false)
    public Long getIdAnswerType() {
        return this.idAnswerType;
    }
    
    public void setIdAnswerType(Long idAnswerType) {
        this.idAnswerType = idAnswerType;
    }
    
    @Column(name="answer_type", length=20)
    public String getAnswerType() {
        return this.answerType;
    }
    
    public void setAnswerType(String answerType) {
        this.answerType = answerType;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="EAnswerType")
    public Set<EAnswer> getEAnswers() {
        return this.EAnswers;
    }
    
    public void setEAnswers(Set<EAnswer> EAnswers) {
        this.EAnswers = EAnswers;
    }




}


