package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EAnswer generated by hbm2java
 */
@Entity
@Table(name="e_answer"
    ,catalog="jms4"
)
public class EAnswer  implements java.io.Serializable {


     private Long idAnswer;
     private EAnswerType EAnswerType;
     private String des;

    public EAnswer() {
    }

	
    public EAnswer(Long idAnswer) {
        this.idAnswer = idAnswer;
    }
    public EAnswer(Long idAnswer, EAnswerType EAnswerType, String des) {
       this.idAnswer = idAnswer;
       this.EAnswerType = EAnswerType;
       this.des = des;
    }
   
     @Id 
    
    @Column(name="id_answer", unique=true, nullable=false)
    public Long getIdAnswer() {
        return this.idAnswer;
    }
    
    public void setIdAnswer(Long idAnswer) {
        this.idAnswer = idAnswer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_answer_type")
    public EAnswerType getEAnswerType() {
        return this.EAnswerType;
    }
    
    public void setEAnswerType(EAnswerType EAnswerType) {
        this.EAnswerType = EAnswerType;
    }
    
    @Column(name="des", length=64)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }




}


