package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ECategoryItem generated by hbm2java
 */
@Entity
@Table(name="e_category_item"
    ,catalog="jms4"
)
public class ECategoryItem  implements java.io.Serializable {


     private Long idCategoryItem;
     private EWorkCategoryDic EWorkCategoryDic;
     private EType EType;
     private ECheckItemDic ECheckItemDic;
     private ELevelDic ELevelDic;
     private Set<EEhsD> EEhsDs = new HashSet<EEhsD>(0);

    public ECategoryItem() {
    }

	
    public ECategoryItem(Long idCategoryItem) {
        this.idCategoryItem = idCategoryItem;
    }
    public ECategoryItem(Long idCategoryItem, EWorkCategoryDic EWorkCategoryDic, EType EType, ECheckItemDic ECheckItemDic, ELevelDic ELevelDic, Set<EEhsD> EEhsDs) {
       this.idCategoryItem = idCategoryItem;
       this.EWorkCategoryDic = EWorkCategoryDic;
       this.EType = EType;
       this.ECheckItemDic = ECheckItemDic;
       this.ELevelDic = ELevelDic;
       this.EEhsDs = EEhsDs;
    }
   
     @Id 
    
    @Column(name="id_category_item", unique=true, nullable=false)
    public Long getIdCategoryItem() {
        return this.idCategoryItem;
    }
    
    public void setIdCategoryItem(Long idCategoryItem) {
        this.idCategoryItem = idCategoryItem;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_work_category")
    public EWorkCategoryDic getEWorkCategoryDic() {
        return this.EWorkCategoryDic;
    }
    
    public void setEWorkCategoryDic(EWorkCategoryDic EWorkCategoryDic) {
        this.EWorkCategoryDic = EWorkCategoryDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_type")
    public EType getEType() {
        return this.EType;
    }
    
    public void setEType(EType EType) {
        this.EType = EType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_check_item")
    public ECheckItemDic getECheckItemDic() {
        return this.ECheckItemDic;
    }
    
    public void setECheckItemDic(ECheckItemDic ECheckItemDic) {
        this.ECheckItemDic = ECheckItemDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="initial")
    public ELevelDic getELevelDic() {
        return this.ELevelDic;
    }
    
    public void setELevelDic(ELevelDic ELevelDic) {
        this.ELevelDic = ELevelDic;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ECategoryItem")
    public Set<EEhsD> getEEhsDs() {
        return this.EEhsDs;
    }
    
    public void setEEhsDs(Set<EEhsD> EEhsDs) {
        this.EEhsDs = EEhsDs;
    }




}


