package com.jms.domain.db;
// Generated 2016-10-10 10:16:43 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EhsRecord generated by hbm2java
 */
@Entity
@Table(name="ehs_record"
    ,catalog="jms5"
)
public class EhsRecord  implements java.io.Serializable {


     private Long idEhsRecord;
     private EhsItem ehsItem;
     private Date date;
     private Long idOp;
     private Long idShiftD;
     private Date creationTime;
     private Long idSup;
     private String remark;
     private Date supTime;
     private Long status;
     private Long idCompany;

    public EhsRecord() {
    }

	
    public EhsRecord(Long idEhsRecord) {
        this.idEhsRecord = idEhsRecord;
    }
    public EhsRecord(Long idEhsRecord, EhsItem ehsItem, Date date, Long idOp, Long idShiftD, Date creationTime, Long idSup, String remark, Date supTime, Long status, Long idCompany) {
       this.idEhsRecord = idEhsRecord;
       this.ehsItem = ehsItem;
       this.date = date;
       this.idOp = idOp;
       this.idShiftD = idShiftD;
       this.creationTime = creationTime;
       this.idSup = idSup;
       this.remark = remark;
       this.supTime = supTime;
       this.status = status;
       this.idCompany = idCompany;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ehs_record", unique=true, nullable=false)
    public Long getIdEhsRecord() {
        return this.idEhsRecord;
    }
    
    public void setIdEhsRecord(Long idEhsRecord) {
        this.idEhsRecord = idEhsRecord;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ehs")
    public EhsItem getEhsItem() {
        return this.ehsItem;
    }
    
    public void setEhsItem(EhsItem ehsItem) {
        this.ehsItem = ehsItem;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="id_op")
    public Long getIdOp() {
        return this.idOp;
    }
    
    public void setIdOp(Long idOp) {
        this.idOp = idOp;
    }
    
    @Column(name="id_shift_d")
    public Long getIdShiftD() {
        return this.idShiftD;
    }
    
    public void setIdShiftD(Long idShiftD) {
        this.idShiftD = idShiftD;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_time", length=19)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    
    @Column(name="id_sup")
    public Long getIdSup() {
        return this.idSup;
    }
    
    public void setIdSup(Long idSup) {
        this.idSup = idSup;
    }
    
    @Column(name="remark", length=256)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sup_time", length=19)
    public Date getSupTime() {
        return this.supTime;
    }
    
    public void setSupTime(Date supTime) {
        this.supTime = supTime;
    }
    
    @Column(name="status")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    
    @Column(name="id_company")
    public Long getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Long idCompany) {
        this.idCompany = idCompany;
    }




}


