package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ELevelDic generated by hbm2java
 */
@Entity
@Table(name="e_level_dic"
    ,catalog="jms4"
)
public class ELevelDic  implements java.io.Serializable {


     private Long idLevel;
     private String des;
     private Set<ECategoryItem> ECategoryItems = new HashSet<ECategoryItem>(0);
     private Set<EEhsD> EEhsDs = new HashSet<EEhsD>(0);
     private Set<EEhs> EEhses = new HashSet<EEhs>(0);

    public ELevelDic() {
    }

	
    public ELevelDic(Long idLevel) {
        this.idLevel = idLevel;
    }
    public ELevelDic(Long idLevel, String des, Set<ECategoryItem> ECategoryItems, Set<EEhsD> EEhsDs, Set<EEhs> EEhses) {
       this.idLevel = idLevel;
       this.des = des;
       this.ECategoryItems = ECategoryItems;
       this.EEhsDs = EEhsDs;
       this.EEhses = EEhses;
    }
   
     @Id 
    
    @Column(name="id_level", unique=true, nullable=false)
    public Long getIdLevel() {
        return this.idLevel;
    }
    
    public void setIdLevel(Long idLevel) {
        this.idLevel = idLevel;
    }
    
    @Column(name="des", length=20)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ELevelDic")
    public Set<ECategoryItem> getECategoryItems() {
        return this.ECategoryItems;
    }
    
    public void setECategoryItems(Set<ECategoryItem> ECategoryItems) {
        this.ECategoryItems = ECategoryItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ELevelDic")
    public Set<EEhsD> getEEhsDs() {
        return this.EEhsDs;
    }
    
    public void setEEhsDs(Set<EEhsD> EEhsDs) {
        this.EEhsDs = EEhsDs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ELevelDic")
    public Set<EEhs> getEEhses() {
        return this.EEhses;
    }
    
    public void setEEhses(Set<EEhs> EEhses) {
        this.EEhses = EEhses;
    }




}


