package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EStatus generated by hbm2java
 */
@Entity
@Table(name="e_status"
    ,catalog="jms4"
)
public class EStatus  implements java.io.Serializable {


     private Long idEstatus;
     private String des;
     private Set<EEhs> EEhses = new HashSet<EEhs>(0);

    public EStatus() {
    }

	
    public EStatus(Long idEstatus) {
        this.idEstatus = idEstatus;
    }
    public EStatus(Long idEstatus, String des, Set<EEhs> EEhses) {
       this.idEstatus = idEstatus;
       this.des = des;
       this.EEhses = EEhses;
    }
   
     @Id 
    
    @Column(name="id_estatus", unique=true, nullable=false)
    public Long getIdEstatus() {
        return this.idEstatus;
    }
    
    public void setIdEstatus(Long idEstatus) {
        this.idEstatus = idEstatus;
    }
    
    @Column(name="des", length=20)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="EStatus")
    public Set<EEhs> getEEhses() {
        return this.EEhses;
    }
    
    public void setEEhses(Set<EEhs> EEhses) {
        this.EEhses = EEhses;
    }




}


