package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EType generated by hbm2java
 */
@Entity
@Table(name="e_type"
    ,catalog="jms4"
)
public class EType  implements java.io.Serializable {


     private Long idType;
     private Company company;
     private String des;
     private Set<ECategoryItem> ECategoryItems = new HashSet<ECategoryItem>(0);

    public EType() {
    }

	
    public EType(Long idType) {
        this.idType = idType;
    }
    public EType(Long idType, Company company, String des, Set<ECategoryItem> ECategoryItems) {
       this.idType = idType;
       this.company = company;
       this.des = des;
       this.ECategoryItems = ECategoryItems;
    }
   
     @Id 
    
    @Column(name="id_type", unique=true, nullable=false)
    public Long getIdType() {
        return this.idType;
    }
    
    public void setIdType(Long idType) {
        this.idType = idType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="des", length=64)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="EType")
    public Set<ECategoryItem> getECategoryItems() {
        return this.ECategoryItems;
    }
    
    public void setECategoryItems(Set<ECategoryItem> ECategoryItems) {
        this.ECategoryItems = ECategoryItems;
    }




}


