package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EWorkCategoryDic generated by hbm2java
 */
@Entity
@Table(name="e_work_category_dic"
    ,catalog="jms5"
)
public class EWorkCategoryDic  implements java.io.Serializable {


     private Long idWorkCategory;
     private Company company;
     private String workCategory;
     private String des;
     private Set<PRoutineDCategory> PRoutineDCategories = new HashSet<PRoutineDCategory>(0);
     private Set<ECategoryItem> ECategoryItems = new HashSet<ECategoryItem>(0);
     private Set<EEhs> EEhses = new HashSet<EEhs>(0);

    public EWorkCategoryDic() {
    }

    public EWorkCategoryDic(Company company, String workCategory, String des, Set<PRoutineDCategory> PRoutineDCategories, Set<ECategoryItem> ECategoryItems, Set<EEhs> EEhses) {
       this.company = company;
       this.workCategory = workCategory;
       this.des = des;
       this.PRoutineDCategories = PRoutineDCategories;
       this.ECategoryItems = ECategoryItems;
       this.EEhses = EEhses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_work_category", unique=true, nullable=false)
    public Long getIdWorkCategory() {
        return this.idWorkCategory;
    }
    
    public void setIdWorkCategory(Long idWorkCategory) {
        this.idWorkCategory = idWorkCategory;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="work_category", length=20)
    public String getWorkCategory() {
        return this.workCategory;
    }
    
    public void setWorkCategory(String workCategory) {
        this.workCategory = workCategory;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="EWorkCategoryDic")
    public Set<PRoutineDCategory> getPRoutineDCategories() {
        return this.PRoutineDCategories;
    }
    
    public void setPRoutineDCategories(Set<PRoutineDCategory> PRoutineDCategories) {
        this.PRoutineDCategories = PRoutineDCategories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="EWorkCategoryDic")
    public Set<ECategoryItem> getECategoryItems() {
        return this.ECategoryItems;
    }
    
    public void setECategoryItems(Set<ECategoryItem> ECategoryItems) {
        this.ECategoryItems = ECategoryItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="EWorkCategoryDic")
    public Set<EEhs> getEEhses() {
        return this.EEhses;
    }
    
    public void setEEhses(Set<EEhs> EEhses) {
        this.EEhses = EEhses;
    }




}


