package com.jms.domain.db;
// Generated 2015-6-14 15:39:31 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Issue generated by hbm2java
 */
@Entity
@Table(name="issue"
    ,catalog="jms"
)
public class Issue  implements java.io.Serializable {


     private Integer idIssue;
     private SysDicD sysDicDByStatus;
     private Project project;
     private SysDicD sysDicDByPriority;
     private String name;
     private String description;
     private Set<IssueDoc> issueDocs = new HashSet<IssueDoc>(0);
     private Set<IssueComment> issueComments = new HashSet<IssueComment>(0);

    public Issue() {
    }

    public Issue(SysDicD sysDicDByStatus, Project project, SysDicD sysDicDByPriority, String name, String description, Set<IssueDoc> issueDocs, Set<IssueComment> issueComments) {
       this.sysDicDByStatus = sysDicDByStatus;
       this.project = project;
       this.sysDicDByPriority = sysDicDByPriority;
       this.name = name;
       this.description = description;
       this.issueDocs = issueDocs;
       this.issueComments = issueComments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_ISSUE", unique=true, nullable=false)
    public Integer getIdIssue() {
        return this.idIssue;
    }
    
    public void setIdIssue(Integer idIssue) {
        this.idIssue = idIssue;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public SysDicD getSysDicDByStatus() {
        return this.sysDicDByStatus;
    }
    
    public void setSysDicDByStatus(SysDicD sysDicDByStatus) {
        this.sysDicDByStatus = sysDicDByStatus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROJECT")
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRIORITY")
    public SysDicD getSysDicDByPriority() {
        return this.sysDicDByPriority;
    }
    
    public void setSysDicDByPriority(SysDicD sysDicDByPriority) {
        this.sysDicDByPriority = sysDicDByPriority;
    }
    
    @Column(name="NAME", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="issue")
    public Set<IssueDoc> getIssueDocs() {
        return this.issueDocs;
    }
    
    public void setIssueDocs(Set<IssueDoc> issueDocs) {
        this.issueDocs = issueDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="issue")
    public Set<IssueComment> getIssueComments() {
        return this.issueComments;
    }
    
    public void setIssueComments(Set<IssueComment> issueComments) {
        this.issueComments = issueComments;
    }




}


