package com.jms.domain.db;
// Generated 2015-6-7 13:49:29 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Issue generated by hbm2java
 */
@Entity
@Table(name="issue"
    ,catalog="jms"
)
public class Issue  implements java.io.Serializable {


     private Integer idIssue;
     private Project project;
     private String name;
     private String description;
     private Integer priority;
     private String status;
     private Set<IssueDoc> issueDocs = new HashSet<IssueDoc>(0);
     private Set<IssueComment> issueComments = new HashSet<IssueComment>(0);

    public Issue() {
    }

	
    public Issue(Integer idIssue) {
        this.idIssue = idIssue;
    }
    public Issue(Integer idIssue, Project project, String name, String description, Integer priority, String status, Set<IssueDoc> issueDocs, Set<IssueComment> issueComments) {
       this.idIssue = idIssue;
       this.project = project;
       this.name = name;
       this.description = description;
       this.priority = priority;
       this.status = status;
       this.issueDocs = issueDocs;
       this.issueComments = issueComments;
    }
   
     @Id 
     @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_ISSUE", unique=true, nullable=false)
    public Integer getIdIssue() {
        return this.idIssue;
    }
    
    public void setIdIssue(Integer idIssue) {
        this.idIssue = idIssue;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROJECT")
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    
    @Column(name="NAME", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    
    @Column(name="STATUS", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="issue")
    public Set<IssueDoc> getIssueDocs() {
        return this.issueDocs;
    }
    
    public void setIssueDocs(Set<IssueDoc> issueDocs) {
        this.issueDocs = issueDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="issue")
    public Set<IssueComment> getIssueComments() {
        return this.issueComments;
    }
    
    public void setIssueComments(Set<IssueComment> issueComments) {
        this.issueComments = issueComments;
    }




}


