package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JmsEvent generated by hbm2java
 */
@Entity
@Table(name="jms_event"
    ,catalog="jms3"
)
public class JmsEvent  implements java.io.Serializable {


     private Long idEvent;
     private JmsEvent jmsEvent;
     private Apps apps;
     private String class_;
     private String name;
     private String description;
     private String template;
     private Set<Notification> notifications = new HashSet<Notification>(0);
     private Set<JmsEvent> jmsEvents = new HashSet<JmsEvent>(0);

    public JmsEvent() {
    }

    public JmsEvent(JmsEvent jmsEvent, Apps apps, String class_, String name, String description, String template, Set<Notification> notifications, Set<JmsEvent> jmsEvents) {
       this.jmsEvent = jmsEvent;
       this.apps = apps;
       this.class_ = class_;
       this.name = name;
       this.description = description;
       this.template = template;
       this.notifications = notifications;
       this.jmsEvents = jmsEvents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_event", unique=true, nullable=false)
    public Long getIdEvent() {
        return this.idEvent;
    }
    
    public void setIdEvent(Long idEvent) {
        this.idEvent = idEvent;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent")
    public JmsEvent getJmsEvent() {
        return this.jmsEvent;
    }
    
    public void setJmsEvent(JmsEvent jmsEvent) {
        this.jmsEvent = jmsEvent;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_app")
    public Apps getApps() {
        return this.apps;
    }
    
    public void setApps(Apps apps) {
        this.apps = apps;
    }
    
    @Column(name="class", length=100)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="template", length=64)
    public String getTemplate() {
        return this.template;
    }
    
    public void setTemplate(String template) {
        this.template = template;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="jmsEvent")
    public Set<Notification> getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set<Notification> notifications) {
        this.notifications = notifications;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="jmsEvent")
    public Set<JmsEvent> getJmsEvents() {
        return this.jmsEvents;
    }
    
    public void setJmsEvents(Set<JmsEvent> jmsEvents) {
        this.jmsEvents = jmsEvents;
    }




}


