package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MDept generated by hbm2java
 */
@Entity
@Table(name="m_dept"
    ,catalog="jms4"
)
public class MDept  implements java.io.Serializable {


     private Long idDept;
     private MStatusDic MStatusDic;
     private SCostCenter SCostCenter;
     private String des;
     private Set<MMainItem> MMainItems = new HashSet<MMainItem>(0);
     private Set<PSubCode> PSubCodes = new HashSet<PSubCode>(0);
     private Set<MRemark> MRemarks = new HashSet<MRemark>(0);

    public MDept() {
    }

	
    public MDept(Long idDept) {
        this.idDept = idDept;
    }
    public MDept(Long idDept, MStatusDic MStatusDic, SCostCenter SCostCenter, String des, Set<MMainItem> MMainItems, Set<PSubCode> PSubCodes, Set<MRemark> MRemarks) {
       this.idDept = idDept;
       this.MStatusDic = MStatusDic;
       this.SCostCenter = SCostCenter;
       this.des = des;
       this.MMainItems = MMainItems;
       this.PSubCodes = PSubCodes;
       this.MRemarks = MRemarks;
    }
   
     @Id 
    
    @Column(name="id_dept", unique=true, nullable=false)
    public Long getIdDept() {
        return this.idDept;
    }
    
    public void setIdDept(Long idDept) {
        this.idDept = idDept;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mstatus_dic")
    public MStatusDic getMStatusDic() {
        return this.MStatusDic;
    }
    
    public void setMStatusDic(MStatusDic MStatusDic) {
        this.MStatusDic = MStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cost_center")
    public SCostCenter getSCostCenter() {
        return this.SCostCenter;
    }
    
    public void setSCostCenter(SCostCenter SCostCenter) {
        this.SCostCenter = SCostCenter;
    }
    
    @Column(name="des", length=32)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MDept")
    public Set<MMainItem> getMMainItems() {
        return this.MMainItems;
    }
    
    public void setMMainItems(Set<MMainItem> MMainItems) {
        this.MMainItems = MMainItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MDept")
    public Set<PSubCode> getPSubCodes() {
        return this.PSubCodes;
    }
    
    public void setPSubCodes(Set<PSubCode> PSubCodes) {
        this.PSubCodes = PSubCodes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MDept")
    public Set<MRemark> getMRemarks() {
        return this.MRemarks;
    }
    
    public void setMRemarks(Set<MRemark> MRemarks) {
        this.MRemarks = MRemarks;
    }




}


