package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MHistoryPart generated by hbm2java
 */
@Entity
@Table(name="m_history_part"
    ,catalog="jms4"
)
public class MHistoryPart  implements java.io.Serializable {


     private Long idHistoryPart;
     private SMaterial SMaterial;
     private MRepairHistory MRepairHistory;
     private Long qty;

    public MHistoryPart() {
    }

	
    public MHistoryPart(Long idHistoryPart) {
        this.idHistoryPart = idHistoryPart;
    }
    public MHistoryPart(Long idHistoryPart, SMaterial SMaterial, MRepairHistory MRepairHistory, Long qty) {
       this.idHistoryPart = idHistoryPart;
       this.SMaterial = SMaterial;
       this.MRepairHistory = MRepairHistory;
       this.qty = qty;
    }
   
     @Id 
    
    @Column(name="id_history_part", unique=true, nullable=false)
    public Long getIdHistoryPart() {
        return this.idHistoryPart;
    }
    
    public void setIdHistoryPart(Long idHistoryPart) {
        this.idHistoryPart = idHistoryPart;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_material")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_repair_history")
    public MRepairHistory getMRepairHistory() {
        return this.MRepairHistory;
    }
    
    public void setMRepairHistory(MRepairHistory MRepairHistory) {
        this.MRepairHistory = MRepairHistory;
    }
    
    @Column(name="qty")
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }




}


