package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MMachineGroup generated by hbm2java
 */
@Entity
@Table(name="m_machine_group"
    ,catalog="jms4"
)
public class MMachineGroup  implements java.io.Serializable {


     private Long idGroup;
     private String groupName;
     private Set<MMachine> MMachines = new HashSet<MMachine>(0);

    public MMachineGroup() {
    }

	
    public MMachineGroup(Long idGroup) {
        this.idGroup = idGroup;
    }
    public MMachineGroup(Long idGroup, String groupName, Set<MMachine> MMachines) {
       this.idGroup = idGroup;
       this.groupName = groupName;
       this.MMachines = MMachines;
    }
   
     @Id 
    
    @Column(name="id_group", unique=true, nullable=false)
    public Long getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(Long idGroup) {
        this.idGroup = idGroup;
    }
    
    @Column(name="group_name", length=20)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachineGroup")
    public Set<MMachine> getMMachines() {
        return this.MMachines;
    }
    
    public void setMMachines(Set<MMachine> MMachines) {
        this.MMachines = MMachines;
    }




}


