package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MMachine generated by hbm2java
 */
@Entity
@Table(name="m_machine"
    ,catalog="jms5"
)
public class MMachine  implements java.io.Serializable {


     private Long idMachine;
     private Company company;
     private PWorkCenter PWorkCenter;
     private PWip PWip;
     private PLine PLine;
     private MMachineGroup MMachineGroup;
     private SBin SBin;
     private MStatusDic MStatusDic;
     private String code;
     private String name;
     private Long totalKwa;
     private String spec;
     private Date satCompletedDate;
     
     private  BigDecimal mttr;
     private  BigDecimal mtbf;
     private  BigDecimal downtime;
  
     private Set<MRepairHistory> MRepairHistories = new HashSet<MRepairHistory>(0);
     private Set<PCPp> PCPps = new HashSet<PCPp>(0);
     private Set<QFaiInFinal> QFaiInFinals = new HashSet<QFaiInFinal>(0);
     private Set<MMainItem> MMainItems = new HashSet<MMainItem>(0);
     private Set<MRemark> MRemarks = new HashSet<MRemark>(0);
     private Set<MSparePart> MSpareParts = new HashSet<MSparePart>(0);
     private Set<PStopsPlan> PStopsPlans = new HashSet<PStopsPlan>(0);
     private Set<PCheckTime> PCheckTimes = new HashSet<PCheckTime>(0);

    public MMachine() {
    }

    public MMachine(Company company, PWorkCenter PWorkCenter, PWip PWip, PLine PLine, MMachineGroup MMachineGroup, SBin SBin, MStatusDic MStatusDic, String code, String name, Long totalKwa, String spec, Date satCompletedDate, Set<MRepairHistory> MRepairHistories, Set<PCPp> PCPps, Set<QFaiInFinal> QFaiInFinals, Set<MMainItem> MMainItems, Set<MRemark> MRemarks, Set<MSparePart> MSpareParts, Set<PStopsPlan> PStopsPlans, Set<PCheckTime> PCheckTimes) {
       this.company = company;
       this.PWorkCenter = PWorkCenter;
       this.PWip = PWip;
       this.PLine = PLine;
       this.MMachineGroup = MMachineGroup;
       this.SBin = SBin;
       this.MStatusDic = MStatusDic;
       this.code = code;
       this.name = name;
       this.totalKwa = totalKwa;
       this.spec = spec;
       this.satCompletedDate = satCompletedDate;
       this.MRepairHistories = MRepairHistories;
       this.PCPps = PCPps;
       this.QFaiInFinals = QFaiInFinals;
       this.MMainItems = MMainItems;
       this.MRemarks = MRemarks;
       this.MSpareParts = MSpareParts;
       this.PStopsPlans = PStopsPlans;
       this.PCheckTimes = PCheckTimes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_machine", unique=true, nullable=false)
    public Long getIdMachine() {
        return this.idMachine;
    }
    
    public void setIdMachine(Long idMachine) {
        this.idMachine = idMachine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wc")
    public PWorkCenter getPWorkCenter() {
        return this.PWorkCenter;
    }
    
    public void setPWorkCenter(PWorkCenter PWorkCenter) {
        this.PWorkCenter = PWorkCenter;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wip")
    public PWip getPWip() {
        return this.PWip;
    }
    
    public void setPWip(PWip PWip) {
        this.PWip = PWip;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pline")
    public PLine getPLine() {
        return this.PLine;
    }
    
    public void setPLine(PLine PLine) {
        this.PLine = PLine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_group")
    public MMachineGroup getMMachineGroup() {
        return this.MMachineGroup;
    }
    
    public void setMMachineGroup(MMachineGroup MMachineGroup) {
        this.MMachineGroup = MMachineGroup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="location")
    public SBin getSBin() {
        return this.SBin;
    }
    
    public void setSBin(SBin SBin) {
        this.SBin = SBin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mstatus_dic")
    public MStatusDic getMStatusDic() {
        return this.MStatusDic;
    }
    
    public void setMStatusDic(MStatusDic MStatusDic) {
        this.MStatusDic = MStatusDic;
    }
    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="total_kwa", precision=10, scale=0)
    public Long getTotalKwa() {
        return this.totalKwa;
    }
    
    public void setTotalKwa(Long totalKwa) {
        this.totalKwa = totalKwa;
    }
    
    @Column(name="spec", length=64)
    public String getSpec() {
        return this.spec;
    }
    
    public void setSpec(String spec) {
        this.spec = spec;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="sat_completed_date", length=10)
    public Date getSatCompletedDate() {
        return this.satCompletedDate;
    }
    
    public void setSatCompletedDate(Date satCompletedDate) {
        this.satCompletedDate = satCompletedDate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<MRepairHistory> getMRepairHistories() {
        return this.MRepairHistories;
    }
    
    public void setMRepairHistories(Set<MRepairHistory> MRepairHistories) {
        this.MRepairHistories = MRepairHistories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<PCPp> getPCPps() {
        return this.PCPps;
    }
    
    public void setPCPps(Set<PCPp> PCPps) {
        this.PCPps = PCPps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<QFaiInFinal> getQFaiInFinals() {
        return this.QFaiInFinals;
    }
    
    public void setQFaiInFinals(Set<QFaiInFinal> QFaiInFinals) {
        this.QFaiInFinals = QFaiInFinals;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<MMainItem> getMMainItems() {
        return this.MMainItems;
    }
    
    public void setMMainItems(Set<MMainItem> MMainItems) {
        this.MMainItems = MMainItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<MRemark> getMRemarks() {
        return this.MRemarks;
    }
    
    public void setMRemarks(Set<MRemark> MRemarks) {
        this.MRemarks = MRemarks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<MSparePart> getMSpareParts() {
        return this.MSpareParts;
    }
    
    public void setMSpareParts(Set<MSparePart> MSpareParts) {
        this.MSpareParts = MSpareParts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<PStopsPlan> getPStopsPlans() {
        return this.PStopsPlans;
    }
    
    public void setPStopsPlans(Set<PStopsPlan> PStopsPlans) {
        this.PStopsPlans = PStopsPlans;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MMachine")
    public Set<PCheckTime> getPCheckTimes() {
        return this.PCheckTimes;
    }
    
    public void setPCheckTimes(Set<PCheckTime> PCheckTimes) {
        this.PCheckTimes = PCheckTimes;
    }

    @Column(name="mttr", scale=4)
	public BigDecimal getMttr() {
		return mttr;
	}

	public void setMttr(BigDecimal mttr) {
		this.mttr = mttr;
	}

    @Column(name="mtbf", scale=4)
	public BigDecimal getMtbf() {
		return mtbf;
	}

	public void setMtbf(BigDecimal mtbf) {
		this.mtbf = mtbf;
	}

    @Column(name="downtime", scale=4)
	public BigDecimal getDowntime() {
		return downtime;
	}

	public void setDowntime(BigDecimal downtime) {
		this.downtime = downtime;
	}




}


