package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MSparePart generated by hbm2java
 */
@Entity
@Table(name="m_spare_part"
    ,catalog="jms4"
)
public class MSparePart  implements java.io.Serializable {


     private Long idPart;
     private MMachine MMachine;
     private SMaterial SMaterial;
     private MStatusDic MStatusDic;
     private Long orderBy;
     private Long actualQty;
     private Long incoming;
     private Long outgoing;

    public MSparePart() {
    }

	
    public MSparePart(Long idPart) {
        this.idPart = idPart;
    }
    public MSparePart(Long idPart, MMachine MMachine, SMaterial SMaterial, MStatusDic MStatusDic, Long orderBy, Long actualQty, Long incoming, Long outgoing) {
       this.idPart = idPart;
       this.MMachine = MMachine;
       this.SMaterial = SMaterial;
       this.MStatusDic = MStatusDic;
       this.orderBy = orderBy;
       this.actualQty = actualQty;
       this.incoming = incoming;
       this.outgoing = outgoing;
    }
   
     @Id 
    
    @Column(name="id_part", unique=true, nullable=false)
    public Long getIdPart() {
        return this.idPart;
    }
    
    public void setIdPart(Long idPart) {
        this.idPart = idPart;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_machine")
    public MMachine getMMachine() {
        return this.MMachine;
    }
    
    public void setMMachine(MMachine MMachine) {
        this.MMachine = MMachine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_material")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mstatus_dic")
    public MStatusDic getMStatusDic() {
        return this.MStatusDic;
    }
    
    public void setMStatusDic(MStatusDic MStatusDic) {
        this.MStatusDic = MStatusDic;
    }
    
    @Column(name="order_by")
    public Long getOrderBy() {
        return this.orderBy;
    }
    
    public void setOrderBy(Long orderBy) {
        this.orderBy = orderBy;
    }
    
    @Column(name="actual_qty")
    public Long getActualQty() {
        return this.actualQty;
    }
    
    public void setActualQty(Long actualQty) {
        this.actualQty = actualQty;
    }
    
    @Column(name="incoming")
    public Long getIncoming() {
        return this.incoming;
    }
    
    public void setIncoming(Long incoming) {
        this.incoming = incoming;
    }
    
    @Column(name="outgoing")
    public Long getOutgoing() {
        return this.outgoing;
    }
    
    public void setOutgoing(Long outgoing) {
        this.outgoing = outgoing;
    }




}


