package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MStatusDic generated by hbm2java
 */
@Entity
@Table(name="m_status_dic"
    ,catalog="jms4"
)
public class MStatusDic  implements java.io.Serializable {


     private Long idMstatusDic;
     private String name;
     private String des;
     private String source;
     private Set<MDept> MDepts = new HashSet<MDept>(0);
     private Set<MRepairHistory> MRepairHistories = new HashSet<MRepairHistory>(0);
     private Set<MSparePart> MSpareParts = new HashSet<MSparePart>(0);

    public MStatusDic() {
    }

	
    public MStatusDic(Long idMstatusDic) {
        this.idMstatusDic = idMstatusDic;
    }
    public MStatusDic(Long idMstatusDic, String name, String des, String source, Set<MDept> MDepts, Set<MRepairHistory> MRepairHistories, Set<MSparePart> MSpareParts) {
       this.idMstatusDic = idMstatusDic;
       this.name = name;
       this.des = des;
       this.source = source;
       this.MDepts = MDepts;
       this.MRepairHistories = MRepairHistories;
       this.MSpareParts = MSpareParts;
    }
   
     @Id 
    
    @Column(name="id_mstatus_dic", unique=true, nullable=false)
    public Long getIdMstatusDic() {
        return this.idMstatusDic;
    }
    
    public void setIdMstatusDic(Long idMstatusDic) {
        this.idMstatusDic = idMstatusDic;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="source", length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MStatusDic")
    public Set<MDept> getMDepts() {
        return this.MDepts;
    }
    
    public void setMDepts(Set<MDept> MDepts) {
        this.MDepts = MDepts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MStatusDic")
    public Set<MRepairHistory> getMRepairHistories() {
        return this.MRepairHistories;
    }
    
    public void setMRepairHistories(Set<MRepairHistory> MRepairHistories) {
        this.MRepairHistories = MRepairHistories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="MStatusDic")
    public Set<MSparePart> getMSpareParts() {
        return this.MSpareParts;
    }
    
    public void setMSpareParts(Set<MSparePart> MSpareParts) {
        this.MSpareParts = MSpareParts;
    }




}


