package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notice generated by hbm2java
 */
@Entity
@Table(name="notice"
    ,catalog="jms4"
)
public class Notice  implements java.io.Serializable {


     private Long idNotice;
     private Users users;
     private String title;
     private String notice;
     private String remark;
     private Date publishTime;

    public Notice() {
    }

	
    public Notice(Long idNotice) {
        this.idNotice = idNotice;
    }
    public Notice(Long idNotice, Users users, String title, String notice, String remark, Date publishTime) {
       this.idNotice = idNotice;
       this.users = users;
       this.title = title;
       this.notice = notice;
       this.remark = remark;
       this.publishTime = publishTime;
    }
   
     @Id 
    
    @Column(name="id_notice", unique=true, nullable=false)
    public Long getIdNotice() {
        return this.idNotice;
    }
    
    public void setIdNotice(Long idNotice) {
        this.idNotice = idNotice;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="title", length=128)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="notice", length=4096)
    public String getNotice() {
        return this.notice;
    }
    
    public void setNotice(String notice) {
        this.notice = notice;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="publish_time", length=10)
    public Date getPublishTime() {
        return this.publishTime;
    }
    
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }




}


