package com.jms.domain.db;
// Generated 2015-6-29 13:44:42 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * NotiInstance generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "noti_instance_AUD")
@Entity
@Table(name="noti_instance"
    ,catalog="jms"
)
public class NotiInstance  implements java.io.Serializable {


     private Long idNotiInstance;
     private Notification notification;
     private Long idSource;
     private Long idReceiver;

    public NotiInstance() {
    }

	
    public NotiInstance(Long idNotiInstance) {
        this.idNotiInstance = idNotiInstance;
    }
    public NotiInstance(Long idNotiInstance, Notification notification, Long idSource, Long idReceiver) {
       this.idNotiInstance = idNotiInstance;
       this.notification = notification;
       this.idSource = idSource;
       this.idReceiver = idReceiver;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_NOTI_INSTANCE", unique=true, nullable=false)
    public Long getIdNotiInstance() {
        return this.idNotiInstance;
    }
    
    public void setIdNotiInstance(Long idNotiInstance) {
        this.idNotiInstance = idNotiInstance;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_NOTIFICATION")
    public Notification getNotification() {
        return this.notification;
    }
    
    public void setNotification(Notification notification) {
        this.notification = notification;
    }
    
    @Column(name="ID_SOURCE")
    public Long getIdSource() {
        return this.idSource;
    }
    
    public void setIdSource(Long idSource) {
        this.idSource = idSource;
    }
    
    @Column(name="ID_RECEIVER")
    public Long getIdReceiver() {
        return this.idReceiver;
    }
    
    public void setIdReceiver(Long idReceiver) {
        this.idReceiver = idReceiver;
    }




}


