package com.jms.domain.db;
// Generated 2016-10-5 10:11:12 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OCalendar generated by hbm2java
 */
@Entity
@Table(name="o_calendar"
    ,catalog="jms5"
)
public class OCalendar  implements java.io.Serializable {


     private Long idCalendar;
     private OCalendarType OCalendarType;
     private String name;
     private Long year;
     private Date date;
     private Long idCompany;
     private Long idShiftD;

    public OCalendar() {
    }

    public OCalendar(OCalendarType OCalendarType, String name, Long year, Date date, Long idCompany) {
       this.OCalendarType = OCalendarType;
       this.name = name;
       this.year = year;
       this.date = date;
       this.idCompany = idCompany;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_calendar", unique=true, nullable=false)
    public Long getIdCalendar() {
        return this.idCalendar;
    }
    
    public void setIdCalendar(Long idCalendar) {
        this.idCalendar = idCalendar;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_calendar_type")
    public OCalendarType getOCalendarType() {
        return this.OCalendarType;
    }
    
    public void setOCalendarType(OCalendarType OCalendarType) {
        this.OCalendarType = OCalendarType;
    }
    
    @Column(name="name", length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="year")
    public Long getYear() {
        return this.year;
    }
    
    public void setYear(Long year) {
        this.year = year;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="id_company")
    public Long getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Long idCompany) {
        this.idCompany = idCompany;
    }
    
    @Column(name="id_shift_d")
	public Long getIdShiftD() {
		return idShiftD;
	}

	public void setIdShiftD(Long idShiftD) {
		this.idShiftD = idShiftD;
	}




}


