package com.jms.domain.db;
// Generated 2016-10-5 10:11:12 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OCalendarType generated by hbm2java
 */
@Entity
@Table(name="o_calendar_type"
)
public class OCalendarType  implements java.io.Serializable {


     private Long idCalendarType;
     private String type;
     private Float salary;
     private Set<OCalendar> OCalendars = new HashSet<OCalendar>(0);

    public OCalendarType() {
    }

	
    public OCalendarType(Long idCalendarType) {
        this.idCalendarType = idCalendarType;
    }
    public OCalendarType(Long idCalendarType, String type, Float salary, Set<OCalendar> OCalendars) {
       this.idCalendarType = idCalendarType;
       this.type = type;
       this.salary = salary;
       this.OCalendars = OCalendars;
    }
   
     @Id 
    
    @Column(name="id_calendar_type", unique=true, nullable=false)
    public Long getIdCalendarType() {
        return this.idCalendarType;
    }
    
    public void setIdCalendarType(Long idCalendarType) {
        this.idCalendarType = idCalendarType;
    }
    
    @Column(name="type", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="salary", precision=12, scale=0)
    public Float getSalary() {
        return this.salary;
    }
    
    public void setSalary(Float salary) {
        this.salary = salary;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="OCalendarType")
    public Set<OCalendar> getOCalendars() {
        return this.OCalendars;
    }
    
    public void setOCalendars(Set<OCalendar> OCalendars) {
        this.OCalendars = OCalendars;
    }




}


