package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PActualSetup generated by hbm2java
 */
@Entity
@Table(name="p_actual_setup"
    ,catalog="jms4"
)
public class PActualSetup  implements java.io.Serializable {


     private Long idActualSetup;
     private PCPp PCPp;
     private Date actSt;
     private Date actFt;

    public PActualSetup() {
    }

	
    public PActualSetup(Long idActualSetup) {
        this.idActualSetup = idActualSetup;
    }
    public PActualSetup(Long idActualSetup, PCPp PCPp, Date actSt, Date actFt) {
       this.idActualSetup = idActualSetup;
       this.PCPp = PCPp;
       this.actSt = actSt;
       this.actFt = actFt;
    }
   
     @Id 
    
    @Column(name="id_actual_setup", unique=true, nullable=false)
    public Long getIdActualSetup() {
        return this.idActualSetup;
    }
    
    public void setIdActualSetup(Long idActualSetup) {
        this.idActualSetup = idActualSetup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_c_pp")
    public PCPp getPCPp() {
        return this.PCPp;
    }
    
    public void setPCPp(PCPp PCPp) {
        this.PCPp = PCPp;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="act_st", length=19)
    public Date getActSt() {
        return this.actSt;
    }
    
    public void setActSt(Date actSt) {
        this.actSt = actSt;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="act_ft", length=19)
    public Date getActFt() {
        return this.actFt;
    }
    
    public void setActFt(Date actFt) {
        this.actFt = actFt;
    }




}


