package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PAttDraw generated by hbm2java
 */
@Entity
@Table(name="p_att_draw"
    ,catalog="jms5"
)
public class PAttDraw  implements java.io.Serializable {


     private Long idAttDraw;
     private Users users;
     private String name;
     private String des;
     private String filename;
     private String orgFilename;
     private Date creationTime;
     private Set<PRoutineD> PRoutineDs = new HashSet<PRoutineD>(0);
     private Set<PRoutineDAtt> PRoutineDAtts = new HashSet<PRoutineDAtt>(0);

    public PAttDraw() {
    }

    public PAttDraw(Users users, String name, String des, String filename, String orgFilename, Date creationTime, Set<PRoutineD> PRoutineDs, Set<PRoutineDAtt> PRoutineDAtts) {
       this.users = users;
       this.name = name;
       this.des = des;
       this.filename = filename;
       this.orgFilename = orgFilename;
       this.creationTime = creationTime;
       this.PRoutineDs = PRoutineDs;
       this.PRoutineDAtts = PRoutineDAtts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_att_draw", unique=true, nullable=false)
    public Long getIdAttDraw() {
        return this.idAttDraw;
    }
    
    public void setIdAttDraw(Long idAttDraw) {
        this.idAttDraw = idAttDraw;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="upload_by")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="filename", length=128)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Column(name="org_filename", length=128)
    public String getOrgFilename() {
        return this.orgFilename;
    }
    
    public void setOrgFilename(String orgFilename) {
        this.orgFilename = orgFilename;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PAttDraw")
    public Set<PRoutineD> getPRoutineDs() {
        return this.PRoutineDs;
    }
    
    public void setPRoutineDs(Set<PRoutineD> PRoutineDs) {
        this.PRoutineDs = PRoutineDs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PAttDraw")
    public Set<PRoutineDAtt> getPRoutineDAtts() {
        return this.PRoutineDAtts;
    }
    
    public void setPRoutineDAtts(Set<PRoutineDAtt> PRoutineDAtts) {
        this.PRoutineDAtts = PRoutineDAtts;
    }




}


