package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PBom generated by hbm2java
 */
@Entity
@Table(name="p_bom"
    ,catalog="jms4"
)
public class PBom  implements java.io.Serializable {


     private Long idBom;
     private PWorkCenter PWorkCenter;
     private SMaterial SMaterial;
     private PBomLabel PBomLabel;
     private PBom PBom;
     private Long qpu;
     private Long orderBy;
     private Set<PMr> PMrs = new HashSet<PMr>(0);
     private Set<PWoBom> PWoBoms = new HashSet<PWoBom>(0);
     private Set<PBom> PBoms = new HashSet<PBom>(0);

    public PBom() {
    }

	
    public PBom(Long idBom) {
        this.idBom = idBom;
    }
    public PBom(Long idBom, PWorkCenter PWorkCenter, SMaterial SMaterial, PBomLabel PBomLabel, PBom PBom, Long qpu, Long orderBy, Set<PMr> PMrs, Set<PWoBom> PWoBoms, Set<PBom> PBoms) {
       this.idBom = idBom;
       this.PWorkCenter = PWorkCenter;
       this.SMaterial = SMaterial;
       this.PBomLabel = PBomLabel;
       this.PBom = PBom;
       this.qpu = qpu;
       this.orderBy = orderBy;
       this.PMrs = PMrs;
       this.PWoBoms = PWoBoms;
       this.PBoms = PBoms;
    }
   
     @Id 
    
    @Column(name="id_bom", unique=true, nullable=false)
    public Long getIdBom() {
        return this.idBom;
    }
    
    public void setIdBom(Long idBom) {
        this.idBom = idBom;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wc")
    public PWorkCenter getPWorkCenter() {
        return this.PWorkCenter;
    }
    
    public void setPWorkCenter(PWorkCenter PWorkCenter) {
        this.PWorkCenter = PWorkCenter;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mat")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_bom_label")
    public PBomLabel getPBomLabel() {
        return this.PBomLabel;
    }
    
    public void setPBomLabel(PBomLabel PBomLabel) {
        this.PBomLabel = PBomLabel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pid")
    public PBom getPBom() {
        return this.PBom;
    }
    
    public void setPBom(PBom PBom) {
        this.PBom = PBom;
    }
    
    @Column(name="qpu")
    public Long getQpu() {
        return this.qpu;
    }
    
    public void setQpu(Long qpu) {
        this.qpu = qpu;
    }
    
    @Column(name="order_by")
    public Long getOrderBy() {
        return this.orderBy;
    }
    
    public void setOrderBy(Long orderBy) {
        this.orderBy = orderBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PBom")
    public Set<PMr> getPMrs() {
        return this.PMrs;
    }
    
    public void setPMrs(Set<PMr> PMrs) {
        this.PMrs = PMrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PBom")
    public Set<PWoBom> getPWoBoms() {
        return this.PWoBoms;
    }
    
    public void setPWoBoms(Set<PWoBom> PWoBoms) {
        this.PWoBoms = PWoBoms;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PBom")
    public Set<PBom> getPBoms() {
        return this.PBoms;
    }
    
    public void setPBoms(Set<PBom> PBoms) {
        this.PBoms = PBoms;
    }




}


