package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PCheckTime generated by hbm2java
 */
@Entity
@Table(name="p_check_time"
    ,catalog="jms4"
)
public class PCheckTime  implements java.io.Serializable {


     private Long idCheckTime;
     private MMachine MMachine;
     private Long interval1;
     private String UTime;

    public PCheckTime() {
    }

	
    public PCheckTime(Long idCheckTime) {
        this.idCheckTime = idCheckTime;
    }
    public PCheckTime(Long idCheckTime, MMachine MMachine, Long interval1, String UTime) {
       this.idCheckTime = idCheckTime;
       this.MMachine = MMachine;
       this.interval1 = interval1;
       this.UTime = UTime;
    }
   
     @Id 
    
    @Column(name="id_check_time", unique=true, nullable=false)
    public Long getIdCheckTime() {
        return this.idCheckTime;
    }
    
    public void setIdCheckTime(Long idCheckTime) {
        this.idCheckTime = idCheckTime;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_machine")
    public MMachine getMMachine() {
        return this.MMachine;
    }
    
    public void setMMachine(MMachine MMachine) {
        this.MMachine = MMachine;
    }
    
    @Column(name="interval1")
    public Long getInterval1() {
        return this.interval1;
    }
    
    public void setInterval1(Long interval1) {
        this.interval1 = interval1;
    }
    
    @Column(name="u_time", length=20)
    public String getUTime() {
        return this.UTime;
    }
    
    public void setUTime(String UTime) {
        this.UTime = UTime;
    }




}


