package com.jms.domain.db;
// Generated 2015-5-30 22:39:13 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersistentLogin generated by hbm2java
 */
@Entity
@Table(name="persistent_login"
    ,catalog="jms"
)
public class PersistentLogin  implements java.io.Serializable {


     private String series;
     private Users users;
     private String token;
     private Date lastUesed;

    public PersistentLogin() {
    }

	
    public PersistentLogin(String series, String token, Date lastUesed) {
        this.series = series;
        this.token = token;
        this.lastUesed = lastUesed;
    }
    public PersistentLogin(String series, Users users, String token, Date lastUesed) {
       this.series = series;
       this.users = users;
       this.token = token;
       this.lastUesed = lastUesed;
    }
   
     @Id 
    
    @Column(name="SERIES", unique=true, nullable=false, length=64)
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USER")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="TOKEN", nullable=false, length=64)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UESED", nullable=false, length=19)
    public Date getLastUesed() {
        return this.lastUesed;
    }
    
    public void setLastUesed(Date lastUesed) {
        this.lastUesed = lastUesed;
    }




}


