package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PMr generated by hbm2java
 */
@Entity
@Table(name="p_mr"
    ,catalog="jms4"
)
public class PMr  implements java.io.Serializable {


     private Long idMr;
     private PBom PBom;
     private PCPp PCPp;
     private Long qty;
     private Date st;
     private Date ft;

    public PMr() {
    }

	
    public PMr(Long idMr) {
        this.idMr = idMr;
    }
    public PMr(Long idMr, PBom PBom, PCPp PCPp, Long qty, Date st, Date ft) {
       this.idMr = idMr;
       this.PBom = PBom;
       this.PCPp = PCPp;
       this.qty = qty;
       this.st = st;
       this.ft = ft;
    }
   
     @Id 
    
    @Column(name="id_mr", unique=true, nullable=false)
    public Long getIdMr() {
        return this.idMr;
    }
    
    public void setIdMr(Long idMr) {
        this.idMr = idMr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_bom")
    public PBom getPBom() {
        return this.PBom;
    }
    
    public void setPBom(PBom PBom) {
        this.PBom = PBom;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_c_pp")
    public PCPp getPCPp() {
        return this.PCPp;
    }
    
    public void setPCPp(PCPp PCPp) {
        this.PCPp = PCPp;
    }
    
    @Column(name="qty")
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="st", length=19)
    public Date getSt() {
        return this.st;
    }
    
    public void setSt(Date st) {
        this.st = st;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ft", length=19)
    public Date getFt() {
        return this.ft;
    }
    
    public void setFt(Date ft) {
        this.ft = ft;
    }




}


