package com.jms.domain.db;
// Generated 2015-5-30 22:39:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectDoc generated by hbm2java
 */
@Entity
@Table(name="project_doc"
    ,catalog="jms"
)
public class ProjectDoc  implements java.io.Serializable {


     private ProjectDocId id;
     private Documents documents;
     private Project project;
     private Integer publish;

    public ProjectDoc() {
    }

	
    public ProjectDoc(ProjectDocId id, Documents documents, Project project) {
        this.id = id;
        this.documents = documents;
        this.project = project;
    }
    public ProjectDoc(ProjectDocId id, Documents documents, Project project, Integer publish) {
       this.id = id;
       this.documents = documents;
       this.project = project;
       this.publish = publish;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idProject", column=@Column(name="ID_PROJECT", nullable=false) ), 
        @AttributeOverride(name="idDocument", column=@Column(name="ID_DOCUMENT", nullable=false) ) } )
    public ProjectDocId getId() {
        return this.id;
    }
    
    public void setId(ProjectDocId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOCUMENT", nullable=false, insertable=false, updatable=false)
    public Documents getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Documents documents) {
        this.documents = documents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROJECT", nullable=false, insertable=false, updatable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    
    @Column(name="PUBLISH")
    public Integer getPublish() {
        return this.publish;
    }
    
    public void setPublish(Integer publish) {
        this.publish = publish;
    }




}


