package com.jms.domain.db;
// Generated 2015-6-14 15:39:31 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
    ,catalog="jms"
)
public class Project  implements java.io.Serializable {


     private Integer idProject;
     private Company company;
     private Project project;
     private Users users;
     private SysDicD sysDicD;
     private String projectName;
     private String description;
     private String projectNumber;
     private Date planStartTime;
     private Date planEndTime;
     private Date startTime;
     private Date endTime;
     private Integer process;
     private int enabled;
     private Set<Issue> issues = new HashSet<Issue>(0);
     private Set<ProjectDoc> projectDocs = new HashSet<ProjectDoc>(0);
     private Set<ProjectParticipant> projectParticipants = new HashSet<ProjectParticipant>(0);
     private Set<Project> projects = new HashSet<Project>(0);
     private Set<Task> tasks = new HashSet<Task>(0);

    public Project() {
    }

	
    public Project(Company company, String projectName, int enabled) {
        this.company = company;
        this.projectName = projectName;
        this.enabled = enabled;
    }
    public Project(Company company, Project project, Users users, SysDicD sysDicD, String projectName, String description, String projectNumber, Date planStartTime, Date planEndTime, Date startTime, Date endTime, Integer process, int enabled, Set<Issue> issues, Set<ProjectDoc> projectDocs, Set<ProjectParticipant> projectParticipants, Set<Project> projects, Set<Task> tasks) {
       this.company = company;
       this.project = project;
       this.users = users;
       this.sysDicD = sysDicD;
       this.projectName = projectName;
       this.description = description;
       this.projectNumber = projectNumber;
       this.planStartTime = planStartTime;
       this.planEndTime = planEndTime;
       this.startTime = startTime;
       this.endTime = endTime;
       this.process = process;
       this.enabled = enabled;
       this.issues = issues;
       this.projectDocs = projectDocs;
       this.projectParticipants = projectParticipants;
       this.projects = projects;
       this.tasks = tasks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_PROJECT", unique=true, nullable=false)
    public Integer getIdProject() {
        return this.idProject;
    }
    
    public void setIdProject(Integer idProject) {
        this.idProject = idProject;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMPANY", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARENT")
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LEADER")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRIORITY")
    public SysDicD getSysDicD() {
        return this.sysDicD;
    }
    
    public void setSysDicD(SysDicD sysDicD) {
        this.sysDicD = sysDicD;
    }
    
    @Column(name="PROJECT_NAME", nullable=false, length=64)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="PROJECT_NUMBER", length=64)
    public String getProjectNumber() {
        return this.projectNumber;
    }
    
    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="PLAN_START_TIME", length=10)
    public Date getPlanStartTime() {
        return this.planStartTime;
    }
    
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="PLAN_END_TIME", length=10)
    public Date getPlanEndTime() {
        return this.planEndTime;
    }
    
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="START_TIME", length=10)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="END_TIME", length=10)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="PROCESS")
    public Integer getProcess() {
        return this.process;
    }
    
    public void setProcess(Integer process) {
        this.process = process;
    }
    
    @Column(name="ENABLED", nullable=false)
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="project")
    public Set<Issue> getIssues() {
        return this.issues;
    }
    
    public void setIssues(Set<Issue> issues) {
        this.issues = issues;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="project")
    public Set<ProjectDoc> getProjectDocs() {
        return this.projectDocs;
    }
    
    public void setProjectDocs(Set<ProjectDoc> projectDocs) {
        this.projectDocs = projectDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="project")
    public Set<ProjectParticipant> getProjectParticipants() {
        return this.projectParticipants;
    }
    
    public void setProjectParticipants(Set<ProjectParticipant> projectParticipants) {
        this.projectParticipants = projectParticipants;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="project")
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="project")
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }




}


