package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PRoutineDAtt generated by hbm2java
 */
@Entity
@Table(name="p_routine_d_att"
    ,catalog="jms5"
)
public class PRoutineDAtt  implements java.io.Serializable {


     private Long idRoutineDAtt;
     private PRoutineD PRoutineD;
     private PAttDraw PAttDraw;
     private Long orderBy;

    public PRoutineDAtt() {
    }

    public PRoutineDAtt(PRoutineD PRoutineD, PAttDraw PAttDraw, Long orderBy) {
       this.PRoutineD = PRoutineD;
       this.PAttDraw = PAttDraw;
       this.orderBy = orderBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_routine_d_att", unique=true, nullable=false)
    public Long getIdRoutineDAtt() {
        return this.idRoutineDAtt;
    }
    
    public void setIdRoutineDAtt(Long idRoutineDAtt) {
        this.idRoutineDAtt = idRoutineDAtt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_routine_d")
    public PRoutineD getPRoutineD() {
        return this.PRoutineD;
    }
    
    public void setPRoutineD(PRoutineD PRoutineD) {
        this.PRoutineD = PRoutineD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_att_draw")
    public PAttDraw getPAttDraw() {
        return this.PAttDraw;
    }
    
    public void setPAttDraw(PAttDraw PAttDraw) {
        this.PAttDraw = PAttDraw;
    }
    
    @Column(name="order_by")
    public Long getOrderBy() {
        return this.orderBy;
    }
    
    public void setOrderBy(Long orderBy) {
        this.orderBy = orderBy;
    }




}


