package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PRoutine generated by hbm2java
 */
@Entity
@Table(name="p_routine"
    ,catalog="jms4"
)
public class PRoutine  implements java.io.Serializable {


     private Long idRoutine;
     private Company company;
     private SMaterial SMaterial;
     private PDraw PDraw;
     private PLine PLine;
     private PStatusDic PStatusDic;
     private Set<PRoutineD> PRoutineDs = new HashSet<PRoutineD>(0);

    public PRoutine() {
    }

	
    public PRoutine(Long idRoutine) {
        this.idRoutine = idRoutine;
    }
    public PRoutine(Long idRoutine, Company company, SMaterial SMaterial, PDraw PDraw, PLine PLine, PStatusDic PStatusDic, Set<PRoutineD> PRoutineDs) {
       this.idRoutine = idRoutine;
       this.company = company;
       this.SMaterial = SMaterial;
       this.PDraw = PDraw;
       this.PLine = PLine;
       this.PStatusDic = PStatusDic;
       this.PRoutineDs = PRoutineDs;
    }
   
     @Id 
    
    @Column(name="id_routine", unique=true, nullable=false)
    public Long getIdRoutine() {
        return this.idRoutine;
    }
    
    public void setIdRoutine(Long idRoutine) {
        this.idRoutine = idRoutine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mat")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_draw")
    public PDraw getPDraw() {
        return this.PDraw;
    }
    
    public void setPDraw(PDraw PDraw) {
        this.PDraw = PDraw;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pline")
    public PLine getPLine() {
        return this.PLine;
    }
    
    public void setPLine(PLine PLine) {
        this.PLine = PLine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pstatus")
    public PStatusDic getPStatusDic() {
        return this.PStatusDic;
    }
    
    public void setPStatusDic(PStatusDic PStatusDic) {
        this.PStatusDic = PStatusDic;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PRoutine")
    public Set<PRoutineD> getPRoutineDs() {
        return this.PRoutineDs;
    }
    
    public void setPRoutineDs(Set<PRoutineD> PRoutineDs) {
        this.PRoutineDs = PRoutineDs;
    }




}


