package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PRoutineD generated by hbm2java
 */
@Entity
@Table(name="p_routine_d"
    ,catalog="jms4"
)
public class PRoutineD  implements java.io.Serializable {


     private Long idRoutineD;
     private PWorkCenter PWorkCenter;
     private Users users;
     private PAttDraw PAttDraw;
     private PRoutine PRoutine;
     private String routeNo;
     private String des;
     private Date stdWtLabor;
     private Date stdWtMachine;
     private Date stdWtSetup;
     private Set<QFaiInFinal> QFaiInFinals = new HashSet<QFaiInFinal>(0);
     private Set<PWoRoute> PWoRoutes = new HashSet<PWoRoute>(0);
     private Set<PRoutineDAtt> PRoutineDAtts = new HashSet<PRoutineDAtt>(0);
     private Set<QCheckList> QCheckLists = new HashSet<QCheckList>(0);
     private Set<PCPp> PCPps = new HashSet<PCPp>(0);

    public PRoutineD() {
    }

	
    public PRoutineD(Long idRoutineD) {
        this.idRoutineD = idRoutineD;
    }
    public PRoutineD(Long idRoutineD, PWorkCenter PWorkCenter, Users users, PAttDraw PAttDraw, PRoutine PRoutine, String routeNo, String des, Date stdWtLabor, Date stdWtMachine, Date stdWtSetup, Set<QFaiInFinal> QFaiInFinals, Set<PWoRoute> PWoRoutes, Set<PRoutineDAtt> PRoutineDAtts, Set<QCheckList> QCheckLists, Set<PCPp> PCPps) {
       this.idRoutineD = idRoutineD;
       this.PWorkCenter = PWorkCenter;
       this.users = users;
       this.PAttDraw = PAttDraw;
       this.PRoutine = PRoutine;
       this.routeNo = routeNo;
       this.des = des;
       this.stdWtLabor = stdWtLabor;
       this.stdWtMachine = stdWtMachine;
       this.stdWtSetup = stdWtSetup;
       this.QFaiInFinals = QFaiInFinals;
       this.PWoRoutes = PWoRoutes;
       this.PRoutineDAtts = PRoutineDAtts;
       this.QCheckLists = QCheckLists;
       this.PCPps = PCPps;
    }
   
     @Id 
    
    @Column(name="id_routine_d", unique=true, nullable=false)
    public Long getIdRoutineD() {
        return this.idRoutineD;
    }
    
    public void setIdRoutineD(Long idRoutineD) {
        this.idRoutineD = idRoutineD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wc")
    public PWorkCenter getPWorkCenter() {
        return this.PWorkCenter;
    }
    
    public void setPWorkCenter(PWorkCenter PWorkCenter) {
        this.PWorkCenter = PWorkCenter;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_by")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wi")
    public PAttDraw getPAttDraw() {
        return this.PAttDraw;
    }
    
    public void setPAttDraw(PAttDraw PAttDraw) {
        this.PAttDraw = PAttDraw;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_routine")
    public PRoutine getPRoutine() {
        return this.PRoutine;
    }
    
    public void setPRoutine(PRoutine PRoutine) {
        this.PRoutine = PRoutine;
    }
    
    @Column(name="route_no", length=20)
    public String getRouteNo() {
        return this.routeNo;
    }
    
    public void setRouteNo(String routeNo) {
        this.routeNo = routeNo;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="std_wt_labor", length=19)
    public Date getStdWtLabor() {
        return this.stdWtLabor;
    }
    
    public void setStdWtLabor(Date stdWtLabor) {
        this.stdWtLabor = stdWtLabor;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="std_wt_machine", length=19)
    public Date getStdWtMachine() {
        return this.stdWtMachine;
    }
    
    public void setStdWtMachine(Date stdWtMachine) {
        this.stdWtMachine = stdWtMachine;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="std_wt_setup", length=19)
    public Date getStdWtSetup() {
        return this.stdWtSetup;
    }
    
    public void setStdWtSetup(Date stdWtSetup) {
        this.stdWtSetup = stdWtSetup;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PRoutineD")
    public Set<QFaiInFinal> getQFaiInFinals() {
        return this.QFaiInFinals;
    }
    
    public void setQFaiInFinals(Set<QFaiInFinal> QFaiInFinals) {
        this.QFaiInFinals = QFaiInFinals;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PRoutineD")
    public Set<PWoRoute> getPWoRoutes() {
        return this.PWoRoutes;
    }
    
    public void setPWoRoutes(Set<PWoRoute> PWoRoutes) {
        this.PWoRoutes = PWoRoutes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PRoutineD")
    public Set<PRoutineDAtt> getPRoutineDAtts() {
        return this.PRoutineDAtts;
    }
    
    public void setPRoutineDAtts(Set<PRoutineDAtt> PRoutineDAtts) {
        this.PRoutineDAtts = PRoutineDAtts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PRoutineD")
    public Set<QCheckList> getQCheckLists() {
        return this.QCheckLists;
    }
    
    public void setQCheckLists(Set<QCheckList> QCheckLists) {
        this.QCheckLists = QCheckLists;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PRoutineD")
    public Set<PCPp> getPCPps() {
        return this.PCPps;
    }
    
    public void setPCPps(Set<PCPp> PCPps) {
        this.PCPps = PCPps;
    }




}


