package com.jms.domain.db;
// Generated 2015-7-3 12:07:40 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * Province generated by hbm2java
 */
@Audited
@Entity
@Table(name="province"
    ,catalog="jms"
)
public class Province  implements java.io.Serializable {


     private Long idProvince;
     private String province;
     private Set<City> cities = new HashSet<City>(0);

    public Province() {
    }

	
    public Province(Long idProvince) {
        this.idProvince = idProvince;
    }
    public Province(Long idProvince, String province, Set<City> cities) {
       this.idProvince = idProvince;
       this.province = province;
       this.cities = cities;
    }
   
     @Id 
    
    @Column(name="ID_PROVINCE", unique=true, nullable=false)
    public Long getIdProvince() {
        return this.idProvince;
    }
    
    public void setIdProvince(Long idProvince) {
        this.idProvince = idProvince;
    }
    
    @Column(name="PROVINCE", length=32)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="province")
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    }




}


