package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PShiftPlan generated by hbm2java
 */
@Entity
@Table(name="p_shift_plan"
)
public class PShiftPlan  implements java.io.Serializable {


     private Long idShiftPlan;
     private Company company;
     private PStatusDic PStatusDic;
     private Long shiftPlanNo;
     private String name;
     private Date validityTime;
     private Date st;
     private Date ft;
     private Set<PSPp> PSPps = new HashSet<PSPp>(0);
     private Set<PShiftPlanD> PShiftPlanDs = new HashSet<PShiftPlanD>(0);

    public PShiftPlan() {
    }

    public PShiftPlan(Company company, PStatusDic PStatusDic, Long shiftPlanNo, String name, Date validityTime, Date st, Date ft, Set<PSPp> PSPps, Set<PShiftPlanD> PShiftPlanDs) {
       this.company = company;
       this.PStatusDic = PStatusDic;
       this.shiftPlanNo = shiftPlanNo;
       this.name = name;
       this.validityTime = validityTime;
       this.st = st;
       this.ft = ft;
       this.PSPps = PSPps;
       this.PShiftPlanDs = PShiftPlanDs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_shift_plan", unique=true, nullable=false)
    public Long getIdShiftPlan() {
        return this.idShiftPlan;
    }
    
    public void setIdShiftPlan(Long idShiftPlan) {
        this.idShiftPlan = idShiftPlan;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pstatus")
    public PStatusDic getPStatusDic() {
        return this.PStatusDic;
    }
    
    public void setPStatusDic(PStatusDic PStatusDic) {
        this.PStatusDic = PStatusDic;
    }
    
    @Column(name="shift_plan_no")
    public Long getShiftPlanNo() {
        return this.shiftPlanNo;
    }
    
    public void setShiftPlanNo(Long shiftPlanNo) {
        this.shiftPlanNo = shiftPlanNo;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="validity_time", length=19)
    public Date getValidityTime() {
        return this.validityTime;
    }
    
    public void setValidityTime(Date validityTime) {
        this.validityTime = validityTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="st", length=10)
    public Date getSt() {
        return this.st;
    }
    
    public void setSt(Date st) {
        this.st = st;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ft", length=10)
    public Date getFt() {
        return this.ft;
    }
    
    public void setFt(Date ft) {
        this.ft = ft;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PShiftPlan")
    public Set<PSPp> getPSPps() {
        return this.PSPps;
    }
    
    public void setPSPps(Set<PSPp> PSPps) {
        this.PSPps = PSPps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PShiftPlan")
    public Set<PShiftPlanD> getPShiftPlanDs() {
        return this.PShiftPlanDs;
    }
    
    public void setPShiftPlanDs(Set<PShiftPlanD> PShiftPlanDs) {
        this.PShiftPlanDs = PShiftPlanDs;
    }




}


