package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PShiftPlanD generated by hbm2java
 */
@Entity
@Table(name="p_shift_plan_d"
    ,catalog="jms5"
)
public class PShiftPlanD  implements java.io.Serializable {


     private Long idShiftD;
     private PShiftPlan PShiftPlan;
     private String shift;
     private String des;
     private String st;
     private String ft;
     private Set<PCPp> PCPps = new HashSet<PCPp>(0);

    public PShiftPlanD() {
    }

    public PShiftPlanD(PShiftPlan PShiftPlan, String shift, String des, String st, String ft, Set<PCPp> PCPps) {
       this.PShiftPlan = PShiftPlan;
       this.shift = shift;
       this.des = des;
       this.st = st;
       this.ft = ft;
       this.PCPps = PCPps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_shift_d", unique=true, nullable=false)
    public Long getIdShiftD() {
        return this.idShiftD;
    }
    
    public void setIdShiftD(Long idShiftD) {
        this.idShiftD = idShiftD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_shift_plan")
    public PShiftPlan getPShiftPlan() {
        return this.PShiftPlan;
    }
    
    public void setPShiftPlan(PShiftPlan PShiftPlan) {
        this.PShiftPlan = PShiftPlan;
    }
    
    @Column(name="shift", length=20)
    public String getShift() {
        return this.shift;
    }
    
    public void setShift(String shift) {
        this.shift = shift;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }

    @Column(name="st", length=64)
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }
    @Column(name="ft", length=64)
    public String getFt() {
        return this.ft;
    }
    
    public void setFt(String ft) {
        this.ft = ft;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PShiftPlanD")
    public Set<PCPp> getPCPps() {
        return this.PCPps;
    }
    
    public void setPCPps(Set<PCPp> PCPps) {
        this.PCPps = PCPps;
    }




}


