package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PStatusDic generated by hbm2java
 */
@Entity
@Table(name="p_status_dic"
    ,catalog="jms5"
)
public class PStatusDic  implements java.io.Serializable {


     private Long idPstatus;
     private String name;
     private String des;
     private String source;
     private Set<PWip> PWips = new HashSet<PWip>(0);
     private Set<PBomLabel> PBomLabels = new HashSet<PBomLabel>(0);
     private Set<PCheckPlan> PCheckPlans = new HashSet<PCheckPlan>(0);
     private Set<PUnplannedStops> PUnplannedStopses = new HashSet<PUnplannedStops>(0);
     private Set<PLine> PLines = new HashSet<PLine>(0);
     private Set<PMr> PMrs = new HashSet<PMr>(0);
     private Set<PSPp> PSPps = new HashSet<PSPp>(0);
     private Set<PStopsPlan> PStopsPlans = new HashSet<PStopsPlan>(0);
     private Set<PRoutine> PRoutines = new HashSet<PRoutine>(0);
     private Set<PWo> PWos = new HashSet<PWo>(0);
     private Set<PShiftPlan> PShiftPlans = new HashSet<PShiftPlan>(0);

    public PStatusDic() {
    }

    public PStatusDic(String name, String des, String source, Set<PWip> PWips, Set<PBomLabel> PBomLabels, Set<PCheckPlan> PCheckPlans, Set<PUnplannedStops> PUnplannedStopses, Set<PLine> PLines, Set<PMr> PMrs, Set<PSPp> PSPps, Set<PStopsPlan> PStopsPlans, Set<PRoutine> PRoutines, Set<PWo> PWos, Set<PShiftPlan> PShiftPlans) {
       this.name = name;
       this.des = des;
       this.source = source;
       this.PWips = PWips;
       this.PBomLabels = PBomLabels;
       this.PCheckPlans = PCheckPlans;
       this.PUnplannedStopses = PUnplannedStopses;
       this.PLines = PLines;
       this.PMrs = PMrs;
       this.PSPps = PSPps;
       this.PStopsPlans = PStopsPlans;
       this.PRoutines = PRoutines;
       this.PWos = PWos;
       this.PShiftPlans = PShiftPlans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_pstatus", unique=true, nullable=false)
    public Long getIdPstatus() {
        return this.idPstatus;
    }
    
    public void setIdPstatus(Long idPstatus) {
        this.idPstatus = idPstatus;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="source", length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PWip> getPWips() {
        return this.PWips;
    }
    
    public void setPWips(Set<PWip> PWips) {
        this.PWips = PWips;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PBomLabel> getPBomLabels() {
        return this.PBomLabels;
    }
    
    public void setPBomLabels(Set<PBomLabel> PBomLabels) {
        this.PBomLabels = PBomLabels;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PCheckPlan> getPCheckPlans() {
        return this.PCheckPlans;
    }
    
    public void setPCheckPlans(Set<PCheckPlan> PCheckPlans) {
        this.PCheckPlans = PCheckPlans;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PUnplannedStops> getPUnplannedStopses() {
        return this.PUnplannedStopses;
    }
    
    public void setPUnplannedStopses(Set<PUnplannedStops> PUnplannedStopses) {
        this.PUnplannedStopses = PUnplannedStopses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PLine> getPLines() {
        return this.PLines;
    }
    
    public void setPLines(Set<PLine> PLines) {
        this.PLines = PLines;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PMr> getPMrs() {
        return this.PMrs;
    }
    
    public void setPMrs(Set<PMr> PMrs) {
        this.PMrs = PMrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PSPp> getPSPps() {
        return this.PSPps;
    }
    
    public void setPSPps(Set<PSPp> PSPps) {
        this.PSPps = PSPps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PStopsPlan> getPStopsPlans() {
        return this.PStopsPlans;
    }
    
    public void setPStopsPlans(Set<PStopsPlan> PStopsPlans) {
        this.PStopsPlans = PStopsPlans;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PRoutine> getPRoutines() {
        return this.PRoutines;
    }
    
    public void setPRoutines(Set<PRoutine> PRoutines) {
        this.PRoutines = PRoutines;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PWo> getPWos() {
        return this.PWos;
    }
    
    public void setPWos(Set<PWo> PWos) {
        this.PWos = PWos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStatusDic")
    public Set<PShiftPlan> getPShiftPlans() {
        return this.PShiftPlans;
    }
    
    public void setPShiftPlans(Set<PShiftPlan> PShiftPlans) {
        this.PShiftPlans = PShiftPlans;
    }




}


