package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PStopsPlan generated by hbm2java
 */
@Entity
@Table(name="p_stops_plan"
    ,catalog="jms5"
)
public class PStopsPlan  implements java.io.Serializable {


     private Long idStopsPlan;
     private PSubCode PSubCode;
     private Company company;
     private MMachine MMachine;
     private PStatusDic PStatusDic;
     private Long stopsPlanNo;
     private Date planSt;
     private Date planFt;
     private Date actSt;
     private Date actFt;
     private Set<PActStops> PActStopses = new HashSet<PActStops>(0);

    public PStopsPlan() {
    }

    public PStopsPlan(PSubCode PSubCode, Company company, MMachine MMachine, PStatusDic PStatusDic, Long stopsPlanNo, Date planSt, Date planFt, Date actSt, Date actFt, Set<PActStops> PActStopses) {
       this.PSubCode = PSubCode;
       this.company = company;
       this.MMachine = MMachine;
       this.PStatusDic = PStatusDic;
       this.stopsPlanNo = stopsPlanNo;
       this.planSt = planSt;
       this.planFt = planFt;
       this.actSt = actSt;
       this.actFt = actFt;
       this.PActStopses = PActStopses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_stops_plan", unique=true, nullable=false)
    public Long getIdStopsPlan() {
        return this.idStopsPlan;
    }
    
    public void setIdStopsPlan(Long idStopsPlan) {
        this.idStopsPlan = idStopsPlan;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_code")
    public PSubCode getPSubCode() {
        return this.PSubCode;
    }
    
    public void setPSubCode(PSubCode PSubCode) {
        this.PSubCode = PSubCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_machine")
    public MMachine getMMachine() {
        return this.MMachine;
    }
    
    public void setMMachine(MMachine MMachine) {
        this.MMachine = MMachine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pstatus")
    public PStatusDic getPStatusDic() {
        return this.PStatusDic;
    }
    
    public void setPStatusDic(PStatusDic PStatusDic) {
        this.PStatusDic = PStatusDic;
    }
    
    @Column(name="stops_plan_no")
    public Long getStopsPlanNo() {
        return this.stopsPlanNo;
    }
    
    public void setStopsPlanNo(Long stopsPlanNo) {
        this.stopsPlanNo = stopsPlanNo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="plan_st", length=19)
    public Date getPlanSt() {
        return this.planSt;
    }
    
    public void setPlanSt(Date planSt) {
        this.planSt = planSt;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="plan_ft", length=19)
    public Date getPlanFt() {
        return this.planFt;
    }
    
    public void setPlanFt(Date planFt) {
        this.planFt = planFt;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="act_st", length=19)
    public Date getActSt() {
        return this.actSt;
    }
    
    public void setActSt(Date actSt) {
        this.actSt = actSt;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="act_ft", length=19)
    public Date getActFt() {
        return this.actFt;
    }
    
    public void setActFt(Date actFt) {
        this.actFt = actFt;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PStopsPlan")
    public Set<PActStops> getPActStopses() {
        return this.PActStopses;
    }
    
    public void setPActStopses(Set<PActStops> PActStopses) {
        this.PActStopses = PActStopses;
    }




}


