package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PUnplannedStops generated by hbm2java
 */
@Entity
@Table(name="p_unplanned_stops"
    ,catalog="jms4"
)
public class PUnplannedStops  implements java.io.Serializable {


     private Long idUnplannedStops;
     private PSubCode PSubCode;
     private PStopsCode PStopsCode;
     private Long unplannedStopsNo;
     private Date unplannedFt;
     private Date unplannedSt;
     private String opDes;
     private String reason;
     private String reaction;

    public PUnplannedStops() {
    }

	
    public PUnplannedStops(Long idUnplannedStops) {
        this.idUnplannedStops = idUnplannedStops;
    }
    public PUnplannedStops(Long idUnplannedStops, PSubCode PSubCode, PStopsCode PStopsCode, Long unplannedStopsNo, Date unplannedFt, Date unplannedSt, String opDes, String reason, String reaction) {
       this.idUnplannedStops = idUnplannedStops;
       this.PSubCode = PSubCode;
       this.PStopsCode = PStopsCode;
       this.unplannedStopsNo = unplannedStopsNo;
       this.unplannedFt = unplannedFt;
       this.unplannedSt = unplannedSt;
       this.opDes = opDes;
       this.reason = reason;
       this.reaction = reaction;
    }
   
     @Id 
    
    @Column(name="id_unplanned_stops", unique=true, nullable=false)
    public Long getIdUnplannedStops() {
        return this.idUnplannedStops;
    }
    
    public void setIdUnplannedStops(Long idUnplannedStops) {
        this.idUnplannedStops = idUnplannedStops;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_code")
    public PSubCode getPSubCode() {
        return this.PSubCode;
    }
    
    public void setPSubCode(PSubCode PSubCode) {
        this.PSubCode = PSubCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_stops_code")
    public PStopsCode getPStopsCode() {
        return this.PStopsCode;
    }
    
    public void setPStopsCode(PStopsCode PStopsCode) {
        this.PStopsCode = PStopsCode;
    }
    
    @Column(name="unplanned_stops_no")
    public Long getUnplannedStopsNo() {
        return this.unplannedStopsNo;
    }
    
    public void setUnplannedStopsNo(Long unplannedStopsNo) {
        this.unplannedStopsNo = unplannedStopsNo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="unplanned_ft", length=19)
    public Date getUnplannedFt() {
        return this.unplannedFt;
    }
    
    public void setUnplannedFt(Date unplannedFt) {
        this.unplannedFt = unplannedFt;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="unplanned_st", length=10)
    public Date getUnplannedSt() {
        return this.unplannedSt;
    }
    
    public void setUnplannedSt(Date unplannedSt) {
        this.unplannedSt = unplannedSt;
    }
    
    @Column(name="op_des", length=128)
    public String getOpDes() {
        return this.opDes;
    }
    
    public void setOpDes(String opDes) {
        this.opDes = opDes;
    }
    
    @Column(name="reason", length=1024)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    
    @Column(name="reaction", length=1024)
    public String getReaction() {
        return this.reaction;
    }
    
    public void setReaction(String reaction) {
        this.reaction = reaction;
    }




}


