package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PVote generated by hbm2java
 */
@Entity
@Table(name="p_vote"
    ,catalog="jms3"
)
public class PVote  implements java.io.Serializable {


     private PVoteId id;
     private PPollItems PPollItems;
     private PPollParticipant PPollParticipant;
     private SysDicD sysDicD;

    public PVote() {
    }

	
    public PVote(PVoteId id, PPollItems PPollItems, PPollParticipant PPollParticipant) {
        this.id = id;
        this.PPollItems = PPollItems;
        this.PPollParticipant = PPollParticipant;
    }
    public PVote(PVoteId id, PPollItems PPollItems, PPollParticipant PPollParticipant, SysDicD sysDicD) {
       this.id = id;
       this.PPollItems = PPollItems;
       this.PPollParticipant = PPollParticipant;
       this.sysDicD = sysDicD;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="idItem", column=@Column(name="id_item", nullable=false) ) } )
    public PVoteId getId() {
        return this.id;
    }
    
    public void setId(PVoteId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_item", nullable=false, insertable=false, updatable=false)
    public PPollItems getPPollItems() {
        return this.PPollItems;
    }
    
    public void setPPollItems(PPollItems PPollItems) {
        this.PPollItems = PPollItems;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public PPollParticipant getPPollParticipant() {
        return this.PPollParticipant;
    }
    
    public void setPPollParticipant(PPollParticipant PPollParticipant) {
        this.PPollParticipant = PPollParticipant;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="degree")
    public SysDicD getSysDicD() {
        return this.sysDicD;
    }
    
    public void setSysDicD(SysDicD sysDicD) {
        this.sysDicD = sysDicD;
    }




}


