package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PWorkCenter generated by hbm2java
 */
@Entity
@Table(name="p_work_center"
    ,catalog="jms5"
)
public class PWorkCenter  implements java.io.Serializable {


     private Long idWc;
     private Company company;
     private Users users;
     private String workCenter;
     private Date creationTime;
     private Set<PBom> PBoms = new HashSet<PBom>(0);
     private Set<MMachine> MMachines = new HashSet<MMachine>(0);
     private Set<PRoutineD> PRoutineDs = new HashSet<PRoutineD>(0);

    public PWorkCenter() {
    }

    public PWorkCenter(Company company, Users users, String workCenter, Date creationTime, Set<PBom> PBoms, Set<MMachine> MMachines, Set<PRoutineD> PRoutineDs) {
       this.company = company;
       this.users = users;
       this.workCenter = workCenter;
       this.creationTime = creationTime;
       this.PBoms = PBoms;
       this.MMachines = MMachines;
       this.PRoutineDs = PRoutineDs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_wc", unique=true, nullable=false)
    public Long getIdWc() {
        return this.idWc;
    }
    
    public void setIdWc(Long idWc) {
        this.idWc = idWc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="work_center", length=20)
    public String getWorkCenter() {
        return this.workCenter;
    }
    
    public void setWorkCenter(String workCenter) {
        this.workCenter = workCenter;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_time", length=19)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PWorkCenter")
    public Set<PBom> getPBoms() {
        return this.PBoms;
    }
    
    public void setPBoms(Set<PBom> PBoms) {
        this.PBoms = PBoms;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PWorkCenter")
    public Set<MMachine> getMMachines() {
        return this.MMachines;
    }
    
    public void setMMachines(Set<MMachine> MMachines) {
        this.MMachines = MMachines;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="PWorkCenter")
    public Set<PRoutineD> getPRoutineDs() {
        return this.PRoutineDs;
    }
    
    public void setPRoutineDs(Set<PRoutineD> PRoutineDs) {
        this.PRoutineDs = PRoutineDs;
    }




}


