package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PWoRoute generated by hbm2java
 */
@Entity
@Table(name="p_wo_route"
    ,catalog="jms4"
)
public class PWoRoute  implements java.io.Serializable {


     private Long idWoRoute;
     private PRoutineD PRoutineD;
     private PWo PWo;

    public PWoRoute() {
    }

	
    public PWoRoute(Long idWoRoute) {
        this.idWoRoute = idWoRoute;
    }
    public PWoRoute(Long idWoRoute, PRoutineD PRoutineD, PWo PWo) {
       this.idWoRoute = idWoRoute;
       this.PRoutineD = PRoutineD;
       this.PWo = PWo;
    }
   
     @Id 
    
    @Column(name="id_wo_route", unique=true, nullable=false)
    public Long getIdWoRoute() {
        return this.idWoRoute;
    }
    
    public void setIdWoRoute(Long idWoRoute) {
        this.idWoRoute = idWoRoute;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_routine_d")
    public PRoutineD getPRoutineD() {
        return this.PRoutineD;
    }
    
    public void setPRoutineD(PRoutineD PRoutineD) {
        this.PRoutineD = PRoutineD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wo")
    public PWo getPWo() {
        return this.PWo;
    }
    
    public void setPWo(PWo PWo) {
        this.PWo = PWo;
    }




}


