package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QAtt generated by hbm2java
 */
@Entity
@Table(name="q_att"
    ,catalog="jms4"
)
public class QAtt  implements java.io.Serializable {


     private Long idQAtt;
     private Company company;
     private QAttType QAttType;
     private QDimensionReport QDimensionReport;
     private Users users;
     private String orgFilename;
     private String filename;

    public QAtt() {
    }

	
    public QAtt(Long idQAtt) {
        this.idQAtt = idQAtt;
    }
    public QAtt(Long idQAtt, Company company, QAttType QAttType, QDimensionReport QDimensionReport, Users users, String orgFilename, String filename) {
       this.idQAtt = idQAtt;
       this.company = company;
       this.QAttType = QAttType;
       this.QDimensionReport = QDimensionReport;
       this.users = users;
       this.orgFilename = orgFilename;
       this.filename = filename;
    }
   
     @Id 
    
    @Column(name="id_q_att", unique=true, nullable=false)
    public Long getIdQAtt() {
        return this.idQAtt;
    }
    
    public void setIdQAtt(Long idQAtt) {
        this.idQAtt = idQAtt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_att_type")
    public QAttType getQAttType() {
        return this.QAttType;
    }
    
    public void setQAttType(QAttType QAttType) {
        this.QAttType = QAttType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_report")
    public QDimensionReport getQDimensionReport() {
        return this.QDimensionReport;
    }
    
    public void setQDimensionReport(QDimensionReport QDimensionReport) {
        this.QDimensionReport = QDimensionReport;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="upload_by")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="org_filename", length=256)
    public String getOrgFilename() {
        return this.orgFilename;
    }
    
    public void setOrgFilename(String orgFilename) {
        this.orgFilename = orgFilename;
    }
    
    @Column(name="filename", length=256)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }




}


