package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QCheckList generated by hbm2java
 */
@Entity
@Table(name="q_check_list"
)
public class QCheckList  implements java.io.Serializable {


     private Long idCheckList;
     private SMaterial SMaterial;
     private Company company;
     private PRoutineD PRoutineD;
     private QTester QTester;
     private QItemType QItemType;
     private String item;
     private String testMethod;
     private String specification;
     private Long frequency;
     private Set<QUnRollerD> QUnRollerDs = new HashSet<QUnRollerD>(0);
     private Set<QReportRecord> QReportRecords = new HashSet<QReportRecord>(0);
     private Set<QFaiPulleyD> QFaiPulleyDs = new HashSet<QFaiPulleyD>(0);
     private Set<QRollerFinalD> QRollerFinalDs = new HashSet<QRollerFinalD>(0);

    public QCheckList() {
    }

    public QCheckList(SMaterial SMaterial, Company company, PRoutineD PRoutineD, QTester QTester, QItemType QItemType, String item, String testMethod, String specification, Long frequency, Set<QUnRollerD> QUnRollerDs, Set<QReportRecord> QReportRecords, Set<QFaiPulleyD> QFaiPulleyDs, Set<QRollerFinalD> QRollerFinalDs) {
       this.SMaterial = SMaterial;
       this.company = company;
       this.PRoutineD = PRoutineD;
       this.QTester = QTester;
       this.QItemType = QItemType;
       this.item = item;
       this.testMethod = testMethod;
       this.specification = specification;
       this.frequency = frequency;
       this.QUnRollerDs = QUnRollerDs;
       this.QReportRecords = QReportRecords;
       this.QFaiPulleyDs = QFaiPulleyDs;
       this.QRollerFinalDs = QRollerFinalDs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_check_list", unique=true, nullable=false)
    public Long getIdCheckList() {
        return this.idCheckList;
    }
    
    public void setIdCheckList(Long idCheckList) {
        this.idCheckList = idCheckList;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="guage")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_routine_d")
    public PRoutineD getPRoutineD() {
        return this.PRoutineD;
    }
    
    public void setPRoutineD(PRoutineD PRoutineD) {
        this.PRoutineD = PRoutineD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tester")
    public QTester getQTester() {
        return this.QTester;
    }
    
    public void setQTester(QTester QTester) {
        this.QTester = QTester;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_item_type")
    public QItemType getQItemType() {
        return this.QItemType;
    }
    
    public void setQItemType(QItemType QItemType) {
        this.QItemType = QItemType;
    }
    
    @Column(name="item", length=100)
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    
    @Column(name="test_method", length=100)
    public String getTestMethod() {
        return this.testMethod;
    }
    
    public void setTestMethod(String testMethod) {
        this.testMethod = testMethod;
    }
    
    @Column(name="specification", length=100)
    public String getSpecification() {
        return this.specification;
    }
    
    public void setSpecification(String specification) {
        this.specification = specification;
    }
    
    @Column(name="frequency")
    public Long getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(Long frequency) {
        this.frequency = frequency;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QCheckList")
    public Set<QUnRollerD> getQUnRollerDs() {
        return this.QUnRollerDs;
    }
    
    public void setQUnRollerDs(Set<QUnRollerD> QUnRollerDs) {
        this.QUnRollerDs = QUnRollerDs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QCheckList")
    public Set<QReportRecord> getQReportRecords() {
        return this.QReportRecords;
    }
    
    public void setQReportRecords(Set<QReportRecord> QReportRecords) {
        this.QReportRecords = QReportRecords;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QCheckList")
    public Set<QFaiPulleyD> getQFaiPulleyDs() {
        return this.QFaiPulleyDs;
    }
    
    public void setQFaiPulleyDs(Set<QFaiPulleyD> QFaiPulleyDs) {
        this.QFaiPulleyDs = QFaiPulleyDs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QCheckList")
    public Set<QRollerFinalD> getQRollerFinalDs() {
        return this.QRollerFinalDs;
    }
    
    public void setQRollerFinalDs(Set<QRollerFinalD> QRollerFinalDs) {
        this.QRollerFinalDs = QRollerFinalDs;
    }




}


