package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QConclusionDic generated by hbm2java
 */
@Entity
@Table(name="q_conclusion_dic"
)
public class QConclusionDic  implements java.io.Serializable {


     private Long idConclusion;
     private String des;
     private String source;
     private Set<QFaiInFinal> QFaiInFinals = new HashSet<QFaiInFinal>(0);
     private Set<QNcp> QNcps = new HashSet<QNcp>(0);
     private Set<QDimensionReport> QDimensionReports = new HashSet<QDimensionReport>(0);
     private Set<QFaiPulleyD> QFaiPulleyDsForInspConclusion = new HashSet<QFaiPulleyD>(0);
     private Set<QFaiPulleyD> QFaiPulleyDsForOpConclusion = new HashSet<QFaiPulleyD>(0);

    public QConclusionDic() {
    }

    public QConclusionDic(String des, String source, Set<QFaiInFinal> QFaiInFinals, Set<QNcp> QNcps, Set<QDimensionReport> QDimensionReports, Set<QFaiPulleyD> QFaiPulleyDsForInspConclusion, Set<QFaiPulleyD> QFaiPulleyDsForOpConclusion) {
       this.des = des;
       this.source = source;
       this.QFaiInFinals = QFaiInFinals;
       this.QNcps = QNcps;
       this.QDimensionReports = QDimensionReports;
       this.QFaiPulleyDsForInspConclusion = QFaiPulleyDsForInspConclusion;
       this.QFaiPulleyDsForOpConclusion = QFaiPulleyDsForOpConclusion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_conclusion", unique=true, nullable=false)
    public Long getIdConclusion() {
        return this.idConclusion;
    }
    
    public void setIdConclusion(Long idConclusion) {
        this.idConclusion = idConclusion;
    }
    
    @Column(name="des", length=20)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="source", length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QConclusionDic")
    public Set<QFaiInFinal> getQFaiInFinals() {
        return this.QFaiInFinals;
    }
    
    public void setQFaiInFinals(Set<QFaiInFinal> QFaiInFinals) {
        this.QFaiInFinals = QFaiInFinals;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QConclusionDic")
    public Set<QNcp> getQNcps() {
        return this.QNcps;
    }
    
    public void setQNcps(Set<QNcp> QNcps) {
        this.QNcps = QNcps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QConclusionDic")
    public Set<QDimensionReport> getQDimensionReports() {
        return this.QDimensionReports;
    }
    
    public void setQDimensionReports(Set<QDimensionReport> QDimensionReports) {
        this.QDimensionReports = QDimensionReports;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QConclusionDicByInspConclusion")
    public Set<QFaiPulleyD> getQFaiPulleyDsForInspConclusion() {
        return this.QFaiPulleyDsForInspConclusion;
    }
    
    public void setQFaiPulleyDsForInspConclusion(Set<QFaiPulleyD> QFaiPulleyDsForInspConclusion) {
        this.QFaiPulleyDsForInspConclusion = QFaiPulleyDsForInspConclusion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QConclusionDicByOpConclusion")
    public Set<QFaiPulleyD> getQFaiPulleyDsForOpConclusion() {
        return this.QFaiPulleyDsForOpConclusion;
    }
    
    public void setQFaiPulleyDsForOpConclusion(Set<QFaiPulleyD> QFaiPulleyDsForOpConclusion) {
        this.QFaiPulleyDsForOpConclusion = QFaiPulleyDsForOpConclusion;
    }




}


