package com.jms.domain.db;
// Generated 2016-8-23 14:57:20 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QDeviation generated by hbm2java
 */
@Entity
@Table(name="q_deviation"
    ,catalog="jms5"
)
public class QDeviation  implements java.io.Serializable {


     private Long idDeviation;
     private String deviationNo;
     private Long idMaterial;
     private Long idRoutineD;
     private Long idCompanyCo;
     private String issuer;
     private Date date;
     private String scopePeriodMaxqty;
     private String reason;
     private String mfgRemark;
     private String mfgSign;
     private String aeRemark;
     private String aeSign;
     private String qeRemark;
     private String qeSign;
     private String otherFuction;
     private String ofSign;
     private Long idDept;
     private Set<QNoProcess> QNoProcesses = new HashSet<QNoProcess>(0);

    public QDeviation() {
    }

    public QDeviation(String deviationNo, Long idMaterial, Long idRoutineD, Long idCompanyCo, String issuer, Date date, String scopePeriodMaxqty, String reason, String mfgRemark, String mfgSign, String aeRemark, String aeSign, String qeRemark, String qeSign, String otherFuction, String ofSign, Long idDept, Set<QNoProcess> QNoProcesses) {
       this.deviationNo = deviationNo;
       this.idMaterial = idMaterial;
       this.idRoutineD = idRoutineD;
       this.idCompanyCo = idCompanyCo;
       this.issuer = issuer;
       this.date = date;
       this.scopePeriodMaxqty = scopePeriodMaxqty;
       this.reason = reason;
       this.mfgRemark = mfgRemark;
       this.mfgSign = mfgSign;
       this.aeRemark = aeRemark;
       this.aeSign = aeSign;
       this.qeRemark = qeRemark;
       this.qeSign = qeSign;
       this.otherFuction = otherFuction;
       this.ofSign = ofSign;
       this.idDept = idDept;
       this.QNoProcesses = QNoProcesses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_deviation", unique=true, nullable=false)
    public Long getIdDeviation() {
        return this.idDeviation;
    }
    
    public void setIdDeviation(Long idDeviation) {
        this.idDeviation = idDeviation;
    }
    
    @Column(name="deviation_no", length=20)
    public String getDeviationNo() {
        return this.deviationNo;
    }
    
    public void setDeviationNo(String deviationNo) {
        this.deviationNo = deviationNo;
    }
    
    @Column(name="id_material")
    public Long getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Long idMaterial) {
        this.idMaterial = idMaterial;
    }
    
    @Column(name="id_routine_d")
    public Long getIdRoutineD() {
        return this.idRoutineD;
    }
    
    public void setIdRoutineD(Long idRoutineD) {
        this.idRoutineD = idRoutineD;
    }
    
    @Column(name="id_company_co")
    public Long getIdCompanyCo() {
        return this.idCompanyCo;
    }
    
    public void setIdCompanyCo(Long idCompanyCo) {
        this.idCompanyCo = idCompanyCo;
    }
    
    @Column(name="issuer", length=32)
    public String getIssuer() {
        return this.issuer;
    }
    
    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="scope_period_maxqty", length=128)
    public String getScopePeriodMaxqty() {
        return this.scopePeriodMaxqty;
    }
    
    public void setScopePeriodMaxqty(String scopePeriodMaxqty) {
        this.scopePeriodMaxqty = scopePeriodMaxqty;
    }
    
    @Column(name="reason", length=1024)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    
    @Column(name="mfg_remark", length=20)
    public String getMfgRemark() {
        return this.mfgRemark;
    }
    
    public void setMfgRemark(String mfgRemark) {
        this.mfgRemark = mfgRemark;
    }
    
    @Column(name="mfg_sign", length=20)
    public String getMfgSign() {
        return this.mfgSign;
    }
    
    public void setMfgSign(String mfgSign) {
        this.mfgSign = mfgSign;
    }
    
    @Column(name="ae_remark", length=20)
    public String getAeRemark() {
        return this.aeRemark;
    }
    
    public void setAeRemark(String aeRemark) {
        this.aeRemark = aeRemark;
    }
    
    @Column(name="ae_sign", length=20)
    public String getAeSign() {
        return this.aeSign;
    }
    
    public void setAeSign(String aeSign) {
        this.aeSign = aeSign;
    }
    
    @Column(name="qe_remark", length=18)
    public String getQeRemark() {
        return this.qeRemark;
    }
    
    public void setQeRemark(String qeRemark) {
        this.qeRemark = qeRemark;
    }
    
    @Column(name="qe_sign", length=20)
    public String getQeSign() {
        return this.qeSign;
    }
    
    public void setQeSign(String qeSign) {
        this.qeSign = qeSign;
    }
    
    @Column(name="other_fuction", length=20)
    public String getOtherFuction() {
        return this.otherFuction;
    }
    
    public void setOtherFuction(String otherFuction) {
        this.otherFuction = otherFuction;
    }
    
    @Column(name="of_sign", length=20)
    public String getOfSign() {
        return this.ofSign;
    }
    
    public void setOfSign(String ofSign) {
        this.ofSign = ofSign;
    }
    
    @Column(name="id_dept")
    public Long getIdDept() {
        return this.idDept;
    }
    
    public void setIdDept(Long idDept) {
        this.idDept = idDept;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QDeviation")
    public Set<QNoProcess> getQNoProcesses() {
        return this.QNoProcesses;
    }
    
    public void setQNoProcesses(Set<QNoProcess> QNoProcesses) {
        this.QNoProcesses = QNoProcesses;
    }




}


