package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QDisposalType generated by hbm2java
 */
@Entity
@Table(name="q_disposal_type"
    ,catalog="jms4"
)
public class QDisposalType  implements java.io.Serializable {


     private Long idDisposalType;
     private Company company;
     private QStatusDic QStatusDic;
     private String des;
     private Set<QNcp> QNcps = new HashSet<QNcp>(0);

    public QDisposalType() {
    }

	
    public QDisposalType(Long idDisposalType) {
        this.idDisposalType = idDisposalType;
    }
    public QDisposalType(Long idDisposalType, Company company, QStatusDic QStatusDic, String des, Set<QNcp> QNcps) {
       this.idDisposalType = idDisposalType;
       this.company = company;
       this.QStatusDic = QStatusDic;
       this.des = des;
       this.QNcps = QNcps;
    }
   
     @Id 
    
    @Column(name="id_disposal_type", unique=true, nullable=false)
    public Long getIdDisposalType() {
        return this.idDisposalType;
    }
    
    public void setIdDisposalType(Long idDisposalType) {
        this.idDisposalType = idDisposalType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_qstatus")
    public QStatusDic getQStatusDic() {
        return this.QStatusDic;
    }
    
    public void setQStatusDic(QStatusDic QStatusDic) {
        this.QStatusDic = QStatusDic;
    }
    
    @Column(name="des", length=20)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QDisposalType")
    public Set<QNcp> getQNcps() {
        return this.QNcps;
    }
    
    public void setQNcps(Set<QNcp> QNcps) {
        this.QNcps = QNcps;
    }




}


