package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QFaiInFinal generated by hbm2java
 */
@Entity
@Table(name="q_fai_in_final"
)
public class QFaiInFinal  implements java.io.Serializable {


     private Long idFaiInFinal;
     private QReportType QReportType;
     private Company company;
     private MMachine MMachine;
     private PRoutineD PRoutineD;
     private Users usersByInspector;
     private Users usersByOp;
     private PWo PWo;
     private QConclusionDic QConclusionDic;
     private Users usersByShiftLeader;
     private String projectName;
     private String lotNo;
     private Date opDate;
     private String type;
     private Date slDate;
     private Date inspDate;
     private String falInFinalNo;
     private Set<QUnRollerD> QUnRollerDs = new HashSet<QUnRollerD>(0);
     private Set<QFaiPulleyD> QFaiPulleyDs = new HashSet<QFaiPulleyD>(0);
     private Set<QRollerFinalD> QRollerFinalDs = new HashSet<QRollerFinalD>(0);

    public QFaiInFinal() {
    }

    public QFaiInFinal(QReportType QReportType, Company company, MMachine MMachine, PRoutineD PRoutineD, Users usersByInspector, Users usersByOp, PWo PWo, QConclusionDic QConclusionDic, Users usersByShiftLeader, String projectName, String lotNo, Date opDate, String type, Date slDate, Date inspDate, String falInFinalNo, Set<QUnRollerD> QUnRollerDs, Set<QFaiPulleyD> QFaiPulleyDs, Set<QRollerFinalD> QRollerFinalDs) {
       this.QReportType = QReportType;
       this.company = company;
       this.MMachine = MMachine;
       this.PRoutineD = PRoutineD;
       this.usersByInspector = usersByInspector;
       this.usersByOp = usersByOp;
       this.PWo = PWo;
       this.QConclusionDic = QConclusionDic;
       this.usersByShiftLeader = usersByShiftLeader;
       this.projectName = projectName;
       this.lotNo = lotNo;
       this.opDate = opDate;
       this.type = type;
       this.slDate = slDate;
       this.inspDate = inspDate;
       this.falInFinalNo = falInFinalNo;
       this.QUnRollerDs = QUnRollerDs;
       this.QFaiPulleyDs = QFaiPulleyDs;
       this.QRollerFinalDs = QRollerFinalDs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_fai_in_final", unique=true, nullable=false)
    public Long getIdFaiInFinal() {
        return this.idFaiInFinal;
    }
    
    public void setIdFaiInFinal(Long idFaiInFinal) {
        this.idFaiInFinal = idFaiInFinal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_report_type")
    public QReportType getQReportType() {
        return this.QReportType;
    }
    
    public void setQReportType(QReportType QReportType) {
        this.QReportType = QReportType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_machine")
    public MMachine getMMachine() {
        return this.MMachine;
    }
    
    public void setMMachine(MMachine MMachine) {
        this.MMachine = MMachine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_routine_d")
    public PRoutineD getPRoutineD() {
        return this.PRoutineD;
    }
    
    public void setPRoutineD(PRoutineD PRoutineD) {
        this.PRoutineD = PRoutineD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inspector")
    public Users getUsersByInspector() {
        return this.usersByInspector;
    }
    
    public void setUsersByInspector(Users usersByInspector) {
        this.usersByInspector = usersByInspector;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="op")
    public Users getUsersByOp() {
        return this.usersByOp;
    }
    
    public void setUsersByOp(Users usersByOp) {
        this.usersByOp = usersByOp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wo")
    public PWo getPWo() {
        return this.PWo;
    }
    
    public void setPWo(PWo PWo) {
        this.PWo = PWo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_conclusion")
    public QConclusionDic getQConclusionDic() {
        return this.QConclusionDic;
    }
    
    public void setQConclusionDic(QConclusionDic QConclusionDic) {
        this.QConclusionDic = QConclusionDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="shift_leader")
    public Users getUsersByShiftLeader() {
        return this.usersByShiftLeader;
    }
    
    public void setUsersByShiftLeader(Users usersByShiftLeader) {
        this.usersByShiftLeader = usersByShiftLeader;
    }
    
    @Column(name="project_name", length=64)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @Column(name="lot_no", length=64)
    public String getLotNo() {
        return this.lotNo;
    }
    
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="op_date", length=10)
    public Date getOpDate() {
        return this.opDate;
    }
    
    public void setOpDate(Date opDate) {
        this.opDate = opDate;
    }
    
    @Column(name="type", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="sl_date", length=10)
    public Date getSlDate() {
        return this.slDate;
    }
    
    public void setSlDate(Date slDate) {
        this.slDate = slDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="insp_date", length=10)
    public Date getInspDate() {
        return this.inspDate;
    }
    
    public void setInspDate(Date inspDate) {
        this.inspDate = inspDate;
    }
    
    @Column(name="fal_in_final_no", length=20)
    public String getFalInFinalNo() {
        return this.falInFinalNo;
    }
    
    public void setFalInFinalNo(String falInFinalNo) {
        this.falInFinalNo = falInFinalNo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QFaiInFinal")
    public Set<QUnRollerD> getQUnRollerDs() {
        return this.QUnRollerDs;
    }
    
    public void setQUnRollerDs(Set<QUnRollerD> QUnRollerDs) {
        this.QUnRollerDs = QUnRollerDs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QFaiInFinal")
    public Set<QFaiPulleyD> getQFaiPulleyDs() {
        return this.QFaiPulleyDs;
    }
    
    public void setQFaiPulleyDs(Set<QFaiPulleyD> QFaiPulleyDs) {
        this.QFaiPulleyDs = QFaiPulleyDs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QFaiInFinal")
    public Set<QRollerFinalD> getQRollerFinalDs() {
        return this.QRollerFinalDs;
    }
    
    public void setQRollerFinalDs(Set<QRollerFinalD> QRollerFinalDs) {
        this.QRollerFinalDs = QRollerFinalDs;
    }




}


