package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QFaiPulleyD generated by hbm2java
 */
@Entity
@Table(name="q_fai_pulley_d"
    ,catalog="jms4"
)
public class QFaiPulleyD  implements java.io.Serializable {


     private Long idFaiPulleyD;
     private QCheckList QCheckList;
     private QConclusionDic QConclusionDicByInspConclusion;
     private QFaiInFinal QFaiInFinal;
     private QConclusionDic QConclusionDicByOpConclusion;
     private String opResult;
     private String inspResult;

    public QFaiPulleyD() {
    }

	
    public QFaiPulleyD(Long idFaiPulleyD) {
        this.idFaiPulleyD = idFaiPulleyD;
    }
    public QFaiPulleyD(Long idFaiPulleyD, QCheckList QCheckList, QConclusionDic QConclusionDicByInspConclusion, QFaiInFinal QFaiInFinal, QConclusionDic QConclusionDicByOpConclusion, String opResult, String inspResult) {
       this.idFaiPulleyD = idFaiPulleyD;
       this.QCheckList = QCheckList;
       this.QConclusionDicByInspConclusion = QConclusionDicByInspConclusion;
       this.QFaiInFinal = QFaiInFinal;
       this.QConclusionDicByOpConclusion = QConclusionDicByOpConclusion;
       this.opResult = opResult;
       this.inspResult = inspResult;
    }
   
     @Id 
    
    @Column(name="id_fai_pulley_d", unique=true, nullable=false)
    public Long getIdFaiPulleyD() {
        return this.idFaiPulleyD;
    }
    
    public void setIdFaiPulleyD(Long idFaiPulleyD) {
        this.idFaiPulleyD = idFaiPulleyD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_check_list")
    public QCheckList getQCheckList() {
        return this.QCheckList;
    }
    
    public void setQCheckList(QCheckList QCheckList) {
        this.QCheckList = QCheckList;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="insp_conclusion")
    public QConclusionDic getQConclusionDicByInspConclusion() {
        return this.QConclusionDicByInspConclusion;
    }
    
    public void setQConclusionDicByInspConclusion(QConclusionDic QConclusionDicByInspConclusion) {
        this.QConclusionDicByInspConclusion = QConclusionDicByInspConclusion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fai_in_final")
    public QFaiInFinal getQFaiInFinal() {
        return this.QFaiInFinal;
    }
    
    public void setQFaiInFinal(QFaiInFinal QFaiInFinal) {
        this.QFaiInFinal = QFaiInFinal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="op_conclusion")
    public QConclusionDic getQConclusionDicByOpConclusion() {
        return this.QConclusionDicByOpConclusion;
    }
    
    public void setQConclusionDicByOpConclusion(QConclusionDic QConclusionDicByOpConclusion) {
        this.QConclusionDicByOpConclusion = QConclusionDicByOpConclusion;
    }
    
    @Column(name="op_result", length=20)
    public String getOpResult() {
        return this.opResult;
    }
    
    public void setOpResult(String opResult) {
        this.opResult = opResult;
    }
    
    @Column(name="insp_result", length=20)
    public String getInspResult() {
        return this.inspResult;
    }
    
    public void setInspResult(String inspResult) {
        this.inspResult = inspResult;
    }




}


