package com.jms.domain.db;
// Generated 2016-8-23 16:01:55 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QFileManagent generated by hbm2java
 */
@Entity
@Table(name="q_file_managent"
)
public class QFileManagent  implements java.io.Serializable {


     private Long idFile;
     private QFileType QFileType;
     private String fileNo;
     private Long idRoutineD;
     private Long creator;
     private Date creationTime;
     private String orgFilename;
     private String fileName;
     private Long uploadByUser;
     private Long idCompany;
     private Long idWo;
     private Long idMaterial;

    public QFileManagent() {
    }

    public QFileManagent(QFileType QFileType, String fileNo, Long idRoutineD, Long creator, Date creationTime, String orgFilename, String fileName, Long uploadByUser, Long idCompany, Long idWo) {
       this.QFileType = QFileType;
       this.fileNo = fileNo;
       this.idRoutineD = idRoutineD;
       this.creator = creator;
       this.creationTime = creationTime;
       this.orgFilename = orgFilename;
       this.fileName = fileName;
       this.uploadByUser = uploadByUser;
       this.idCompany = idCompany;
       this.idWo = idWo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_file", unique=true, nullable=false)
    public Long getIdFile() {
        return this.idFile;
    }
    
    public void setIdFile(Long idFile) {
        this.idFile = idFile;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_file_type")
    public QFileType getQFileType() {
        return this.QFileType;
    }
    
    public void setQFileType(QFileType QFileType) {
        this.QFileType = QFileType;
    }
    
    @Column(name="file_no", length=20)
    public String getFileNo() {
        return this.fileNo;
    }
    
    public void setFileNo(String fileNo) {
        this.fileNo = fileNo;
    }
    
    @Column(name="id_routine_d")
    public Long getIdRoutineD() {
        return this.idRoutineD;
    }
    
    public void setIdRoutineD(Long idRoutineD) {
        this.idRoutineD = idRoutineD;
    }
    
    @Column(name="creator")
    public Long getCreator() {
        return this.creator;
    }
    
    public void setCreator(Long creator) {
        this.creator = creator;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_time", length=19)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    
    @Column(name="org_filename", length=256)
    public String getOrgFilename() {
        return this.orgFilename;
    }
    
    public void setOrgFilename(String orgFilename) {
        this.orgFilename = orgFilename;
    }
    
    @Column(name="file_name", length=256)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="upload_by_user")
    public Long getUploadByUser() {
        return this.uploadByUser;
    }
    
    public void setUploadByUser(Long uploadByUser) {
        this.uploadByUser = uploadByUser;
    }
    
    @Column(name="id_company")
    public Long getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Long idCompany) {
        this.idCompany = idCompany;
    }
    
    @Column(name="id_wo")
    public Long getIdWo() {
        return this.idWo;
    }
    
    public void setIdWo(Long idWo) {
        this.idWo = idWo;
    }

    @Column(name="id_material")
	public Long getIdMaterial() {
		return idMaterial;
	}

	public void setIdMaterial(Long idMaterial) {
		this.idMaterial = idMaterial;
	}




}


