package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QLocationDic generated by hbm2java
 */
@Entity
@Table(name="q_location_dic"
    ,catalog="jms5"
)
public class QLocationDic  implements java.io.Serializable {


     private Long idLocation;
     private Company company;
     private QStatusDic QStatusDic;
     private String des;
     private Set<QNcp> QNcps = new HashSet<QNcp>(0);

    public QLocationDic() {
    }

    public QLocationDic(Company company, QStatusDic QStatusDic, String des, Set<QNcp> QNcps) {
       this.company = company;
       this.QStatusDic = QStatusDic;
       this.des = des;
       this.QNcps = QNcps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_location", unique=true, nullable=false)
    public Long getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Long idLocation) {
        this.idLocation = idLocation;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_qstatus")
    public QStatusDic getQStatusDic() {
        return this.QStatusDic;
    }
    
    public void setQStatusDic(QStatusDic QStatusDic) {
        this.QStatusDic = QStatusDic;
    }
    
    @Column(name="des", length=32)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QLocationDic")
    public Set<QNcp> getQNcps() {
        return this.QNcps;
    }
    
    public void setQNcps(Set<QNcp> QNcps) {
        this.QNcps = QNcps;
    }




}


