package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QNgMode generated by hbm2java
 */
@Entity
@Table(name="q_ng_mode"
    ,catalog="jms4"
)
public class QNgMode  implements java.io.Serializable {


     private Long idNgMode;
     private Company company;
     private String des;
     private Set<QUnRollerD> QUnRollerDs = new HashSet<QUnRollerD>(0);

    public QNgMode() {
    }

	
    public QNgMode(Long idNgMode) {
        this.idNgMode = idNgMode;
    }
    public QNgMode(Long idNgMode, Company company, String des, Set<QUnRollerD> QUnRollerDs) {
       this.idNgMode = idNgMode;
       this.company = company;
       this.des = des;
       this.QUnRollerDs = QUnRollerDs;
    }
   
     @Id 
    
    @Column(name="id_ng_mode", unique=true, nullable=false)
    public Long getIdNgMode() {
        return this.idNgMode;
    }
    
    public void setIdNgMode(Long idNgMode) {
        this.idNgMode = idNgMode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="des", length=256)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QNgMode")
    public Set<QUnRollerD> getQUnRollerDs() {
        return this.QUnRollerDs;
    }
    
    public void setQUnRollerDs(Set<QUnRollerD> QUnRollerDs) {
        this.QUnRollerDs = QUnRollerDs;
    }




}


