package com.jms.domain.db;
// Generated 2016-8-23 14:57:20 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QNoProcess generated by hbm2java
 */
@Entity
@Table(name="q_no_process"
    ,catalog="jms5"
)
public class QNoProcess  implements java.io.Serializable {


     private String idNoProcess;
     private QNcr2 QNcr2;
     private QDeviation QDeviation;
     private String ncpNo;
     private String lotNo;
     private Long idMaterial;
     private Long qty;
     private String default_;
     private Long idLocation;
     private String des;
     private String release1;
     private String audit01;
     private String comment;
     private String isSorting;
     private Float sortingQty;
     private String isReworking;
     private Float reworkingQty;
     private String isScrap;
     private Float scrapQty;
     private String idReject;
     private Float manHour;
     private String isDeviation;
     private String deviationQty;
     private String owner;
     private String audit02;
     private String countersign;
     private String approval02;
     private String inprovementAction;
     private String concernOrNot;
     private String response;
     private String audit03;
     private String approval03;
     private Long idQstatus;
     private Long idCompany;

    public QNoProcess() {
    }

	
    public QNoProcess(String idNoProcess) {
        this.idNoProcess = idNoProcess;
    }
    public QNoProcess(String idNoProcess, QNcr2 QNcr2, QDeviation QDeviation, String ncpNo, String lotNo, Long idMaterial, Long qty, String default_, Long idLocation, String des, String release1, String audit01, String comment, String isSorting, Float sortingQty, String isReworking, Float reworkingQty, String isScrap, Float scrapQty, String idReject, Float manHour, String isDeviation, String deviationQty, String owner, String audit02, String countersign, String approval02, String inprovementAction, String concernOrNot, String response, String audit03, String approval03, Long idQstatus, Long idCompany) {
       this.idNoProcess = idNoProcess;
       this.QNcr2 = QNcr2;
       this.QDeviation = QDeviation;
       this.ncpNo = ncpNo;
       this.lotNo = lotNo;
       this.idMaterial = idMaterial;
       this.qty = qty;
       this.default_ = default_;
       this.idLocation = idLocation;
       this.des = des;
       this.release1 = release1;
       this.audit01 = audit01;
       this.comment = comment;
       this.isSorting = isSorting;
       this.sortingQty = sortingQty;
       this.isReworking = isReworking;
       this.reworkingQty = reworkingQty;
       this.isScrap = isScrap;
       this.scrapQty = scrapQty;
       this.idReject = idReject;
       this.manHour = manHour;
       this.isDeviation = isDeviation;
       this.deviationQty = deviationQty;
       this.owner = owner;
       this.audit02 = audit02;
       this.countersign = countersign;
       this.approval02 = approval02;
       this.inprovementAction = inprovementAction;
       this.concernOrNot = concernOrNot;
       this.response = response;
       this.audit03 = audit03;
       this.approval03 = approval03;
       this.idQstatus = idQstatus;
       this.idCompany = idCompany;
    }
   
     @Id 
    
    @Column(name="id_no_process", unique=true, nullable=false, length=20)
    public String getIdNoProcess() {
        return this.idNoProcess;
    }
    
    public void setIdNoProcess(String idNoProcess) {
        this.idNoProcess = idNoProcess;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ncr")
    public QNcr2 getQNcr2() {
        return this.QNcr2;
    }
    
    public void setQNcr2(QNcr2 QNcr2) {
        this.QNcr2 = QNcr2;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_deviation")
    public QDeviation getQDeviation() {
        return this.QDeviation;
    }
    
    public void setQDeviation(QDeviation QDeviation) {
        this.QDeviation = QDeviation;
    }
    
    @Column(name="ncp_no", length=32)
    public String getNcpNo() {
        return this.ncpNo;
    }
    
    public void setNcpNo(String ncpNo) {
        this.ncpNo = ncpNo;
    }
    
    @Column(name="lot_no", length=64)
    public String getLotNo() {
        return this.lotNo;
    }
    
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo;
    }
    
    @Column(name="id_material")
    public Long getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Long idMaterial) {
        this.idMaterial = idMaterial;
    }
    
    @Column(name="qty")
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    
    @Column(name="_default_", length=18)
    public String getDefault_() {
        return this.default_;
    }
    
    public void setDefault_(String default_) {
        this.default_ = default_;
    }
    
    @Column(name="id_location")
    public Long getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Long idLocation) {
        this.idLocation = idLocation;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="release1", length=32)
    public String getRelease1() {
        return this.release1;
    }
    
    public void setRelease1(String release1) {
        this.release1 = release1;
    }
    
    @Column(name="audit01", length=32)
    public String getAudit01() {
        return this.audit01;
    }
    
    public void setAudit01(String audit01) {
        this.audit01 = audit01;
    }
    
    @Column(name="comment", length=1024)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    @Column(name="is_sorting", length=20)
    public String getIsSorting() {
        return this.isSorting;
    }
    
    public void setIsSorting(String isSorting) {
        this.isSorting = isSorting;
    }
    
    @Column(name="sorting_qty", precision=12, scale=0)
    public Float getSortingQty() {
        return this.sortingQty;
    }
    
    public void setSortingQty(Float sortingQty) {
        this.sortingQty = sortingQty;
    }
    
    @Column(name="is_reworking", length=20)
    public String getIsReworking() {
        return this.isReworking;
    }
    
    public void setIsReworking(String isReworking) {
        this.isReworking = isReworking;
    }
    
    @Column(name="reworking_qty", precision=12, scale=0)
    public Float getReworkingQty() {
        return this.reworkingQty;
    }
    
    public void setReworkingQty(Float reworkingQty) {
        this.reworkingQty = reworkingQty;
    }
    
    @Column(name="is_scrap", length=20)
    public String getIsScrap() {
        return this.isScrap;
    }
    
    public void setIsScrap(String isScrap) {
        this.isScrap = isScrap;
    }
    
    @Column(name="scrap_qty", precision=12, scale=0)
    public Float getScrapQty() {
        return this.scrapQty;
    }
    
    public void setScrapQty(Float scrapQty) {
        this.scrapQty = scrapQty;
    }
    
    @Column(name="id_reject", length=20)
    public String getIdReject() {
        return this.idReject;
    }
    
    public void setIdReject(String idReject) {
        this.idReject = idReject;
    }
    
    @Column(name="man_hour", precision=12, scale=0)
    public Float getManHour() {
        return this.manHour;
    }
    
    public void setManHour(Float manHour) {
        this.manHour = manHour;
    }
    
    @Column(name="is_deviation", length=20)
    public String getIsDeviation() {
        return this.isDeviation;
    }
    
    public void setIsDeviation(String isDeviation) {
        this.isDeviation = isDeviation;
    }
    
    @Column(name="deviation_qty", length=18)
    public String getDeviationQty() {
        return this.deviationQty;
    }
    
    public void setDeviationQty(String deviationQty) {
        this.deviationQty = deviationQty;
    }
    
    @Column(name="owner", length=32)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    
    @Column(name="audit02", length=32)
    public String getAudit02() {
        return this.audit02;
    }
    
    public void setAudit02(String audit02) {
        this.audit02 = audit02;
    }
    
    @Column(name="countersign", length=32)
    public String getCountersign() {
        return this.countersign;
    }
    
    public void setCountersign(String countersign) {
        this.countersign = countersign;
    }
    
    @Column(name="approval02", length=20)
    public String getApproval02() {
        return this.approval02;
    }
    
    public void setApproval02(String approval02) {
        this.approval02 = approval02;
    }
    
    @Column(name="inprovement_action", length=1024)
    public String getInprovementAction() {
        return this.inprovementAction;
    }
    
    public void setInprovementAction(String inprovementAction) {
        this.inprovementAction = inprovementAction;
    }
    
    @Column(name="concern_or_not", length=20)
    public String getConcernOrNot() {
        return this.concernOrNot;
    }
    
    public void setConcernOrNot(String concernOrNot) {
        this.concernOrNot = concernOrNot;
    }
    
    @Column(name="response", length=32)
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }
    
    @Column(name="audit03", length=32)
    public String getAudit03() {
        return this.audit03;
    }
    
    public void setAudit03(String audit03) {
        this.audit03 = audit03;
    }
    
    @Column(name="approval03", length=32)
    public String getApproval03() {
        return this.approval03;
    }
    
    public void setApproval03(String approval03) {
        this.approval03 = approval03;
    }
    
    @Column(name="id_qstatus")
    public Long getIdQstatus() {
        return this.idQstatus;
    }
    
    public void setIdQstatus(Long idQstatus) {
        this.idQstatus = idQstatus;
    }
    
    @Column(name="id_company")
    public Long getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Long idCompany) {
        this.idCompany = idCompany;
    }




}


