package com.jms.domain.db;
// Generated 2016-8-23 16:01:55 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QNoProcess generated by hbm2java
 */
@Entity
@Table(name="q_no_process"
    ,catalog="jms5"
)
public class QNoProcess  implements java.io.Serializable {


     private Long idNoProcess;
     private String ncpNo;
     private String lotNo;
     private Long idMaterial;
     private Float qty;
     private String default_;
     private Long idLocation;
     private String des;
     private Long release1;
     private Long audit01;
     private String comment;
     private String isSorting;
     private Float sortingQty;
     private String isReworking;
     private Float reworkingQty;
     private String isScrap;
     private Float scrapQty;
     private String idReject;
     private Float manHour;
     private String isDeviation;
     private Float deviationQty;
     private Long owner;
     private Long audit02;
     private Long countersign;
     private Long approval02;
     private String inprovementAction;
     private String concernOrNot;
     private Long response;
     private Long audit03;
     private Long approval03;
     private Long idQstatus;
     private Long idCompany;
     
     private Long idCpp;
     private Long idUnplannedStop;
     private Date creationTime;
     
     private Set<QDeviation> QDeviations = new HashSet<QDeviation>(0);
     private Set<QNcr2> QNcr2s = new HashSet<QNcr2>(0);

    public QNoProcess() {
    }

    public QNoProcess(String ncpNo, String lotNo, Long idMaterial, Float qty, String default_, Long idLocation, String des, Long release1, Long audit01, String comment, String isSorting, Float sortingQty, String isReworking, Float reworkingQty, String isScrap, Float scrapQty, String idReject, Float manHour, String isDeviation, Float deviationQty, Long owner, Long audit02, Long countersign, Long approval02, String inprovementAction, String concernOrNot, Long response, Long audit03, Long approval03, Long idQstatus, Long idCompany,Long idCpp,Long idUnplannedStop, Set<QDeviation> QDeviations, Set<QNcr2> QNcr2s) {
       this.ncpNo = ncpNo;
       this.lotNo = lotNo;
       this.idMaterial = idMaterial;
       this.qty = qty;
       this.default_ = default_;
       this.idLocation = idLocation;
       this.des = des;
       this.release1 = release1;
       this.audit01 = audit01;
       this.comment = comment;
       this.isSorting = isSorting;
       this.sortingQty = sortingQty;
       this.isReworking = isReworking;
       this.reworkingQty = reworkingQty;
       this.isScrap = isScrap;
       this.scrapQty = scrapQty;
       this.idReject = idReject;
       this.manHour = manHour;
       this.isDeviation = isDeviation;
       this.deviationQty = deviationQty;
       this.owner = owner;
       this.audit02 = audit02;
       this.countersign = countersign;
       this.approval02 = approval02;
       this.inprovementAction = inprovementAction;
       this.concernOrNot = concernOrNot;
       this.response = response;
       this.audit03 = audit03;
       this.approval03 = approval03;
       this.idQstatus = idQstatus;
       this.idCompany = idCompany;
       this.idCpp=idCpp;
       this.idUnplannedStop=idUnplannedStop;
       this.QDeviations = QDeviations;
       this.QNcr2s = QNcr2s;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_no_process", unique=true, nullable=false)
    public Long getIdNoProcess() {
        return this.idNoProcess;
    }
    
    public void setIdNoProcess(Long idNoProcess) {
        this.idNoProcess = idNoProcess;
    }
    
    @Column(name="ncp_no", length=32)
    public String getNcpNo() {
        return this.ncpNo;
    }
    
    public void setNcpNo(String ncpNo) {
        this.ncpNo = ncpNo;
    }
    
    @Column(name="lot_no", length=64)
    public String getLotNo() {
        return this.lotNo;
    }
    
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo;
    }
    
    @Column(name="id_material")
    public Long getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Long idMaterial) {
        this.idMaterial = idMaterial;
    }
    
    @Column(name="qty", precision=12, scale=0)
    public Float getQty() {
        return this.qty;
    }
    
    public void setQty(Float qty) {
        this.qty = qty;
    }
    
    @Column(name="_default_", length=18)
    public String getDefault_() {
        return this.default_;
    }
    
    public void setDefault_(String default_) {
        this.default_ = default_;
    }
    
    @Column(name="id_location")
    public Long getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Long idLocation) {
        this.idLocation = idLocation;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="release1")
    public Long getRelease1() {
        return this.release1;
    }
    
    public void setRelease1(Long release1) {
        this.release1 = release1;
    }
    
    @Column(name="audit01")
    public Long getAudit01() {
        return this.audit01;
    }
    
    public void setAudit01(Long audit01) {
        this.audit01 = audit01;
    }
    
    @Column(name="comment", length=1024)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    @Column(name="is_sorting", length=20)
    public String getIsSorting() {
        return this.isSorting;
    }
    
    public void setIsSorting(String isSorting) {
        this.isSorting = isSorting;
    }
    
    @Column(name="sorting_qty", precision=12, scale=0)
    public Float getSortingQty() {
        return this.sortingQty;
    }
    
    public void setSortingQty(Float sortingQty) {
        this.sortingQty = sortingQty;
    }
    
    @Column(name="is_reworking", length=20)
    public String getIsReworking() {
        return this.isReworking;
    }
    
    public void setIsReworking(String isReworking) {
        this.isReworking = isReworking;
    }
    
    @Column(name="reworking_qty", precision=12, scale=0)
    public Float getReworkingQty() {
        return this.reworkingQty;
    }
    
    public void setReworkingQty(Float reworkingQty) {
        this.reworkingQty = reworkingQty;
    }
    
    @Column(name="is_scrap", length=20)
    public String getIsScrap() {
        return this.isScrap;
    }
    
    public void setIsScrap(String isScrap) {
        this.isScrap = isScrap;
    }
    
    @Column(name="scrap_qty", precision=12, scale=0)
    public Float getScrapQty() {
        return this.scrapQty;
    }
    
    public void setScrapQty(Float scrapQty) {
        this.scrapQty = scrapQty;
    }
    
    @Column(name="id_reject", length=20)
    public String getIdReject() {
        return this.idReject;
    }
    
    public void setIdReject(String idReject) {
        this.idReject = idReject;
    }
    
    @Column(name="man_hour", precision=12, scale=0)
    public Float getManHour() {
        return this.manHour;
    }
    
    public void setManHour(Float manHour) {
        this.manHour = manHour;
    }
    
    @Column(name="is_deviation", length=20)
    public String getIsDeviation() {
        return this.isDeviation;
    }
    
    public void setIsDeviation(String isDeviation) {
        this.isDeviation = isDeviation;
    }
    
    @Column(name="deviation_qty", precision=12, scale=0)
    public Float getDeviationQty() {
        return this.deviationQty;
    }
    
    public void setDeviationQty(Float deviationQty) {
        this.deviationQty = deviationQty;
    }
    
    @Column(name="owner")
    public Long getOwner() {
        return this.owner;
    }
    
    public void setOwner(Long owner) {
        this.owner = owner;
    }
    
    @Column(name="audit02")
    public Long getAudit02() {
        return this.audit02;
    }
    
    public void setAudit02(Long audit02) {
        this.audit02 = audit02;
    }
    
    @Column(name="countersign")
    public Long getCountersign() {
        return this.countersign;
    }
    
    public void setCountersign(Long countersign) {
        this.countersign = countersign;
    }
    
    @Column(name="approval02")
    public Long getApproval02() {
        return this.approval02;
    }
    
    public void setApproval02(Long approval02) {
        this.approval02 = approval02;
    }
    
    @Column(name="inprovement_action", length=1024)
    public String getInprovementAction() {
        return this.inprovementAction;
    }
    
    public void setInprovementAction(String inprovementAction) {
        this.inprovementAction = inprovementAction;
    }
    
    @Column(name="concern_or_not", length=20)
    public String getConcernOrNot() {
        return this.concernOrNot;
    }
    
    public void setConcernOrNot(String concernOrNot) {
        this.concernOrNot = concernOrNot;
    }
    
    @Column(name="response")
    public Long getResponse() {
        return this.response;
    }
    
    public void setResponse(Long response) {
        this.response = response;
    }
    
    @Column(name="audit03")
    public Long getAudit03() {
        return this.audit03;
    }
    
    public void setAudit03(Long audit03) {
        this.audit03 = audit03;
    }
    
    @Column(name="approval03")
    public Long getApproval03() {
        return this.approval03;
    }
    
    public void setApproval03(Long approval03) {
        this.approval03 = approval03;
    }
    
    @Column(name="id_qstatus")
    public Long getIdQstatus() {
        return this.idQstatus;
    }
    
    public void setIdQstatus(Long idQstatus) {
        this.idQstatus = idQstatus;
    }
    
    @Column(name="id_company")
    public Long getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Long idCompany) {
        this.idCompany = idCompany;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QNoProcess")
    public Set<QDeviation> getQDeviations() {
        return this.QDeviations;
    }
    
    public void setQDeviations(Set<QDeviation> QDeviations) {
        this.QDeviations = QDeviations;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QNoProcess")
    public Set<QNcr2> getQNcr2s() {
        return this.QNcr2s;
    }
    
    public void setQNcr2s(Set<QNcr2> QNcr2s) {
        this.QNcr2s = QNcr2s;
    }

    @Column(name="id_cpp")
	public Long getIdCpp() {
		return idCpp;
	}

	public void setIdCpp(Long idCpp) {
		this.idCpp = idCpp;
	}

    @Column(name="id_unplanned_stop")
	public Long getIdUnplannedStop() {
		return idUnplannedStop;
	}

	public void setIdUnplannedStop(Long idUnplannedStop) {
		this.idUnplannedStop = idUnplannedStop;
	}
	  @Temporal(TemporalType.DATE)
	 @Column(name="creation_time", length=10)
	public Date getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}




}


