package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QReportType generated by hbm2java
 */
@Entity
@Table(name="q_report_type"
    ,catalog="jms4"
)
public class QReportType  implements java.io.Serializable {


     private Long idReportType;
     private Company company;
     private String des;
     private Set<QFaiInFinal> QFaiInFinals = new HashSet<QFaiInFinal>(0);

    public QReportType() {
    }

	
    public QReportType(Long idReportType) {
        this.idReportType = idReportType;
    }
    public QReportType(Long idReportType, Company company, String des, Set<QFaiInFinal> QFaiInFinals) {
       this.idReportType = idReportType;
       this.company = company;
       this.des = des;
       this.QFaiInFinals = QFaiInFinals;
    }
   
     @Id 
    
    @Column(name="id_report_type", unique=true, nullable=false)
    public Long getIdReportType() {
        return this.idReportType;
    }
    
    public void setIdReportType(Long idReportType) {
        this.idReportType = idReportType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="des", length=20)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="QReportType")
    public Set<QFaiInFinal> getQFaiInFinals() {
        return this.QFaiInFinals;
    }
    
    public void setQFaiInFinals(Set<QFaiInFinal> QFaiInFinals) {
        this.QFaiInFinals = QFaiInFinals;
    }




}


