package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QRollerFinalD generated by hbm2java
 */
@Entity
@Table(name="q_roller_final_d"
    ,catalog="jms4"
)
public class QRollerFinalD  implements java.io.Serializable {


     private Long idRollerFinalD;
     private QCheckList QCheckList;
     private QFaiInFinal QFaiInFinal;
     private String r01;
     private String r02;
     private String r03;
     private String r04;
     private String r05;
     private String r06;

    public QRollerFinalD() {
    }

	
    public QRollerFinalD(Long idRollerFinalD) {
        this.idRollerFinalD = idRollerFinalD;
    }
    public QRollerFinalD(Long idRollerFinalD, QCheckList QCheckList, QFaiInFinal QFaiInFinal, String r01, String r02, String r03, String r04, String r05, String r06) {
       this.idRollerFinalD = idRollerFinalD;
       this.QCheckList = QCheckList;
       this.QFaiInFinal = QFaiInFinal;
       this.r01 = r01;
       this.r02 = r02;
       this.r03 = r03;
       this.r04 = r04;
       this.r05 = r05;
       this.r06 = r06;
    }
   
     @Id 
    
    @Column(name="id_roller_final_d", unique=true, nullable=false)
    public Long getIdRollerFinalD() {
        return this.idRollerFinalD;
    }
    
    public void setIdRollerFinalD(Long idRollerFinalD) {
        this.idRollerFinalD = idRollerFinalD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_check_list")
    public QCheckList getQCheckList() {
        return this.QCheckList;
    }
    
    public void setQCheckList(QCheckList QCheckList) {
        this.QCheckList = QCheckList;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fai_in_final")
    public QFaiInFinal getQFaiInFinal() {
        return this.QFaiInFinal;
    }
    
    public void setQFaiInFinal(QFaiInFinal QFaiInFinal) {
        this.QFaiInFinal = QFaiInFinal;
    }
    
    @Column(name="r01", length=20)
    public String getR01() {
        return this.r01;
    }
    
    public void setR01(String r01) {
        this.r01 = r01;
    }
    
    @Column(name="r02", length=20)
    public String getR02() {
        return this.r02;
    }
    
    public void setR02(String r02) {
        this.r02 = r02;
    }
    
    @Column(name="r03", length=20)
    public String getR03() {
        return this.r03;
    }
    
    public void setR03(String r03) {
        this.r03 = r03;
    }
    
    @Column(name="r04", length=20)
    public String getR04() {
        return this.r04;
    }
    
    public void setR04(String r04) {
        this.r04 = r04;
    }
    
    @Column(name="r05", length=20)
    public String getR05() {
        return this.r05;
    }
    
    public void setR05(String r05) {
        this.r05 = r05;
    }
    
    @Column(name="r06", length=20)
    public String getR06() {
        return this.r06;
    }
    
    public void setR06(String r06) {
        this.r06 = r06;
    }




}


