package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receipt generated by hbm2java
 */
@Entity
@Table(name="receipt"
    ,catalog="jms5"
)
public class Receipt  implements java.io.Serializable {


     private Long idReceipt;
     private Company company;
     private String title;
     private String invoiceCode;
     private String invoiceNo;
     private String issuedBy;
     private Date issuedDate;
     private String payer;
     private String content;
     private Long amount;
     private Set<BuyRecord> buyRecords = new HashSet<BuyRecord>(0);

    public Receipt() {
    }

	
    public Receipt(Company company) {
        this.company = company;
    }
    public Receipt(Company company, String title, String invoiceCode, String invoiceNo, String issuedBy, Date issuedDate, String payer, String content, Long amount, Set<BuyRecord> buyRecords) {
       this.company = company;
       this.title = title;
       this.invoiceCode = invoiceCode;
       this.invoiceNo = invoiceNo;
       this.issuedBy = issuedBy;
       this.issuedDate = issuedDate;
       this.payer = payer;
       this.content = content;
       this.amount = amount;
       this.buyRecords = buyRecords;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_receipt", unique=true, nullable=false)
    public Long getIdReceipt() {
        return this.idReceipt;
    }
    
    public void setIdReceipt(Long idReceipt) {
        this.idReceipt = idReceipt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="title", length=256)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="invoice_code", length=20)
    public String getInvoiceCode() {
        return this.invoiceCode;
    }
    
    public void setInvoiceCode(String invoiceCode) {
        this.invoiceCode = invoiceCode;
    }
    
    @Column(name="invoice_no", length=20)
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    
    @Column(name="issued_by", length=20)
    public String getIssuedBy() {
        return this.issuedBy;
    }
    
    public void setIssuedBy(String issuedBy) {
        this.issuedBy = issuedBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="issued_date", length=10)
    public Date getIssuedDate() {
        return this.issuedDate;
    }
    
    public void setIssuedDate(Date issuedDate) {
        this.issuedDate = issuedDate;
    }
    
    @Column(name="payer", length=20)
    public String getPayer() {
        return this.payer;
    }
    
    public void setPayer(String payer) {
        this.payer = payer;
    }
    
    @Column(name="content", length=512)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    @Column(name="amount", precision=10, scale=0)
    public Long getAmount() {
        return this.amount;
    }
    
    public void setAmount(Long amount) {
        this.amount = amount;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="receipt")
    public Set<BuyRecord> getBuyRecords() {
        return this.buyRecords;
    }
    
    public void setBuyRecords(Set<BuyRecord> buyRecords) {
        this.buyRecords = buyRecords;
    }




}


