package com.jms.domain.db;
// Generated 2015-7-3 12:07:40 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePrivId generated by hbm2java
 */
@Embeddable
public class RolePrivId  implements java.io.Serializable {


     private Long idModule;
     private Long idRole;

    public RolePrivId() {
    }

    public RolePrivId(Long idModule, Long idRole) {
       this.idModule = idModule;
       this.idRole = idRole;
    }
   

    @Column(name="ID_MODULE", nullable=false)
    public Long getIdModule() {
        return this.idModule;
    }
    
    public void setIdModule(Long idModule) {
        this.idModule = idModule;
    }

    @Column(name="ID_ROLE", nullable=false)
    public Long getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolePrivId) ) return false;
		 RolePrivId castOther = ( RolePrivId ) other; 
         
		 return ( (this.getIdModule()==castOther.getIdModule()) || ( this.getIdModule()!=null && castOther.getIdModule()!=null && this.getIdModule().equals(castOther.getIdModule()) ) )
 && ( (this.getIdRole()==castOther.getIdRole()) || ( this.getIdRole()!=null && castOther.getIdRole()!=null && this.getIdRole().equals(castOther.getIdRole()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdModule() == null ? 0 : this.getIdModule().hashCode() );
         result = 37 * result + ( getIdRole() == null ? 0 : this.getIdRole().hashCode() );
         return result;
   }   


}


