package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SAttachment generated by hbm2java
 */
@Entity
@Table(name="s_attachment"
    ,catalog="jms5"
)
public class SAttachment  implements java.io.Serializable {


     private Long id;
     private Users users;
     private String name;
     private String des;
     private String filename;
     private String orgFilename;
     private Set<SCompanyCoAttachment> SCompanyCoAttachments = new HashSet<SCompanyCoAttachment>(0);
     private Set<SMaterialAttachment> SMaterialAttachments = new HashSet<SMaterialAttachment>(0);
     private Set<SSo> SSos = new HashSet<SSo>(0);
     private Set<SPo> SPos = new HashSet<SPo>(0);

    public SAttachment() {
    }

    public SAttachment(Users users, String name, String des, String filename, String orgFilename, Set<SCompanyCoAttachment> SCompanyCoAttachments, Set<SMaterialAttachment> SMaterialAttachments, Set<SSo> SSos, Set<SPo> SPos) {
       this.users = users;
       this.name = name;
       this.des = des;
       this.filename = filename;
       this.orgFilename = orgFilename;
       this.SCompanyCoAttachments = SCompanyCoAttachments;
       this.SMaterialAttachments = SMaterialAttachments;
       this.SSos = SSos;
       this.SPos = SPos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="upload_by")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="filename", length=128)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Column(name="org_filename", length=128)
    public String getOrgFilename() {
        return this.orgFilename;
    }
    
    public void setOrgFilename(String orgFilename) {
        this.orgFilename = orgFilename;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SAttachment")
    public Set<SCompanyCoAttachment> getSCompanyCoAttachments() {
        return this.SCompanyCoAttachments;
    }
    
    public void setSCompanyCoAttachments(Set<SCompanyCoAttachment> SCompanyCoAttachments) {
        this.SCompanyCoAttachments = SCompanyCoAttachments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SAttachment")
    public Set<SMaterialAttachment> getSMaterialAttachments() {
        return this.SMaterialAttachments;
    }
    
    public void setSMaterialAttachments(Set<SMaterialAttachment> SMaterialAttachments) {
        this.SMaterialAttachments = SMaterialAttachments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SAttachment")
    public Set<SSo> getSSos() {
        return this.SSos;
    }
    
    public void setSSos(Set<SSo> SSos) {
        this.SSos = SSos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SAttachment")
    public Set<SPo> getSPos() {
        return this.SPos;
    }
    
    public void setSPos(Set<SPo> SPos) {
        this.SPos = SPos;
    }




}


