package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SBin generated by hbm2java
 */
@Entity
@Table(name="s_bin"
    ,catalog="jms5"
)
public class SBin  implements java.io.Serializable {


     private Long idBin;
     private SYesOrNoDic SYesOrNoDic;
     private SStk SStk;
     private SStatusDic SStatusDic;
     private String bin;
     private String des;
     private Set<SInventory> SInventories = new HashSet<SInventory>(0);
     private Set<SMtfMaterial> SMtfMaterialsForToBin = new HashSet<SMtfMaterial>(0);
     private Set<SMtfMaterial> SMtfMaterialsForFromBin = new HashSet<SMtfMaterial>(0);
     private Set<MMachine> MMachines = new HashSet<MMachine>(0);


    public SBin() {
    }

    public SBin(SYesOrNoDic SYesOrNoDic, SStk SStk, SStatusDic SStatusDic, String bin, Set<SInventory> SInventories, Set<SMtfMaterial> SMtfMaterialsForToBin, Set<SMtfMaterial> SMtfMaterialsForFromBin, Set<MMachine> MMachines) {
       this.SYesOrNoDic = SYesOrNoDic;
       this.SStk = SStk;
       this.SStatusDic = SStatusDic;
       this.bin = bin;
       this.SInventories = SInventories;
       this.SMtfMaterialsForToBin = SMtfMaterialsForToBin;
       this.SMtfMaterialsForFromBin = SMtfMaterialsForFromBin;
       this.MMachines = MMachines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_bin", unique=true, nullable=false)
    public Long getIdBin() {
        return this.idBin;
    }
    
    public void setIdBin(Long idBin) {
        this.idBin = idBin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="is_return_shelf")
    public SYesOrNoDic getSYesOrNoDic() {
        return this.SYesOrNoDic;
    }
    
    public void setSYesOrNoDic(SYesOrNoDic SYesOrNoDic) {
        this.SYesOrNoDic = SYesOrNoDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_stk")
    public SStk getSStk() {
        return this.SStk;
    }
    
    public void setSStk(SStk SStk) {
        this.SStk = SStk;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
    
    @Column(name="bin", length=64)
    public String getBin() {
        return this.bin;
    }
    
    public void setBin(String bin) {
        this.bin = bin;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SBin")
    public Set<SInventory> getSInventories() {
        return this.SInventories;
    }
    
    public void setSInventories(Set<SInventory> SInventories) {
        this.SInventories = SInventories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SBinByToBin")
    public Set<SMtfMaterial> getSMtfMaterialsForToBin() {
        return this.SMtfMaterialsForToBin;
    }
    
    public void setSMtfMaterialsForToBin(Set<SMtfMaterial> SMtfMaterialsForToBin) {
        this.SMtfMaterialsForToBin = SMtfMaterialsForToBin;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SBinByFromBin")
    public Set<SMtfMaterial> getSMtfMaterialsForFromBin() {
        return this.SMtfMaterialsForFromBin;
    }
    
    public void setSMtfMaterialsForFromBin(Set<SMtfMaterial> SMtfMaterialsForFromBin) {
        this.SMtfMaterialsForFromBin = SMtfMaterialsForFromBin;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SBin")
    public Set<MMachine> getMMachines() {
        return this.MMachines;
    }
    
    public void setMMachines(Set<MMachine> MMachines) {
        this.MMachines = MMachines;
    }

    @Column(name="des", length=256)
	public String getDes() {
		return des;
	}

	public void setDes(String des) {
		this.des = des;
	}




}


