package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SBin generated by hbm2java
 */
@Entity
@Table(name="s_bin"
    ,catalog="jms3"
)
public class SBin  implements java.io.Serializable {


     private SBinId id;
     private SStk SStk;
     private SStatusDic SStatusDic;
     private Set<SMtf> SMtfsForSMtfIbfk2 = new HashSet<SMtf>(0);
     private Set<SMtf> SMtfsForSMtfIbfk3 = new HashSet<SMtf>(0);
     private Set<SInventory> SInventories = new HashSet<SInventory>(0);

    public SBin() {
    }

	
    public SBin(SBinId id, SStk SStk) {
        this.id = id;
        this.SStk = SStk;
    }
    public SBin(SBinId id, SStk SStk, SStatusDic SStatusDic, Set<SMtf> SMtfsForSMtfIbfk2, Set<SMtf> SMtfsForSMtfIbfk3, Set<SInventory> SInventories) {
       this.id = id;
       this.SStk = SStk;
       this.SStatusDic = SStatusDic;
       this.SMtfsForSMtfIbfk2 = SMtfsForSMtfIbfk2;
       this.SMtfsForSMtfIbfk3 = SMtfsForSMtfIbfk3;
       this.SInventories = SInventories;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idStk", column=@Column(name="id_stk", nullable=false) ), 
        @AttributeOverride(name="bin", column=@Column(name="bin", nullable=false, length=64) ) } )
    public SBinId getId() {
        return this.id;
    }
    
    public void setId(SBinId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_stk", nullable=false, insertable=false, updatable=false)
    public SStk getSStk() {
        return this.SStk;
    }
    
    public void setSStk(SStk SStk) {
        this.SStk = SStk;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SBinBySMtfIbfk2")
    public Set<SMtf> getSMtfsForSMtfIbfk2() {
        return this.SMtfsForSMtfIbfk2;
    }
    
    public void setSMtfsForSMtfIbfk2(Set<SMtf> SMtfsForSMtfIbfk2) {
        this.SMtfsForSMtfIbfk2 = SMtfsForSMtfIbfk2;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SBinBySMtfIbfk3")
    public Set<SMtf> getSMtfsForSMtfIbfk3() {
        return this.SMtfsForSMtfIbfk3;
    }
    
    public void setSMtfsForSMtfIbfk3(Set<SMtf> SMtfsForSMtfIbfk3) {
        this.SMtfsForSMtfIbfk3 = SMtfsForSMtfIbfk3;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SBin")
    public Set<SInventory> getSInventories() {
        return this.SInventories;
    }
    
    public void setSInventories(Set<SInventory> SInventories) {
        this.SInventories = SInventories;
    }




}


