package com.jms.domain.db;
// Generated 2015-7-5 10:54:07 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ScheduleDoc generated by hbm2java
 */
@Entity
@Table(name="schedule_doc"
    ,catalog="jms"
)
public class ScheduleDoc  implements java.io.Serializable {


     private ScheduleDocId id;
     private Document document;
     private Schedule schedule;
     private Long publish;

    public ScheduleDoc() {
    }

	
    public ScheduleDoc(ScheduleDocId id, Document document, Schedule schedule) {
        this.id = id;
        this.document = document;
        this.schedule = schedule;
    }
    public ScheduleDoc(ScheduleDocId id, Document document, Schedule schedule, Long publish) {
       this.id = id;
       this.document = document;
       this.schedule = schedule;
       this.publish = publish;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idSchedule", column=@Column(name="ID_SCHEDULE", nullable=false) ), 
        @AttributeOverride(name="idDocument", column=@Column(name="ID_DOCUMENT", nullable=false) ) } )
    public ScheduleDocId getId() {
        return this.id;
    }
    
    public void setId(ScheduleDocId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOCUMENT", nullable=false, insertable=false, updatable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SCHEDULE", nullable=false, insertable=false, updatable=false)
    public Schedule getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }
    
    @Column(name="PUBLISH")
    public Long getPublish() {
        return this.publish;
    }
    
    public void setPublish(Long publish) {
        this.publish = publish;
    }




}


