package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SCompanyCo generated by hbm2java
 */
@Entity
@Table(name="s_company_co"
)
public class SCompanyCo  implements java.io.Serializable {


     private Long id;
     private Company company;
     private STypeDic STypeDic;
     private SStatusDic SStatusDic;
     private SCountryDic SCountryDic;
     private SLevelDic SLevelDic;
     private STermDic STermDicByFreightTerm;
     private STermDic STermDicByPaymentTerm;
     private String code;
     private String shortName;
     private String name;
     private String tel;
     private String fax;
     private String addressAct;
     private String addressReg;
     private String artificialPerson;
     private String taxNo;
     private String bank;
     private String bankAccNo;
     private String url;
     private String remark;
     private String autoRemark;
     private String auditBy;
     private Long idCompany1;
     private Long auditStatus;
     private String email;
     
     private Set<SMtfResidual> SMtfResiduals = new HashSet<SMtfResidual>(0);
     private Set<SPo> SPos = new HashSet<SPo>(0);
     private Set<SSo> SSos = new HashSet<SSo>(0);
     private Set<SCompanyCoAttachment> SCompanyCoAttachments = new HashSet<SCompanyCoAttachment>(0);
     private Set<SLinkman> SLinkmans = new HashSet<SLinkman>(0);

    public SCompanyCo() {
    }

    public SCompanyCo(Company company, STypeDic STypeDic, SStatusDic SStatusDic, SCountryDic SCountryDic, SLevelDic SLevelDic, STermDic STermDicByFreightTerm, STermDic STermDicByPaymentTerm, String code, String shortName, String name, String tel, String fax, String addressAct, String addressReg, String artificialPerson, String taxNo, String bank, String bankAccNo, String url, String remark, String autoRemark, String auditBy, Set<SMtfResidual> SMtfResiduals, Set<SPo> SPos, Set<SSo> SSos, Set<SCompanyCoAttachment> SCompanyCoAttachments, Set<SLinkman> SLinkmans) {
       this.company = company;
       this.STypeDic = STypeDic;
       this.SStatusDic = SStatusDic;
       this.SCountryDic = SCountryDic;
       this.SLevelDic = SLevelDic;
       this.STermDicByFreightTerm = STermDicByFreightTerm;
       this.STermDicByPaymentTerm = STermDicByPaymentTerm;
       this.code = code;
       this.shortName = shortName;
       this.name = name;
       this.tel = tel;
       this.fax = fax;
       this.addressAct = addressAct;
       this.addressReg = addressReg;
       this.artificialPerson = artificialPerson;
       this.taxNo = taxNo;
       this.bank = bank;
       this.bankAccNo = bankAccNo;
       this.url = url;
       this.remark = remark;
       this.autoRemark = autoRemark;
       this.auditBy = auditBy;
       this.SMtfResiduals = SMtfResiduals;
       this.SPos = SPos;
       this.SSos = SSos;
       this.SCompanyCoAttachments = SCompanyCoAttachments;
       this.SLinkmans = SLinkmans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type")
    public STypeDic getSTypeDic() {
        return this.STypeDic;
    }
    
    public void setSTypeDic(STypeDic STypeDic) {
        this.STypeDic = STypeDic;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country")
    public SCountryDic getSCountryDic() {
        return this.SCountryDic;
    }
    
    public void setSCountryDic(SCountryDic SCountryDic) {
        this.SCountryDic = SCountryDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="level")
    public SLevelDic getSLevelDic() {
        return this.SLevelDic;
    }
    
    public void setSLevelDic(SLevelDic SLevelDic) {
        this.SLevelDic = SLevelDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="freight_term")
    public STermDic getSTermDicByFreightTerm() {
        return this.STermDicByFreightTerm;
    }
    
    public void setSTermDicByFreightTerm(STermDic STermDicByFreightTerm) {
        this.STermDicByFreightTerm = STermDicByFreightTerm;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_term")
    public STermDic getSTermDicByPaymentTerm() {
        return this.STermDicByPaymentTerm;
    }
    
    public void setSTermDicByPaymentTerm(STermDic STermDicByPaymentTerm) {
        this.STermDicByPaymentTerm = STermDicByPaymentTerm;
    }
    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="short_name", length=20)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="tel", length=20)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    
    @Column(name="fax", length=20)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    @Column(name="address_act", length=128)
    public String getAddressAct() {
        return this.addressAct;
    }
    
    public void setAddressAct(String addressAct) {
        this.addressAct = addressAct;
    }
    
    @Column(name="address_reg", length=128)
    public String getAddressReg() {
        return this.addressReg;
    }
    
    public void setAddressReg(String addressReg) {
        this.addressReg = addressReg;
    }
    
    @Column(name="artificial_person", length=20)
    public String getArtificialPerson() {
        return this.artificialPerson;
    }
    
    public void setArtificialPerson(String artificialPerson) {
        this.artificialPerson = artificialPerson;
    }
    
    @Column(name="tax_no", length=64)
    public String getTaxNo() {
        return this.taxNo;
    }
    
    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo;
    }
    
    @Column(name="bank", length=64)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    
    @Column(name="bank_acc_no", length=64)
    public String getBankAccNo() {
        return this.bankAccNo;
    }
    
    public void setBankAccNo(String bankAccNo) {
        this.bankAccNo = bankAccNo;
    }
    
    @Column(name="url", length=512)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="auto_remark", length=1024)
    public String getAutoRemark() {
        return this.autoRemark;
    }
    
    public void setAutoRemark(String autoRemark) {
        this.autoRemark = autoRemark;
    }
    
    @Column(name="audit_by", length=20)
    public String getAuditBy() {
        return this.auditBy;
    }
    
    public void setAuditBy(String auditBy) {
        this.auditBy = auditBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SCompanyCo")
    public Set<SMtfResidual> getSMtfResiduals() {
        return this.SMtfResiduals;
    }
    
    public void setSMtfResiduals(Set<SMtfResidual> SMtfResiduals) {
        this.SMtfResiduals = SMtfResiduals;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SCompanyCo")
    public Set<SPo> getSPos() {
        return this.SPos;
    }
    
    public void setSPos(Set<SPo> SPos) {
        this.SPos = SPos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SCompanyCo")
    public Set<SSo> getSSos() {
        return this.SSos;
    }
    
    public void setSSos(Set<SSo> SSos) {
        this.SSos = SSos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SCompanyCo")
    public Set<SCompanyCoAttachment> getSCompanyCoAttachments() {
        return this.SCompanyCoAttachments;
    }
    
    public void setSCompanyCoAttachments(Set<SCompanyCoAttachment> SCompanyCoAttachments) {
        this.SCompanyCoAttachments = SCompanyCoAttachments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SCompanyCo")
    public Set<SLinkman> getSLinkmans() {
        return this.SLinkmans;
    }
    
    public void setSLinkmans(Set<SLinkman> SLinkmans) {
        this.SLinkmans = SLinkmans;
    }

    @Column(name="id_company1")
	public Long getIdCompany1() {
		return idCompany1;
	}

	public void setIdCompany1(Long idCompany1) {
		this.idCompany1 = idCompany1;
	}

    @Column(name="audit_status")
	public Long getAuditStatus() {
		return auditStatus;
	}

	public void setAuditStatus(Long auditStatus) {
		this.auditStatus = auditStatus;
	}
	  @Column(name="email", length=128)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}




}


