package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SCostCenter generated by hbm2java
 */
@Entity
@Table(name="s_cost_center"
    ,catalog="jms4"
)
public class SCostCenter  implements java.io.Serializable {


     private Long idCostCenter;
     private Company company;
     private Long costCenterNo;
     private String des;
     private Set<SMaterial> SMaterials = new HashSet<SMaterial>(0);
     private Set<MDept> MDepts = new HashSet<MDept>(0);

    public SCostCenter() {
    }

    public SCostCenter(Company company, Long costCenterNo, String des, Set<SMaterial> SMaterials, Set<MDept> MDepts) {
       this.company = company;
       this.costCenterNo = costCenterNo;
       this.des = des;
       this.SMaterials = SMaterials;
       this.MDepts = MDepts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_cost_center", unique=true, nullable=false)
    public Long getIdCostCenter() {
        return this.idCostCenter;
    }
    
    public void setIdCostCenter(Long idCostCenter) {
        this.idCostCenter = idCostCenter;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="cost_center_no")
    public Long getCostCenterNo() {
        return this.costCenterNo;
    }
    
    public void setCostCenterNo(Long costCenterNo) {
        this.costCenterNo = costCenterNo;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SCostCenter")
    public Set<SMaterial> getSMaterials() {
        return this.SMaterials;
    }
    
    public void setSMaterials(Set<SMaterial> SMaterials) {
        this.SMaterials = SMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SCostCenter")
    public Set<MDept> getMDepts() {
        return this.MDepts;
    }
    
    public void setMDepts(Set<MDept> MDepts) {
        this.MDepts = MDepts;
    }




}


