package com.jms.domain.db;
// Generated 2015-6-7 13:49:29 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sector generated by hbm2java
 */
@Entity
@Table(name="sector"
    ,catalog="jms"
)
public class Sector  implements java.io.Serializable {


     private Integer idSector;
     private Company company;
     private String sector;
     private String description;
     private Integer enabled;
     private Integer seq;
     private Set<Roles> roleses = new HashSet<Roles>(0);
     private Set<SectorMember> sectorMembers = new HashSet<SectorMember>(0);

    public Sector() {
    }

	
    public Sector(Company company) {
        this.company = company;
    }
    public Sector(Company company, String sector, String description, Integer enabled, Integer seq, Set<Roles> roleses, Set<SectorMember> sectorMembers) {
       this.company = company;
       this.sector = sector;
       this.description = description;
       this.enabled = enabled;
       this.seq = seq;
       this.roleses = roleses;
       this.sectorMembers = sectorMembers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_SECTOR", unique=true, nullable=false)
    public Integer getIdSector() {
        return this.idSector;
    }
    
    public void setIdSector(Integer idSector) {
        this.idSector = idSector;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMPANY", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="SECTOR", length=64)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }
    
    @Column(name="Description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="ENABLED")
    public Integer getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
    
    @Column(name="SEQ")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sector")
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sector")
    public Set<SectorMember> getSectorMembers() {
        return this.sectorMembers;
    }
    
    public void setSectorMembers(Set<SectorMember> sectorMembers) {
        this.sectorMembers = sectorMembers;
    }




}


