package com.jms.domain.db;
// Generated 2015-6-7 13:49:29 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SectorMemberId generated by hbm2java
 */
@Embeddable
public class SectorMemberId  implements java.io.Serializable {


     private int idSector;
     private int idUser;

    public SectorMemberId() {
    }

    public SectorMemberId(int idSector, int idUser) {
       this.idSector = idSector;
       this.idUser = idUser;
    }
   

    @Column(name="ID_SECTOR", nullable=false)
    public int getIdSector() {
        return this.idSector;
    }
    
    public void setIdSector(int idSector) {
        this.idSector = idSector;
    }

    @Column(name="ID_USER", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SectorMemberId) ) return false;
		 SectorMemberId castOther = ( SectorMemberId ) other; 
         
		 return (this.getIdSector()==castOther.getIdSector())
 && (this.getIdUser()==castOther.getIdUser());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSector();
         result = 37 * result + this.getIdUser();
         return result;
   }   


}


