package com.jms.domain.db;
// Generated 2015-7-3 12:07:40 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * Service generated by hbm2java
 */
@Audited
@Entity
@Table(name="service"
    ,catalog="jms"
)
public class Service  implements java.io.Serializable {


     private Long idService;
     private ServiceType serviceType;
     private String description;
     private Float payment;
     private Set<BuyRecord> buyRecords = new HashSet<BuyRecord>(0);

    public Service() {
    }

	
    public Service(Long idService) {
        this.idService = idService;
    }
    public Service(Long idService, ServiceType serviceType, String description, Float payment, Set<BuyRecord> buyRecords) {
       this.idService = idService;
       this.serviceType = serviceType;
       this.description = description;
       this.payment = payment;
       this.buyRecords = buyRecords;
    }
   
     @Id 
    
    @Column(name="ID_SERVICE", unique=true, nullable=false)
    public Long getIdService() {
        return this.idService;
    }
    
    public void setIdService(Long idService) {
        this.idService = idService;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SERVICE_TYPE")
    public ServiceType getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(ServiceType serviceType) {
        this.serviceType = serviceType;
    }
    
    @Column(name="DESCRIPTION", length=20)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="PAYMENT", precision=12, scale=0)
    public Float getPayment() {
        return this.payment;
    }
    
    public void setPayment(Float payment) {
        this.payment = payment;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="service")
    public Set<BuyRecord> getBuyRecords() {
        return this.buyRecords;
    }
    
    public void setBuyRecords(Set<BuyRecord> buyRecords) {
        this.buyRecords = buyRecords;
    }




}


