package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SInventory generated by hbm2java
 */
@Entity
@Table(name="s_inventory"
    ,catalog="jms3"
)
public class SInventory  implements java.io.Serializable {


     private Long id;
     private SBin SBin;
     private SMaterial SMaterial;
     private Long qty;
     private Long orderBy;

    public SInventory() {
    }

    public SInventory(SBin SBin, SMaterial SMaterial, Long qty, Long orderBy) {
       this.SBin = SBin;
       this.SMaterial = SMaterial;
       this.qty = qty;
       this.orderBy = orderBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="id_stk", referencedColumnName="id_stk"), 
        @JoinColumn(name="bin", referencedColumnName="bin") } )
    public SBin getSBin() {
        return this.SBin;
    }
    
    public void setSBin(SBin SBin) {
        this.SBin = SBin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mat")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
    
    @Column(name="qty", precision=10, scale=0)
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    
    @Column(name="order_by")
    public Long getOrderBy() {
        return this.orderBy;
    }
    
    public void setOrderBy(Long orderBy) {
        this.orderBy = orderBy;
    }




}


