package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SLinkman generated by hbm2java
 */
@Entity
@Table(name="s_linkman"
    ,catalog="jms5"
)
public class SLinkman  implements java.io.Serializable {


     private Long idLinkman;
     private SStatusDic SStatusDic;
     private SGenderDic SGenderDic;
     private SCompanyCo SCompanyCo;
     private String name;
     private String position;
     private String phoneNo;
     private String EMail;
     private Long qq;
     private String weChat;
     private String wangwang;
     private String remark;
     private String autoRemark;

    public SLinkman() {
    }

    public SLinkman(SStatusDic SStatusDic, SGenderDic SGenderDic, SCompanyCo SCompanyCo, String name, String position, String phoneNo, String EMail, Long qq, String weChat, String wangwang, String remark, String autoRemark) {
       this.SStatusDic = SStatusDic;
       this.SGenderDic = SGenderDic;
       this.SCompanyCo = SCompanyCo;
       this.name = name;
       this.position = position;
       this.phoneNo = phoneNo;
       this.EMail = EMail;
       this.qq = qq;
       this.weChat = weChat;
       this.wangwang = wangwang;
       this.remark = remark;
       this.autoRemark = autoRemark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_linkman", unique=true, nullable=false)
    public Long getIdLinkman() {
        return this.idLinkman;
    }
    
    public void setIdLinkman(Long idLinkman) {
        this.idLinkman = idLinkman;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gender")
    public SGenderDic getSGenderDic() {
        return this.SGenderDic;
    }
    
    public void setSGenderDic(SGenderDic SGenderDic) {
        this.SGenderDic = SGenderDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_co")
    public SCompanyCo getSCompanyCo() {
        return this.SCompanyCo;
    }
    
    public void setSCompanyCo(SCompanyCo SCompanyCo) {
        this.SCompanyCo = SCompanyCo;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="position", length=64)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    
    @Column(name="phone_no")
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    
    @Column(name="e_mail", length=64)
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    
    @Column(name="qq")
    public Long getQq() {
        return this.qq;
    }
    
    public void setQq(Long qq) {
        this.qq = qq;
    }
    
    @Column(name="we_chat", length=32)
    public String getWeChat() {
        return this.weChat;
    }
    
    public void setWeChat(String weChat) {
        this.weChat = weChat;
    }
    
    @Column(name="wangwang", length=32)
    public String getWangwang() {
        return this.wangwang;
    }
    
    public void setWangwang(String wangwang) {
        this.wangwang = wangwang;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="auto_remark", length=1024)
    public String getAutoRemark() {
        return this.autoRemark;
    }
    
    public void setAutoRemark(String autoRemark) {
        this.autoRemark = autoRemark;
    }




}


