package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SMaterial generated by hbm2java
 */
@Entity
@Table(name="s_material"
    ,catalog="jms3"
)
public class SMaterial  implements java.io.Serializable {


     private Long id;
     private SMaterialCategory SMaterialCategory;
     private SMaterialTypeDic SMaterialTypeDic;
     private SStatusDic SStatusDic;
     private SUnitDic SUnitDicByUnitPur;
     private SUnitDic SUnitDicByUnitInf;
     private String pno;
     private Long rev;
     private String des;
     private Long moq;
     private String brand;
     private String remark;
     private String autoRemark;
     private Set<SInventory> SInventories = new HashSet<SInventory>(0);
     private Set<SDoMaterial> SDoMaterials = new HashSet<SDoMaterial>(0);
     private Set<SRmaMaterial> SRmaMaterials = new HashSet<SRmaMaterial>(0);
     private Set<SMaterialAttachment> SMaterialAttachments = new HashSet<SMaterialAttachment>(0);
     private Set<SMtfMaterial> SMtfMaterials = new HashSet<SMtfMaterial>(0);
     private Set<SIncomeMaterial> SIncomeMaterials = new HashSet<SIncomeMaterial>(0);
     private Set<SMaterialPic> SMaterialPics = new HashSet<SMaterialPic>(0);
     private Set<SMrbMaterial> SMrbMaterials = new HashSet<SMrbMaterial>(0);
     private Set<SPoMaterial> SPoMaterials = new HashSet<SPoMaterial>(0);
     private Set<SSoMaterial> SSoMaterials = new HashSet<SSoMaterial>(0);

    public SMaterial() {
    }

    public SMaterial(SMaterialCategory SMaterialCategory, SMaterialTypeDic SMaterialTypeDic, SStatusDic SStatusDic, SUnitDic SUnitDicByUnitPur, SUnitDic SUnitDicByUnitInf, String pno, Long rev, String des, Long moq, String brand, String remark, String autoRemark, Set<SInventory> SInventories, Set<SDoMaterial> SDoMaterials, Set<SRmaMaterial> SRmaMaterials, Set<SMaterialAttachment> SMaterialAttachments, Set<SMtfMaterial> SMtfMaterials, Set<SIncomeMaterial> SIncomeMaterials, Set<SMaterialPic> SMaterialPics, Set<SMrbMaterial> SMrbMaterials, Set<SPoMaterial> SPoMaterials, Set<SSoMaterial> SSoMaterials) {
       this.SMaterialCategory = SMaterialCategory;
       this.SMaterialTypeDic = SMaterialTypeDic;
       this.SStatusDic = SStatusDic;
       this.SUnitDicByUnitPur = SUnitDicByUnitPur;
       this.SUnitDicByUnitInf = SUnitDicByUnitInf;
       this.pno = pno;
       this.rev = rev;
       this.des = des;
       this.moq = moq;
       this.brand = brand;
       this.remark = remark;
       this.autoRemark = autoRemark;
       this.SInventories = SInventories;
       this.SDoMaterials = SDoMaterials;
       this.SRmaMaterials = SRmaMaterials;
       this.SMaterialAttachments = SMaterialAttachments;
       this.SMtfMaterials = SMtfMaterials;
       this.SIncomeMaterials = SIncomeMaterials;
       this.SMaterialPics = SMaterialPics;
       this.SMrbMaterials = SMrbMaterials;
       this.SPoMaterials = SPoMaterials;
       this.SSoMaterials = SSoMaterials;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category")
    public SMaterialCategory getSMaterialCategory() {
        return this.SMaterialCategory;
    }
    
    public void setSMaterialCategory(SMaterialCategory SMaterialCategory) {
        this.SMaterialCategory = SMaterialCategory;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type")
    public SMaterialTypeDic getSMaterialTypeDic() {
        return this.SMaterialTypeDic;
    }
    
    public void setSMaterialTypeDic(SMaterialTypeDic SMaterialTypeDic) {
        this.SMaterialTypeDic = SMaterialTypeDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_pur")
    public SUnitDic getSUnitDicByUnitPur() {
        return this.SUnitDicByUnitPur;
    }
    
    public void setSUnitDicByUnitPur(SUnitDic SUnitDicByUnitPur) {
        this.SUnitDicByUnitPur = SUnitDicByUnitPur;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_inf")
    public SUnitDic getSUnitDicByUnitInf() {
        return this.SUnitDicByUnitInf;
    }
    
    public void setSUnitDicByUnitInf(SUnitDic SUnitDicByUnitInf) {
        this.SUnitDicByUnitInf = SUnitDicByUnitInf;
    }
    
    @Column(name="pno", length=64)
    public String getPno() {
        return this.pno;
    }
    
    public void setPno(String pno) {
        this.pno = pno;
    }
    
    @Column(name="rev")
    public Long getRev() {
        return this.rev;
    }
    
    public void setRev(Long rev) {
        this.rev = rev;
    }
    
    @Column(name="des", length=200)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="moq")
    public Long getMoq() {
        return this.moq;
    }
    
    public void setMoq(Long moq) {
        this.moq = moq;
    }
    
    @Column(name="brand", length=20)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="auto_remark", length=8000)
    public String getAutoRemark() {
        return this.autoRemark;
    }
    
    public void setAutoRemark(String autoRemark) {
        this.autoRemark = autoRemark;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SInventory> getSInventories() {
        return this.SInventories;
    }
    
    public void setSInventories(Set<SInventory> SInventories) {
        this.SInventories = SInventories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SDoMaterial> getSDoMaterials() {
        return this.SDoMaterials;
    }
    
    public void setSDoMaterials(Set<SDoMaterial> SDoMaterials) {
        this.SDoMaterials = SDoMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SRmaMaterial> getSRmaMaterials() {
        return this.SRmaMaterials;
    }
    
    public void setSRmaMaterials(Set<SRmaMaterial> SRmaMaterials) {
        this.SRmaMaterials = SRmaMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SMaterialAttachment> getSMaterialAttachments() {
        return this.SMaterialAttachments;
    }
    
    public void setSMaterialAttachments(Set<SMaterialAttachment> SMaterialAttachments) {
        this.SMaterialAttachments = SMaterialAttachments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SMtfMaterial> getSMtfMaterials() {
        return this.SMtfMaterials;
    }
    
    public void setSMtfMaterials(Set<SMtfMaterial> SMtfMaterials) {
        this.SMtfMaterials = SMtfMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SIncomeMaterial> getSIncomeMaterials() {
        return this.SIncomeMaterials;
    }
    
    public void setSIncomeMaterials(Set<SIncomeMaterial> SIncomeMaterials) {
        this.SIncomeMaterials = SIncomeMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SMaterialPic> getSMaterialPics() {
        return this.SMaterialPics;
    }
    
    public void setSMaterialPics(Set<SMaterialPic> SMaterialPics) {
        this.SMaterialPics = SMaterialPics;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SMrbMaterial> getSMrbMaterials() {
        return this.SMrbMaterials;
    }
    
    public void setSMrbMaterials(Set<SMrbMaterial> SMrbMaterials) {
        this.SMrbMaterials = SMrbMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SPoMaterial> getSPoMaterials() {
        return this.SPoMaterials;
    }
    
    public void setSPoMaterials(Set<SPoMaterial> SPoMaterials) {
        this.SPoMaterials = SPoMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMaterial")
    public Set<SSoMaterial> getSSoMaterials() {
        return this.SSoMaterials;
    }
    
    public void setSSoMaterials(Set<SSoMaterial> SSoMaterials) {
        this.SSoMaterials = SSoMaterials;
    }




}


