package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WTaskParticipant generated by hbm2java
 */
@Entity
@Table(name="s_materal_cocompany"
)
public class SMaterialCocompany  implements java.io.Serializable {


     private SMaterialCocompanyId id;

     private Float prec;
     private Long isPrim;
     private Float price;

    public SMaterialCocompany() {
    }

	

     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idCompany", column=@Column(name="id_company", nullable=false) ), 
        @AttributeOverride(name="idMate", column=@Column(name="id_mat", nullable=false) ), 
        @AttributeOverride(name="idCocompany", column=@Column(name="id_cocompany", nullable=false) ) } )
    public SMaterialCocompanyId getId() {
        return this.id;
    }
    
    public void setId(SMaterialCocompanyId id) {
        this.id = id;
    }



	@Column(name = "prec", precision = 12, scale = 0)
	public Float getPrec() {
		return prec;
	}



	public void setPrec(Float prec) {
		this.prec = prec;
	}


    @Column(name="is_prim")
	public Long getIsPrim() {
		return isPrim;
	}



	public void setIsPrim(Long isPrim) {
		this.isPrim = isPrim;
	}


	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return price;
	}



	public void setPrice(Float price) {
		this.price = price;
	}




}


