package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SMaterialPic generated by hbm2java
 */
@Entity
@Table(name="s_material_pic"
    ,catalog="jms3"
)
public class SMaterialPic  implements java.io.Serializable {


     private Long id;
     private SMaterial SMaterial;
     private SPic SPic;
     private Long orderBy;

    public SMaterialPic() {
    }

    public SMaterialPic(SMaterial SMaterial, SPic SPic, Long orderBy) {
       this.SMaterial = SMaterial;
       this.SPic = SPic;
       this.orderBy = orderBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="material")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pic")
    public SPic getSPic() {
        return this.SPic;
    }
    
    public void setSPic(SPic SPic) {
        this.SPic = SPic;
    }
    
    @Column(name="order_by")
    public Long getOrderBy() {
        return this.orderBy;
    }
    
    public void setOrderBy(Long orderBy) {
        this.orderBy = orderBy;
    }




}


