package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SMaterialPic generated by hbm2java
 */
@Entity
@Table(name="s_material_bins"
)
public class SMaterialBins  implements java.io.Serializable {

       private SMaterialBinsId id;
       
       private Long idStk;
       private Long idCompany;
	   @EmbeddedId
	    
	    @AttributeOverrides( {
	        @AttributeOverride(name="idMaterial", column=@Column(name="id_material", nullable=false) ), 
	        @AttributeOverride(name="idBin", column=@Column(name="id_bin", nullable=false) ) } )
	    public SMaterialBinsId getId() {
	        return this.id;
	    }
	    
	    public void setId(SMaterialBinsId id) {
	        this.id = id;
	    }

	    @Column(name="id_stk")
		public Long getIdStk() {
			return idStk;
		}

		public void setIdStk(Long idStk) {
			this.idStk = idStk;
		}
		 @Column(name="id_company")
		public Long getIdCompany() {
			return idCompany;
		}

		public void setIdCompany(Long idCompany) {
			this.idCompany = idCompany;
		}



}


