package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SMrb generated by hbm2java
 */
@Entity
@Table(name="s_mrb"
    ,catalog="jms3"
)
public class SMrb  implements java.io.Serializable {


     private Long idMrb;
     private SStk SStk;
     private Company company;
     private SCompanyCo SCompanyCo;
     private SStatusDic SStatusDic;
     private Users users;
     private SAttachment SAttachment;
     private STermDic STermDicByPaymentTerm;
     private STermDic STermDicByFreightTerm;
     private String codeMrb;
     private Date dateOrder;
     private Long totalAmount;
     private Long taxRate;
     private Long exchange;
     private String remark;
     private Set<SMrbMaterial> SMrbMaterials = new HashSet<SMrbMaterial>(0);

    public SMrb() {
    }

    public SMrb(SStk SStk, Company company, SCompanyCo SCompanyCo, SStatusDic SStatusDic, Users users, SAttachment SAttachment, STermDic STermDicByPaymentTerm, STermDic STermDicByFreightTerm, String codeMrb, Date dateOrder, Long totalAmount, Long taxRate, Long exchange, String remark, Set<SMrbMaterial> SMrbMaterials) {
       this.SStk = SStk;
       this.company = company;
       this.SCompanyCo = SCompanyCo;
       this.SStatusDic = SStatusDic;
       this.users = users;
       this.SAttachment = SAttachment;
       this.STermDicByPaymentTerm = STermDicByPaymentTerm;
       this.STermDicByFreightTerm = STermDicByFreightTerm;
       this.codeMrb = codeMrb;
       this.dateOrder = dateOrder;
       this.totalAmount = totalAmount;
       this.taxRate = taxRate;
       this.exchange = exchange;
       this.remark = remark;
       this.SMrbMaterials = SMrbMaterials;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_mrb", unique=true, nullable=false)
    public Long getIdMrb() {
        return this.idMrb;
    }
    
    public void setIdMrb(Long idMrb) {
        this.idMrb = idMrb;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stk")
    public SStk getSStk() {
        return this.SStk;
    }
    
    public void setSStk(SStk SStk) {
        this.SStk = SStk;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_co")
    public SCompanyCo getSCompanyCo() {
        return this.SCompanyCo;
    }
    
    public void setSCompanyCo(SCompanyCo SCompanyCo) {
        this.SCompanyCo = SCompanyCo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_order")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attachment")
    public SAttachment getSAttachment() {
        return this.SAttachment;
    }
    
    public void setSAttachment(SAttachment SAttachment) {
        this.SAttachment = SAttachment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_term")
    public STermDic getSTermDicByPaymentTerm() {
        return this.STermDicByPaymentTerm;
    }
    
    public void setSTermDicByPaymentTerm(STermDic STermDicByPaymentTerm) {
        this.STermDicByPaymentTerm = STermDicByPaymentTerm;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="freight_term")
    public STermDic getSTermDicByFreightTerm() {
        return this.STermDicByFreightTerm;
    }
    
    public void setSTermDicByFreightTerm(STermDic STermDicByFreightTerm) {
        this.STermDicByFreightTerm = STermDicByFreightTerm;
    }
    
    @Column(name="code_mrb", length=64)
    public String getCodeMrb() {
        return this.codeMrb;
    }
    
    public void setCodeMrb(String codeMrb) {
        this.codeMrb = codeMrb;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_order", length=10)
    public Date getDateOrder() {
        return this.dateOrder;
    }
    
    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }
    
    @Column(name="total_amount", precision=10, scale=0)
    public Long getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }
    
    @Column(name="tax_rate", precision=10, scale=0)
    public Long getTaxRate() {
        return this.taxRate;
    }
    
    public void setTaxRate(Long taxRate) {
        this.taxRate = taxRate;
    }
    
    @Column(name="exchange", precision=10, scale=0)
    public Long getExchange() {
        return this.exchange;
    }
    
    public void setExchange(Long exchange) {
        this.exchange = exchange;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMrb")
    public Set<SMrbMaterial> getSMrbMaterials() {
        return this.SMrbMaterials;
    }
    
    public void setSMrbMaterials(Set<SMrbMaterial> SMrbMaterials) {
        this.SMrbMaterials = SMrbMaterials;
    }




}


