package com.jms.domain.db;
// Generated 2017-3-16 12:58:55 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SMt generated by hbm2java
 */
@Entity
@Table(name="s_mt"
)
public class SMt  implements java.io.Serializable {


     private Long id;
     private String mtNo;
     private Long idCompany1;
     private Long idCompany2;
     private String company2;
     private Long idCompany3;
     private String company3;
     private Long fromStk;
     private Date creationDate;
     private Date auditDate;
     private String PNo;
     private Long PId;
     private Long status;

    public SMt() {
    }

    public SMt(String mtNo, Long idCompany1, Long idCompany2, String company2, Long idCompany3, String company3, Long fromStk, Date creationDate, Date auditDate, String PNo, Long PId, Long status) {
       this.mtNo = mtNo;
       this.idCompany1 = idCompany1;
       this.idCompany2 = idCompany2;
       this.company2 = company2;
       this.idCompany3 = idCompany3;
       this.company3 = company3;
       this.fromStk = fromStk;
       this.creationDate = creationDate;
       this.auditDate = auditDate;
       this.PNo = PNo;
       this.PId = PId;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="mt_no", length=64)
    public String getMtNo() {
        return this.mtNo;
    }
    
    public void setMtNo(String mtNo) {
        this.mtNo = mtNo;
    }
    
    @Column(name="id_company1")
    public Long getIdCompany1() {
        return this.idCompany1;
    }
    
    public void setIdCompany1(Long idCompany1) {
        this.idCompany1 = idCompany1;
    }
    
    @Column(name="id_company2")
    public Long getIdCompany2() {
        return this.idCompany2;
    }
    
    public void setIdCompany2(Long idCompany2) {
        this.idCompany2 = idCompany2;
    }
    
    @Column(name="company2", length=256)
    public String getCompany2() {
        return this.company2;
    }
    
    public void setCompany2(String company2) {
        this.company2 = company2;
    }
    
    @Column(name="id_company3")
    public Long getIdCompany3() {
        return this.idCompany3;
    }
    
    public void setIdCompany3(Long idCompany3) {
        this.idCompany3 = idCompany3;
    }
    
    @Column(name="company3", length=256)
    public String getCompany3() {
        return this.company3;
    }
    
    public void setCompany3(String company3) {
        this.company3 = company3;
    }
    
    @Column(name="from_stk")
    public Long getFromStk() {
        return this.fromStk;
    }
    
    public void setFromStk(Long fromStk) {
        this.fromStk = fromStk;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="audit_date", length=10)
    public Date getAuditDate() {
        return this.auditDate;
    }
    
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }
    
    @Column(name="p_no", length=256)
    public String getPNo() {
        return this.PNo;
    }
    
    public void setPNo(String PNo) {
        this.PNo = PNo;
    }
    
    @Column(name="p_id")
    public Long getPId() {
        return this.PId;
    }
    
    public void setPId(Long PId) {
        this.PId = PId;
    }
    
    @Column(name="status")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }




}


