package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SMtfTypeDic generated by hbm2java
 */
@Entity
@Table(name="s_mtf_type_dic"
)
public class SMtfTypeDic  implements java.io.Serializable {


     private Long idMtfType;
     private String name;
     private String des;
     private Set<SMtf> SMtfs = new HashSet<SMtf>(0);
     private String nameEn;
    public SMtfTypeDic() {
    }

    public SMtfTypeDic(String name, String des, Set<SMtf> SMtfs) {
       this.name = name;
       this.des = des;
       this.SMtfs = SMtfs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_mtf_type", unique=true, nullable=false)
    public Long getIdMtfType() {
        return this.idMtfType;
    }
    
    public void setIdMtfType(Long idMtfType) {
        this.idMtfType = idMtfType;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=128)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMtfTypeDic")
    public Set<SMtf> getSMtfs() {
        return this.SMtfs;
    }
    
    public void setSMtfs(Set<SMtf> SMtfs) {
        this.SMtfs = SMtfs;
    }
    @Column(name="name_en", length=64)
	public String getNameEn() {
		return nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}




}


