package com.jms.domain.db;
// Generated 2017-3-2 14:26:33 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SMtfC generated by hbm2java
 */
@Entity
@Table(name="s_mtf_c"
)
public class SMtfC  implements java.io.Serializable {


     private Long id;
     private String mtNo;
     private Long idCompany1;
     private Long idCompany2;
     private String pno;
     private String lotNo;
     private String materialName;
     private Date creationDate;
     private Date auditDate;
     private Long qty;
     private Long type;
     private Long status;
     private Long idSmtf1;
     private Long idSmtf2;
	 private Long idPoMaterial;
	 private String company1;
	 private String company2;
	 private Long fromBin;
	 private String remark;

    public SMtfC() {
    }

    public SMtfC(String mtNo, Long idCompany1, Long idCompany2, String pno, String lotNo, String materialName, Date creationDate, Date auditDate, Long qty, Long type, Long status, Long idSmtf1, Long idSmtf2) {
       this.mtNo = mtNo;
       this.idCompany1 = idCompany1;
       this.idCompany2 = idCompany2;
       this.pno = pno;
       this.lotNo = lotNo;
       this.materialName = materialName;
       this.creationDate = creationDate;
       this.auditDate = auditDate;
       this.qty = qty;
       this.type = type;
       this.status = status;
       this.idSmtf1 = idSmtf1;
       this.idSmtf2 = idSmtf2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="mt_no", length=64)
    public String getMtNo() {
        return this.mtNo;
    }
    
    public void setMtNo(String mtNo) {
        this.mtNo = mtNo;
    }
    
    @Column(name="id_company1")
    public Long getIdCompany1() {
        return this.idCompany1;
    }
    
    public void setIdCompany1(Long idCompany1) {
        this.idCompany1 = idCompany1;
    }
    
    @Column(name="id_company2")
    public Long getIdCompany2() {
        return this.idCompany2;
    }
    
    public void setIdCompany2(Long idCompany2) {
        this.idCompany2 = idCompany2;
    }
    
    @Column(name="pno", length=64)
    public String getPno() {
        return this.pno;
    }
    
    public void setPno(String pno) {
        this.pno = pno;
    }
    
    @Column(name="lot_no", length=64)
    public String getLotNo() {
        return this.lotNo;
    }
    
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo;
    }
    
    @Column(name="material_name", length=128)
    public String getMaterialName() {
        return this.materialName;
    }
    
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="audit_date", length=10)
    public Date getAuditDate() {
        return this.auditDate;
    }
    
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }
    
    @Column(name="qty")
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    
    @Column(name="type")
    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    
    @Column(name="status")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    
    @Column(name="id_smtf1")
    public Long getIdSmtf1() {
        return this.idSmtf1;
    }
    
    public void setIdSmtf1(Long idSmtf1) {
        this.idSmtf1 = idSmtf1;
    }
    
    @Column(name="id_smtf2")
    public Long getIdSmtf2() {
        return this.idSmtf2;
    }
    
    public void setIdSmtf2(Long idSmtf2) {
        this.idSmtf2 = idSmtf2;
    }

    @Column(name="id_po_material")
    public Long getIdPoMaterial() {
		return idPoMaterial;
	}

	public void setIdPoMaterial(Long idPoMaterial) {
		this.idPoMaterial = idPoMaterial;
	}
    @Column(name="company1", length=128)
	public String getCompany1() {
		return company1;
	}

	public void setCompany1(String company1) {
		this.company1 = company1;
	}
    @Column(name="company2", length=128)
	public String getCompany2() {
		return company2;
	}

	public void setCompany2(String company2) {
		this.company2 = company2;
	}

    @Column(name="from_bin")
	public Long getFromBin() {
		return fromBin;
	}

	public void setFromBin(Long fromBin) {
		this.fromBin = fromBin;
	}

	 @Column(name="remark", length=256)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}


}


