package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SMtfResidual generated by hbm2java
 */
@Entity
@Table(name="s_mtf_residual"
)
public class SMtfResidual  implements java.io.Serializable {


     private Long idMtfResidual;
     private SCompanyCo SCompanyCo;
     private String expressNo;
     private Set<SMtf> SMtfs = new HashSet<SMtf>(0);

    public SMtfResidual() {
    }

    public SMtfResidual(SCompanyCo SCompanyCo, String expressNo, Set<SMtf> SMtfs) {
       this.SCompanyCo = SCompanyCo;
       this.expressNo = expressNo;
       this.SMtfs = SMtfs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_mtf_residual", unique=true, nullable=false)
    public Long getIdMtfResidual() {
        return this.idMtfResidual;
    }
    
    public void setIdMtfResidual(Long idMtfResidual) {
        this.idMtfResidual = idMtfResidual;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_company")
    public SCompanyCo getSCompanyCo() {
        return this.SCompanyCo;
    }
    
    public void setSCompanyCo(SCompanyCo SCompanyCo) {
        this.SCompanyCo = SCompanyCo;
    }
    
    @Column(name="express_no", length=20)
    public String getExpressNo() {
        return this.expressNo;
    }
    
    public void setExpressNo(String expressNo) {
        this.expressNo = expressNo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMtfResidual")
    public Set<SMtf> getSMtfs() {
        return this.SMtfs;
    }
    
    public void setSMtfs(Set<SMtf> SMtfs) {
        this.SMtfs = SMtfs;
    }




}


