package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SMtfMaterial generated by hbm2java
 */
@Entity
@Table(name="s_mtf_material"
    ,catalog="jms4"
)
public class SMtfMaterial  implements java.io.Serializable {


     private Long idMtfMaterial;
     private SBin SBinByToBin;
     private SSo SSo;
     private SPoMaterial SPoMaterial;
     private SStatusDic SStatusDic;
     private SMaterial SMaterial;
     private PWoBom PWoBom;
     private SMtf SMtf;
     private SBin SBinByFromBin;
     private Long qty;
     private String lotNo;
     private Long UQty;
     private Long box;

    public SMtfMaterial() {
    }

	
    public SMtfMaterial(Long idMtfMaterial) {
        this.idMtfMaterial = idMtfMaterial;
    }
    public SMtfMaterial(Long idMtfMaterial, SBin SBinByToBin, SSo SSo, SPoMaterial SPoMaterial, SStatusDic SStatusDic, SMaterial SMaterial, PWoBom PWoBom, SMtf SMtf, SBin SBinByFromBin, Long qty, String lotNo, Long UQty, Long box) {
       this.idMtfMaterial = idMtfMaterial;
       this.SBinByToBin = SBinByToBin;
       this.SSo = SSo;
       this.SPoMaterial = SPoMaterial;
       this.SStatusDic = SStatusDic;
       this.SMaterial = SMaterial;
       this.PWoBom = PWoBom;
       this.SMtf = SMtf;
       this.SBinByFromBin = SBinByFromBin;
       this.qty = qty;
       this.lotNo = lotNo;
       this.UQty = UQty;
       this.box = box;
    }
   
     @Id 
    
    @Column(name="id_mtf_material", unique=true, nullable=false)
    public Long getIdMtfMaterial() {
        return this.idMtfMaterial;
    }
    
    public void setIdMtfMaterial(Long idMtfMaterial) {
        this.idMtfMaterial = idMtfMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="to_bin")
    public SBin getSBinByToBin() {
        return this.SBinByToBin;
    }
    
    public void setSBinByToBin(SBin SBinByToBin) {
        this.SBinByToBin = SBinByToBin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_so")
    public SSo getSSo() {
        return this.SSo;
    }
    
    public void setSSo(SSo SSo) {
        this.SSo = SSo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_po_material")
    public SPoMaterial getSPoMaterial() {
        return this.SPoMaterial;
    }
    
    public void setSPoMaterial(SPoMaterial SPoMaterial) {
        this.SPoMaterial = SPoMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inspection")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_material")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_wo_bom")
    public PWoBom getPWoBom() {
        return this.PWoBom;
    }
    
    public void setPWoBom(PWoBom PWoBom) {
        this.PWoBom = PWoBom;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mt")
    public SMtf getSMtf() {
        return this.SMtf;
    }
    
    public void setSMtf(SMtf SMtf) {
        this.SMtf = SMtf;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="from_bin")
    public SBin getSBinByFromBin() {
        return this.SBinByFromBin;
    }
    
    public void setSBinByFromBin(SBin SBinByFromBin) {
        this.SBinByFromBin = SBinByFromBin;
    }
    
    @Column(name="qty")
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    
    @Column(name="lot_no", length=32)
    public String getLotNo() {
        return this.lotNo;
    }
    
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo;
    }
    
    @Column(name="u_qty")
    public Long getUQty() {
        return this.UQty;
    }
    
    public void setUQty(Long UQty) {
        this.UQty = UQty;
    }
    
    @Column(name="box")
    public Long getBox() {
        return this.box;
    }
    
    public void setBox(Long box) {
        this.box = box;
    }




}


