package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SMtf generated by hbm2java
 */
@Entity
@Table(name="s_mtf"
    ,catalog="jms3"
)
public class SMtf  implements java.io.Serializable {


     private Long idMt;
     private Company company;
     private SBin SBinBySMtfIbfk3;
     private SBin SBinBySMtfIbfk2;
     private Users users;
     private String mtNo;
     private Date dateMt;
     private Set<SMtfMaterial> SMtfMaterials = new HashSet<SMtfMaterial>(0);

    public SMtf() {
    }

    public SMtf(Company company, SBin SBinBySMtfIbfk3, SBin SBinBySMtfIbfk2, Users users, String mtNo, Date dateMt, Set<SMtfMaterial> SMtfMaterials) {
       this.company = company;
       this.SBinBySMtfIbfk3 = SBinBySMtfIbfk3;
       this.SBinBySMtfIbfk2 = SBinBySMtfIbfk2;
       this.users = users;
       this.mtNo = mtNo;
       this.dateMt = dateMt;
       this.SMtfMaterials = SMtfMaterials;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_mt", unique=true, nullable=false)
    public Long getIdMt() {
        return this.idMt;
    }
    
    public void setIdMt(Long idMt) {
        this.idMt = idMt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="stk_to", referencedColumnName="id_stk"), 
        @JoinColumn(name="stk_bin_to", referencedColumnName="bin") } )
    public SBin getSBinBySMtfIbfk3() {
        return this.SBinBySMtfIbfk3;
    }
    
    public void setSBinBySMtfIbfk3(SBin SBinBySMtfIbfk3) {
        this.SBinBySMtfIbfk3 = SBinBySMtfIbfk3;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="stk_from", referencedColumnName="id_stk"), 
        @JoinColumn(name="stk_bin_from", referencedColumnName="bin") } )
    public SBin getSBinBySMtfIbfk2() {
        return this.SBinBySMtfIbfk2;
    }
    
    public void setSBinBySMtfIbfk2(SBin SBinBySMtfIbfk2) {
        this.SBinBySMtfIbfk2 = SBinBySMtfIbfk2;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_mt")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="mt_no", length=20)
    public String getMtNo() {
        return this.mtNo;
    }
    
    public void setMtNo(String mtNo) {
        this.mtNo = mtNo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_mt", length=10)
    public Date getDateMt() {
        return this.dateMt;
    }
    
    public void setDateMt(Date dateMt) {
        this.dateMt = dateMt;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SMtf")
    public Set<SMtfMaterial> getSMtfMaterials() {
        return this.SMtfMaterials;
    }
    
    public void setSMtfMaterials(Set<SMtfMaterial> SMtfMaterials) {
        this.SMtfMaterials = SMtfMaterials;
    }




}


