package com.jms.domain.db;
// Generated 2017-7-16 15:53:57 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SNomaterialReport generated by hbm2java
 */
@Entity
@Table(name="s_nomaterial_report"
    ,catalog="jms7"
)
public class SNomaterialReport  implements java.io.Serializable {


     private Long id;
     private Long idCompany;
     private Long idMat;
     private Long type;
     private Long qty;
     private Date proDate;
     private Date woFinishDate;
     private Long SQty;
     private Long status;
     private String PWNo;
     private Long woQty;
     private Long openWoQty;
     private String product;
     private String planNo;
     private Long openPpQty;
     
     private Long ppQty;
     private String invUnit;
     
     private String material;

    public SNomaterialReport() {
    }

    public SNomaterialReport(Long idCompany, Long idMat, Long type, Long qty, Date proDate, Date woFinishDate, Long SQty, Long status, String PWNo, Long woQty, Long openWoQty, String product, String planNo, Long openPpQty) {
       this.idCompany = idCompany;
       this.idMat = idMat;
       this.type = type;
       this.qty = qty;
       this.proDate = proDate;
       this.woFinishDate = woFinishDate;
       this.SQty = SQty;
       this.status = status;
       this.PWNo = PWNo;
       this.woQty = woQty;
       this.openWoQty = openWoQty;
       this.product = product;
       this.planNo = planNo;
       this.openPpQty = openPpQty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="id_company")
    public Long getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Long idCompany) {
        this.idCompany = idCompany;
    }
    
    @Column(name="id_mat")
    public Long getIdMat() {
        return this.idMat;
    }
    
    public void setIdMat(Long idMat) {
        this.idMat = idMat;
    }
    
    @Column(name="type")
    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    
    @Column(name="qty")
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pro_date", length=19)
    public Date getProDate() {
        return this.proDate;
    }
    
    public void setProDate(Date proDate) {
        this.proDate = proDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="wo_finish_date", length=19)
    public Date getWoFinishDate() {
        return this.woFinishDate;
    }
    
    public void setWoFinishDate(Date woFinishDate) {
        this.woFinishDate = woFinishDate;
    }
    
    @Column(name="s_qty")
    public Long getSQty() {
        return this.SQty;
    }
    
    public void setSQty(Long SQty) {
        this.SQty = SQty;
    }
    
    @Column(name="status")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    
    @Column(name="p_w_no", length=64)
    public String getPWNo() {
        return this.PWNo;
    }
    
    public void setPWNo(String PWNo) {
        this.PWNo = PWNo;
    }
    
    @Column(name="wo_qty")
    public Long getWoQty() {
        return this.woQty;
    }
    
    public void setWoQty(Long woQty) {
        this.woQty = woQty;
    }
    
    @Column(name="open_wo_qty")
    public Long getOpenWoQty() {
        return this.openWoQty;
    }
    
    public void setOpenWoQty(Long openWoQty) {
        this.openWoQty = openWoQty;
    }
    
    @Column(name="product", length=256)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    
    @Column(name="plan_no", length=64)
    public String getPlanNo() {
        return this.planNo;
    }
    
    public void setPlanNo(String planNo) {
        this.planNo = planNo;
    }
    
    @Column(name="open_pp_qty")
    public Long getOpenPpQty() {
        return this.openPpQty;
    }
    
    public void setOpenPpQty(Long openPpQty) {
        this.openPpQty = openPpQty;
    }

    @Column(name="inv_unit", length=64)
	public String getInvUnit() {
		return invUnit;
	}

	public void setInvUnit(String invUnit) {
		this.invUnit = invUnit;
	}

	  @Column(name="material",length=128)
	public String getMaterial() {
		return material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

    @Column(name="pp_qty")
	public Long getPpQty() {
		return ppQty;
	}

	public void setPpQty(Long ppQty) {
		this.ppQty = ppQty;
	}




}


