package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SPic generated by hbm2java
 */
@Entity
@Table(name="s_pic"
    ,catalog="jms3"
)
public class SPic  implements java.io.Serializable {


     private Long id;
     private Users users;
     private String orgFilename;
     private String filename;
     private String des;
     private Set<SMaterialCategoryPic> SMaterialCategoryPics = new HashSet<SMaterialCategoryPic>(0);
     private Set<SMaterialPic> SMaterialPics = new HashSet<SMaterialPic>(0);

    public SPic() {
    }

    public SPic(Users users, String orgFilename, String filename, String des, Set<SMaterialCategoryPic> SMaterialCategoryPics, Set<SMaterialPic> SMaterialPics) {
       this.users = users;
       this.orgFilename = orgFilename;
       this.filename = filename;
       this.des = des;
       this.SMaterialCategoryPics = SMaterialCategoryPics;
       this.SMaterialPics = SMaterialPics;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="upload_by")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="org_filename", length=256)
    public String getOrgFilename() {
        return this.orgFilename;
    }
    
    public void setOrgFilename(String orgFilename) {
        this.orgFilename = orgFilename;
    }
    
    @Column(name="filename", length=256)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SPic")
    public Set<SMaterialCategoryPic> getSMaterialCategoryPics() {
        return this.SMaterialCategoryPics;
    }
    
    public void setSMaterialCategoryPics(Set<SMaterialCategoryPic> SMaterialCategoryPics) {
        this.SMaterialCategoryPics = SMaterialCategoryPics;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SPic")
    public Set<SMaterialPic> getSMaterialPics() {
        return this.SMaterialPics;
    }
    
    public void setSMaterialPics(Set<SMaterialPic> SMaterialPics) {
        this.SMaterialPics = SMaterialPics;
    }




}


