package com.jms.domain.db;

// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SPo generated by hbm2java
 */
@Entity
@Table(name="s_po")
public class SPo  implements java.io.Serializable {

     private Long idPo;
     private Company company;
     private SCompanyCo SCompanyCo;
     private SStatusDic SStatusDic;
     private Users users;
     private SAttachment SAttachment;
     private SCurrencyType SCurrencyType;
     private SPoType SPoType;
     private STermDic STermDicByFreightTerm;
     private STermDic STermDicByPaymentTerm;
     private String codePo;
     private Date dateOrder;
     private Float totalAmount;
     private Float taxRate;
     private Float exchange;
     private String remark;
     private Set<SPoMaterial> SPoMaterials = new HashSet<SPoMaterial>(0);
     
     private Long idCompany1;  //往来公司
     private Long idCompany2;  //供应商
     private Long idSo;
     private String soNo;

    public SPo() { }

  
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_po", unique=true, nullable=false)
    public Long getIdPo() {
        return this.idPo;
    }
    
    public void setIdPo(Long idPo) {
        this.idPo = idPo;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_co")
    public SCompanyCo getSCompanyCo() {
        return this.SCompanyCo;
    }
    
    public void setSCompanyCo(SCompanyCo SCompanyCo) {
        this.SCompanyCo = SCompanyCo;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_order")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attachment")
    public SAttachment getSAttachment() {
        return this.SAttachment;
    }
    
    public void setSAttachment(SAttachment SAttachment) {
        this.SAttachment = SAttachment;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_currency_type")
    public SCurrencyType getSCurrencyType() {
        return this.SCurrencyType;
    }
    
    public void setSCurrencyType(SCurrencyType SCurrencyType) {
        this.SCurrencyType = SCurrencyType;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_po_type_dic")
    public SPoType getSPoType() {
        return this.SPoType;
    }
    
    public void setSPoType(SPoType SPoType) {
        this.SPoType = SPoType;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="freight_term")
    public STermDic getSTermDicByFreightTerm() {
        return this.STermDicByFreightTerm;
    }
    
    public void setSTermDicByFreightTerm(STermDic STermDicByFreightTerm) {
        this.STermDicByFreightTerm = STermDicByFreightTerm;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_term")
    public STermDic getSTermDicByPaymentTerm() {
        return this.STermDicByPaymentTerm;
    }
    
    public void setSTermDicByPaymentTerm(STermDic STermDicByPaymentTerm) {
        this.STermDicByPaymentTerm = STermDicByPaymentTerm;
    }
    
    @Column(name="code_po", length=64)
    public String getCodePo() {
        return this.codePo;
    }
    
    public void setCodePo(String codePo) {
        this.codePo = codePo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_order", length=10)
    public Date getDateOrder() {
        return this.dateOrder;
    }
    
    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }
    
    @Column(name="total_amount", precision=12)
    public Float getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Float totalAmount) {
        this.totalAmount = totalAmount;
    }
    

    @Column(name="tax_rate", precision=12, scale=0)
    public Float getTaxRate() {
        return this.taxRate;
    }
    
    public void setTaxRate(Float taxRate) {
        this.taxRate = taxRate;
    }
    
    @Column(name="exchange", precision=10, scale=0)
    public Float getExchange() {
        return this.exchange;
    }
    
    public void setExchange(Float exchange) {
        this.exchange = exchange;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SPo")
    public Set<SPoMaterial> getSPoMaterials() {
        return this.SPoMaterials;
    }
    
    public void setSPoMaterials(Set<SPoMaterial> SPoMaterials) {
        this.SPoMaterials = SPoMaterials;
    }
    
    @Column(name="id_company1")
	public Long getIdCompany1() {
		return idCompany1;
	}

	public void setIdCompany1(Long idCompany1) {
		this.idCompany1 = idCompany1;
	}
	 @Column(name="id_so")
	public Long getIdSo() {
		return idSo;
	}

	public void setIdSo(Long idSo) {
		this.idSo = idSo;
	}

	 @Column(name="so_no", length=64)
	public String getSoNo() {
		return soNo;
	}

	public void setSoNo(String soNo) {
		this.soNo = soNo;
	}

	 @Column(name="id_company2")
	public Long getIdCompany2() {
		return idCompany2;
	}


	public void setIdCompany2(Long idCompany2) {
		this.idCompany2 = idCompany2;
	}


}


