package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SPoMaterial generated by hbm2java
 */
@Entity
@Table(name="s_po_material"
    ,catalog="jms4"
)
public class SPoMaterial  implements java.io.Serializable {


     private Long idPoMaterial;
     private SStatusDic SStatusDic;
     private SPo SPo;
     private SMaterial SMaterial;
     private Long line;
     private Long qtyPo;
     private Long UPrice;
     private Long totalPrice;
     private String remark;
     private Date deliveryDate;
     private Long qtyReceived;
     private String autoRemark;
     private Set<QDimensionReport> QDimensionReports = new HashSet<QDimensionReport>(0);
     private Set<SMtfMaterial> SMtfMaterials = new HashSet<SMtfMaterial>(0);

    public SPoMaterial() {
    }

	
    public SPoMaterial(Long idPoMaterial) {
        this.idPoMaterial = idPoMaterial;
    }
    public SPoMaterial(Long idPoMaterial, SStatusDic SStatusDic, SPo SPo, SMaterial SMaterial, Long line, Long qtyPo, Long UPrice, Long totalPrice, String remark, Date deliveryDate, Long qtyReceived, String autoRemark, Set<QDimensionReport> QDimensionReports, Set<SMtfMaterial> SMtfMaterials) {
       this.idPoMaterial = idPoMaterial;
       this.SStatusDic = SStatusDic;
       this.SPo = SPo;
       this.SMaterial = SMaterial;
       this.line = line;
       this.qtyPo = qtyPo;
       this.UPrice = UPrice;
       this.totalPrice = totalPrice;
       this.remark = remark;
       this.deliveryDate = deliveryDate;
       this.qtyReceived = qtyReceived;
       this.autoRemark = autoRemark;
       this.QDimensionReports = QDimensionReports;
       this.SMtfMaterials = SMtfMaterials;
    }
   
     @Id 
    
    @Column(name="id_po_material", unique=true, nullable=false)
    public Long getIdPoMaterial() {
        return this.idPoMaterial;
    }
    
    public void setIdPoMaterial(Long idPoMaterial) {
        this.idPoMaterial = idPoMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_po")
    public SPo getSPo() {
        return this.SPo;
    }
    
    public void setSPo(SPo SPo) {
        this.SPo = SPo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pno")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
    
    @Column(name="line")
    public Long getLine() {
        return this.line;
    }
    
    public void setLine(Long line) {
        this.line = line;
    }
    
    @Column(name="qty_po", precision=10, scale=0)
    public Long getQtyPo() {
        return this.qtyPo;
    }
    
    public void setQtyPo(Long qtyPo) {
        this.qtyPo = qtyPo;
    }
    
    @Column(name="u_price", precision=10, scale=0)
    public Long getUPrice() {
        return this.UPrice;
    }
    
    public void setUPrice(Long UPrice) {
        this.UPrice = UPrice;
    }
    
    @Column(name="total_price", precision=10, scale=0)
    public Long getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="delivery_date", length=10)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    
    @Column(name="qty_received", precision=10, scale=0)
    public Long getQtyReceived() {
        return this.qtyReceived;
    }
    
    public void setQtyReceived(Long qtyReceived) {
        this.qtyReceived = qtyReceived;
    }
    
    @Column(name="auto_remark", length=1024)
    public String getAutoRemark() {
        return this.autoRemark;
    }
    
    public void setAutoRemark(String autoRemark) {
        this.autoRemark = autoRemark;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SPoMaterial")
    public Set<QDimensionReport> getQDimensionReports() {
        return this.QDimensionReports;
    }
    
    public void setQDimensionReports(Set<QDimensionReport> QDimensionReports) {
        this.QDimensionReports = QDimensionReports;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SPoMaterial")
    public Set<SMtfMaterial> getSMtfMaterials() {
        return this.SMtfMaterials;
    }
    
    public void setSMtfMaterials(Set<SMtfMaterial> SMtfMaterials) {
        this.SMtfMaterials = SMtfMaterials;
    }




}


