package com.jms.domain.db;
// Generated 2017-7-17 9:13:40 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SPoTemp generated by hbm2java
 */
@Entity
@Table(name="s_po_temp"
    ,catalog="jms7"
)
public class SPoTemp  implements java.io.Serializable {


     private Long id;
     private Long idMat;
     private Long idCompany;
     private String material;
     private Date RDate;
     private Long SQty;
     private String invUnit;
     private Long SPoQty;
     private Long APoQty;
     private Float UPrice;
     private Float AUPrice;
     private Float price;
     private Long ysDiff;
     private Float diff;
     private Long dura;
     private Date lateDate;
     private Date EDate;
     private Float CUPrice;
     private Float CPrice;
     private String purUnit;
     private Long mpq;
     private Long moq;
     private Long idComCo;
     private String comCo;
     private Float prec;
     private Long isPrim;
     private Long status;

    public SPoTemp() {
    }

    public SPoTemp(Long idMat, Long idCompany, String material, Date RDate, Long SQty, String invUnit, Long SPoQty, Long APoQty, Float UPrice, Float AUPrice, Float price, Long ysDiff, Float diff, Long dura, Date lateDate, Date EDate, Float CUPrice, Float CPrice, String purUnit, Long mpq, Long moq, Long idComCo, String comCo, Float prec, Long isPrim) {
       this.idMat = idMat;
       this.idCompany = idCompany;
       this.material = material;
       this.RDate = RDate;
       this.SQty = SQty;
       this.invUnit = invUnit;
       this.SPoQty = SPoQty;
       this.APoQty = APoQty;
       this.UPrice = UPrice;
       this.AUPrice = AUPrice;
       this.price = price;
       this.ysDiff = ysDiff;
       this.diff = diff;
       this.dura = dura;
       this.lateDate = lateDate;
       this.EDate = EDate;
       this.CUPrice = CUPrice;
       this.CPrice = CPrice;
       this.purUnit = purUnit;
       this.mpq = mpq;
       this.moq = moq;
       this.idComCo = idComCo;
       this.comCo = comCo;
       this.prec = prec;
       this.isPrim = isPrim;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="id_mat")
    public Long getIdMat() {
        return this.idMat;
    }
    
    public void setIdMat(Long idMat) {
        this.idMat = idMat;
    }
    
    @Column(name="id_company")
    public Long getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Long idCompany) {
        this.idCompany = idCompany;
    }
    
    @Column(name="material", length=128)
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="r_date", length=19)
    public Date getRDate() {
        return this.RDate;
    }
    
    public void setRDate(Date RDate) {
        this.RDate = RDate;
    }
    
    @Column(name="s_qty")
    public Long getSQty() {
        return this.SQty;
    }
    
    public void setSQty(Long SQty) {
        this.SQty = SQty;
    }
    
    @Column(name="inv_unit", length=64)
    public String getInvUnit() {
        return this.invUnit;
    }
    
    public void setInvUnit(String invUnit) {
        this.invUnit = invUnit;
    }
    
    @Column(name="s_po_qty")
    public Long getSPoQty() {
        return this.SPoQty;
    }
    
    public void setSPoQty(Long SPoQty) {
        this.SPoQty = SPoQty;
    }
    
    @Column(name="a_po_qty")
    public Long getAPoQty() {
        return this.APoQty;
    }
    
    public void setAPoQty(Long APoQty) {
        this.APoQty = APoQty;
    }
    
    @Column(name="u_price", precision=12, scale=0)
    public Float getUPrice() {
        return this.UPrice;
    }
    
    public void setUPrice(Float UPrice) {
        this.UPrice = UPrice;
    }
    
    @Column(name="a_u_price", precision=12, scale=0)
    public Float getAUPrice() {
        return this.AUPrice;
    }
    
    public void setAUPrice(Float AUPrice) {
        this.AUPrice = AUPrice;
    }
    
    @Column(name="price", precision=12, scale=0)
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    
    @Column(name="ys_diff")
    public Long getYsDiff() {
        return this.ysDiff;
    }
    
    public void setYsDiff(Long ysDiff) {
        this.ysDiff = ysDiff;
    }
    
    @Column(name="diff", precision=12, scale=0)
    public Float getDiff() {
        return this.diff;
    }
    
    public void setDiff(Float diff) {
        this.diff = diff;
    }
    
    @Column(name="dura")
    public Long getDura() {
        return this.dura;
    }
    
    public void setDura(Long dura) {
        this.dura = dura;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="late_date", length=19)
    public Date getLateDate() {
        return this.lateDate;
    }
    
    public void setLateDate(Date lateDate) {
        this.lateDate = lateDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="e_date", length=19)
    public Date getEDate() {
        return this.EDate;
    }
    
    public void setEDate(Date EDate) {
        this.EDate = EDate;
    }
    
    @Column(name="c_u_price", precision=12, scale=0)
    public Float getCUPrice() {
        return this.CUPrice;
    }
    
    public void setCUPrice(Float CUPrice) {
        this.CUPrice = CUPrice;
    }
    
    @Column(name="c_price", precision=12, scale=0)
    public Float getCPrice() {
        return this.CPrice;
    }
    
    public void setCPrice(Float CPrice) {
        this.CPrice = CPrice;
    }
    
    @Column(name="pur_unit", length=64)
    public String getPurUnit() {
        return this.purUnit;
    }
    
    public void setPurUnit(String purUnit) {
        this.purUnit = purUnit;
    }
    
    @Column(name="mpq")
    public Long getMpq() {
        return this.mpq;
    }
    
    public void setMpq(Long mpq) {
        this.mpq = mpq;
    }
    
    @Column(name="moq")
    public Long getMoq() {
        return this.moq;
    }
    
    public void setMoq(Long moq) {
        this.moq = moq;
    }
    
    @Column(name="id_com_co")
    public Long getIdComCo() {
        return this.idComCo;
    }
    
    public void setIdComCo(Long idComCo) {
        this.idComCo = idComCo;
    }
    
    @Column(name="com_co", length=128)
    public String getComCo() {
        return this.comCo;
    }
    
    public void setComCo(String comCo) {
        this.comCo = comCo;
    }
    
    @Column(name="prec", precision=12, scale=0)
    public Float getPrec() {
        return this.prec;
    }
    
    public void setPrec(Float prec) {
        this.prec = prec;
    }
    
    @Column(name="is_prim")
    public Long getIsPrim() {
        return this.isPrim;
    }
    
    public void setIsPrim(Long isPrim) {
        this.isPrim = isPrim;
    }

    @Column(name="status")
	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}




}


