package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SRmaMaterial generated by hbm2java
 */
@Entity
@Table(name="s_rma_material"
    ,catalog="jms3"
)
public class SRmaMaterial  implements java.io.Serializable {


     private Long id;
     private SStatusDic SStatusDic;
     private SRma SRma;
     private SMaterial SMaterial;
     private Long line;
     private String default_;
     private Long qty;
     private Long UPrice;
     private Long totalPrice;
     private String reamrk;
     private Date deliveryDate;
     private Long qtyDelivered;
     private Long qtyRejected;

    public SRmaMaterial() {
    }

    public SRmaMaterial(SStatusDic SStatusDic, SRma SRma, SMaterial SMaterial, Long line, String default_, Long qty, Long UPrice, Long totalPrice, String reamrk, Date deliveryDate, Long qtyDelivered, Long qtyRejected) {
       this.SStatusDic = SStatusDic;
       this.SRma = SRma;
       this.SMaterial = SMaterial;
       this.line = line;
       this.default_ = default_;
       this.qty = qty;
       this.UPrice = UPrice;
       this.totalPrice = totalPrice;
       this.reamrk = reamrk;
       this.deliveryDate = deliveryDate;
       this.qtyDelivered = qtyDelivered;
       this.qtyRejected = qtyRejected;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rma")
    public SRma getSRma() {
        return this.SRma;
    }
    
    public void setSRma(SRma SRma) {
        this.SRma = SRma;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pno")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
    
    @Column(name="line")
    public Long getLine() {
        return this.line;
    }
    
    public void setLine(Long line) {
        this.line = line;
    }
    
    @Column(name="_default_", length=18)
    public String getDefault_() {
        return this.default_;
    }
    
    public void setDefault_(String default_) {
        this.default_ = default_;
    }
    
    @Column(name="qty", precision=10, scale=0)
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    
    @Column(name="u_price", precision=10, scale=0)
    public Long getUPrice() {
        return this.UPrice;
    }
    
    public void setUPrice(Long UPrice) {
        this.UPrice = UPrice;
    }
    
    @Column(name="total_price", precision=10, scale=0)
    public Long getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    @Column(name="reamrk", length=1024)
    public String getReamrk() {
        return this.reamrk;
    }
    
    public void setReamrk(String reamrk) {
        this.reamrk = reamrk;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="delivery_date", length=10)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    
    @Column(name="qty_delivered", precision=10, scale=0)
    public Long getQtyDelivered() {
        return this.qtyDelivered;
    }
    
    public void setQtyDelivered(Long qtyDelivered) {
        this.qtyDelivered = qtyDelivered;
    }
    
    @Column(name="qty_rejected", precision=10, scale=0)
    public Long getQtyRejected() {
        return this.qtyRejected;
    }
    
    public void setQtyRejected(Long qtyRejected) {
        this.qtyRejected = qtyRejected;
    }




}


