package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SRma generated by hbm2java
 */
@Entity
@Table(name="s_rma"
    ,catalog="jms3"
)
public class SRma  implements java.io.Serializable {


     private Long idRma;
     private SStk SStk;
     private Company company;
     private SCompanyCo SCompanyCo;
     private SStatusDic SStatusDic;
     private Users users;
     private SAttachment SAttachment;
     private STermDic STermDicByFreightTerm;
     private STermDic STermDicByPaymentTerm;
     private String codeRma;
     private Date dateOrder;
     private Long totalAmount;
     private Long taxRate;
     private Long exchange;
     private String remark;
     private Set<SRmaMaterial> SRmaMaterials = new HashSet<SRmaMaterial>(0);

    public SRma() {
    }

    public SRma(SStk SStk, Company company, SCompanyCo SCompanyCo, SStatusDic SStatusDic, Users users, SAttachment SAttachment, STermDic STermDicByFreightTerm, STermDic STermDicByPaymentTerm, String codeRma, Date dateOrder, Long totalAmount, Long taxRate, Long exchange, String remark, Set<SRmaMaterial> SRmaMaterials) {
       this.SStk = SStk;
       this.company = company;
       this.SCompanyCo = SCompanyCo;
       this.SStatusDic = SStatusDic;
       this.users = users;
       this.SAttachment = SAttachment;
       this.STermDicByFreightTerm = STermDicByFreightTerm;
       this.STermDicByPaymentTerm = STermDicByPaymentTerm;
       this.codeRma = codeRma;
       this.dateOrder = dateOrder;
       this.totalAmount = totalAmount;
       this.taxRate = taxRate;
       this.exchange = exchange;
       this.remark = remark;
       this.SRmaMaterials = SRmaMaterials;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_rma", unique=true, nullable=false)
    public Long getIdRma() {
        return this.idRma;
    }
    
    public void setIdRma(Long idRma) {
        this.idRma = idRma;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stk")
    public SStk getSStk() {
        return this.SStk;
    }
    
    public void setSStk(SStk SStk) {
        this.SStk = SStk;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_co")
    public SCompanyCo getSCompanyCo() {
        return this.SCompanyCo;
    }
    
    public void setSCompanyCo(SCompanyCo SCompanyCo) {
        this.SCompanyCo = SCompanyCo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_oeder")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attachment")
    public SAttachment getSAttachment() {
        return this.SAttachment;
    }
    
    public void setSAttachment(SAttachment SAttachment) {
        this.SAttachment = SAttachment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="freight_term")
    public STermDic getSTermDicByFreightTerm() {
        return this.STermDicByFreightTerm;
    }
    
    public void setSTermDicByFreightTerm(STermDic STermDicByFreightTerm) {
        this.STermDicByFreightTerm = STermDicByFreightTerm;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_term")
    public STermDic getSTermDicByPaymentTerm() {
        return this.STermDicByPaymentTerm;
    }
    
    public void setSTermDicByPaymentTerm(STermDic STermDicByPaymentTerm) {
        this.STermDicByPaymentTerm = STermDicByPaymentTerm;
    }
    
    @Column(name="code_rma", length=64)
    public String getCodeRma() {
        return this.codeRma;
    }
    
    public void setCodeRma(String codeRma) {
        this.codeRma = codeRma;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_order", length=10)
    public Date getDateOrder() {
        return this.dateOrder;
    }
    
    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }
    
    @Column(name="total_amount", precision=10, scale=0)
    public Long getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }
    
    @Column(name="tax_rate", precision=10, scale=0)
    public Long getTaxRate() {
        return this.taxRate;
    }
    
    public void setTaxRate(Long taxRate) {
        this.taxRate = taxRate;
    }
    
    @Column(name="exchange", precision=10, scale=0)
    public Long getExchange() {
        return this.exchange;
    }
    
    public void setExchange(Long exchange) {
        this.exchange = exchange;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SRma")
    public Set<SRmaMaterial> getSRmaMaterials() {
        return this.SRmaMaterials;
    }
    
    public void setSRmaMaterials(Set<SRmaMaterial> SRmaMaterials) {
        this.SRmaMaterials = SRmaMaterials;
    }




}


