package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SSo generated by hbm2java
 */
@Entity
@Table(name="s_so"
    ,catalog="jms3"
)
public class SSo  implements java.io.Serializable {


     private Long idSo;
     private SStk SStk;
     private Company company;
     private SCompanyCo SCompanyCo;
     private SStatusDic SStatusDic;
     private Users users;
     private SAttachment SAttachment;
     private STermDic STermDicByPaymentTerm;
     private STermDic STermDicByFreightTerm;
     private String codeSo;
     private Date dateOrder;
     private Long totalAmount;
     private Long taxRate;
     private Long exchange;
     private String remark;
     private Set<SDo> SDos = new HashSet<SDo>(0);
     private Set<SSoMaterial> SSoMaterials = new HashSet<SSoMaterial>(0);

    public SSo() {
    }

    public SSo(SStk SStk, Company company, SCompanyCo SCompanyCo, SStatusDic SStatusDic, Users users, SAttachment SAttachment, STermDic STermDicByPaymentTerm, STermDic STermDicByFreightTerm, String codeSo, Date dateOrder, Long totalAmount, Long taxRate, Long exchange, String remark, Set<SDo> SDos, Set<SSoMaterial> SSoMaterials) {
       this.SStk = SStk;
       this.company = company;
       this.SCompanyCo = SCompanyCo;
       this.SStatusDic = SStatusDic;
       this.users = users;
       this.SAttachment = SAttachment;
       this.STermDicByPaymentTerm = STermDicByPaymentTerm;
       this.STermDicByFreightTerm = STermDicByFreightTerm;
       this.codeSo = codeSo;
       this.dateOrder = dateOrder;
       this.totalAmount = totalAmount;
       this.taxRate = taxRate;
       this.exchange = exchange;
       this.remark = remark;
       this.SDos = SDos;
       this.SSoMaterials = SSoMaterials;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_so", unique=true, nullable=false)
    public Long getIdSo() {
        return this.idSo;
    }
    
    public void setIdSo(Long idSo) {
        this.idSo = idSo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stk")
    public SStk getSStk() {
        return this.SStk;
    }
    
    public void setSStk(SStk SStk) {
        this.SStk = SStk;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_co")
    public SCompanyCo getSCompanyCo() {
        return this.SCompanyCo;
    }
    
    public void setSCompanyCo(SCompanyCo SCompanyCo) {
        this.SCompanyCo = SCompanyCo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_order")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attachment")
    public SAttachment getSAttachment() {
        return this.SAttachment;
    }
    
    public void setSAttachment(SAttachment SAttachment) {
        this.SAttachment = SAttachment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_term")
    public STermDic getSTermDicByPaymentTerm() {
        return this.STermDicByPaymentTerm;
    }
    
    public void setSTermDicByPaymentTerm(STermDic STermDicByPaymentTerm) {
        this.STermDicByPaymentTerm = STermDicByPaymentTerm;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="freight_term")
    public STermDic getSTermDicByFreightTerm() {
        return this.STermDicByFreightTerm;
    }
    
    public void setSTermDicByFreightTerm(STermDic STermDicByFreightTerm) {
        this.STermDicByFreightTerm = STermDicByFreightTerm;
    }
    
    @Column(name="code_so", length=64)
    public String getCodeSo() {
        return this.codeSo;
    }
    
    public void setCodeSo(String codeSo) {
        this.codeSo = codeSo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_order", length=10)
    public Date getDateOrder() {
        return this.dateOrder;
    }
    
    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }
    
    @Column(name="total_amount", precision=10, scale=0)
    public Long getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }
    
    @Column(name="tax_rate", precision=10, scale=0)
    public Long getTaxRate() {
        return this.taxRate;
    }
    
    public void setTaxRate(Long taxRate) {
        this.taxRate = taxRate;
    }
    
    @Column(name="exchange", precision=10, scale=0)
    public Long getExchange() {
        return this.exchange;
    }
    
    public void setExchange(Long exchange) {
        this.exchange = exchange;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SSo")
    public Set<SDo> getSDos() {
        return this.SDos;
    }
    
    public void setSDos(Set<SDo> SDos) {
        this.SDos = SDos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SSo")
    public Set<SSoMaterial> getSSoMaterials() {
        return this.SSoMaterials;
    }
    
    public void setSSoMaterials(Set<SSoMaterial> SSoMaterials) {
        this.SSoMaterials = SSoMaterials;
    }




}


