package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SSoMaterial generated by hbm2java
 */
@Entity
@Table(name="s_so_material"
    ,catalog="jms3"
)
public class SSoMaterial  implements java.io.Serializable {


     private Long id;
     private SMaterial SMaterial;
     private SSo SSo;
     private SStatusDic SStatusDic;
     private Long line;
     private Long qty;
     private Long UPrice;
     private Long totalPrice;
     private String remark;
     private Date dateDelivery;
     private Long qtyDelivery;

    public SSoMaterial() {
    }

    public SSoMaterial(SMaterial SMaterial, SSo SSo, SStatusDic SStatusDic, Long line, Long qty, Long UPrice, Long totalPrice, String remark, Date dateDelivery, Long qtyDelivery) {
       this.SMaterial = SMaterial;
       this.SSo = SSo;
       this.SStatusDic = SStatusDic;
       this.line = line;
       this.qty = qty;
       this.UPrice = UPrice;
       this.totalPrice = totalPrice;
       this.remark = remark;
       this.dateDelivery = dateDelivery;
       this.qtyDelivery = qtyDelivery;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="material")
    public SMaterial getSMaterial() {
        return this.SMaterial;
    }
    
    public void setSMaterial(SMaterial SMaterial) {
        this.SMaterial = SMaterial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_so")
    public SSo getSSo() {
        return this.SSo;
    }
    
    public void setSSo(SSo SSo) {
        this.SSo = SSo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
    
    @Column(name="line")
    public Long getLine() {
        return this.line;
    }
    
    public void setLine(Long line) {
        this.line = line;
    }
    
    @Column(name="qty", precision=10, scale=0)
    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }
    
    @Column(name="u_price", precision=10, scale=0)
    public Long getUPrice() {
        return this.UPrice;
    }
    
    public void setUPrice(Long UPrice) {
        this.UPrice = UPrice;
    }
    
    @Column(name="total_price", precision=10, scale=0)
    public Long getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    @Column(name="remark", length=1024)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_delivery", length=10)
    public Date getDateDelivery() {
        return this.dateDelivery;
    }
    
    public void setDateDelivery(Date dateDelivery) {
        this.dateDelivery = dateDelivery;
    }
    
    @Column(name="qty_delivery", precision=10, scale=0)
    public Long getQtyDelivery() {
        return this.qtyDelivery;
    }
    
    public void setQtyDelivery(Long qtyDelivery) {
        this.qtyDelivery = qtyDelivery;
    }




}


