package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SStatusDic generated by hbm2java
 */
@Entity
@Table(name="s_status_dic"
    ,catalog="jms4"
)
public class SStatusDic  implements java.io.Serializable {


     private Long id;
     private String name;
     private String des;
     private String source;
     private Set<SMaterial> SMaterials = new HashSet<SMaterial>(0);
     private Set<SMaterialCategory> SMaterialCategories = new HashSet<SMaterialCategory>(0);
     private Set<SMtfMaterial> SMtfMaterials = new HashSet<SMtfMaterial>(0);
     private Set<SPo> SPos = new HashSet<SPo>(0);
     private Set<SCompanyCo> SCompanyCos = new HashSet<SCompanyCo>(0);
     private Set<SSo> SSos = new HashSet<SSo>(0);
     private Set<SBin> SBins = new HashSet<SBin>(0);
     private Set<SStk> SStks = new HashSet<SStk>(0);
     private Set<SMtf> SMtfs = new HashSet<SMtf>(0);
     private Set<SPoMaterial> SPoMaterials = new HashSet<SPoMaterial>(0);
     private Set<SLinkman> SLinkmans = new HashSet<SLinkman>(0);

    public SStatusDic() {
    }

	
    public SStatusDic(Long id) {
        this.id = id;
    }
    public SStatusDic(Long id, String name, String des, String source, Set<SMaterial> SMaterials, Set<SMaterialCategory> SMaterialCategories, Set<SMtfMaterial> SMtfMaterials, Set<SPo> SPos, Set<SCompanyCo> SCompanyCos, Set<SSo> SSos, Set<SBin> SBins, Set<SStk> SStks, Set<SMtf> SMtfs, Set<SPoMaterial> SPoMaterials, Set<SLinkman> SLinkmans) {
       this.id = id;
       this.name = name;
       this.des = des;
       this.source = source;
       this.SMaterials = SMaterials;
       this.SMaterialCategories = SMaterialCategories;
       this.SMtfMaterials = SMtfMaterials;
       this.SPos = SPos;
       this.SCompanyCos = SCompanyCos;
       this.SSos = SSos;
       this.SBins = SBins;
       this.SStks = SStks;
       this.SMtfs = SMtfs;
       this.SPoMaterials = SPoMaterials;
       this.SLinkmans = SLinkmans;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="source", length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SMaterial> getSMaterials() {
        return this.SMaterials;
    }
    
    public void setSMaterials(Set<SMaterial> SMaterials) {
        this.SMaterials = SMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SMaterialCategory> getSMaterialCategories() {
        return this.SMaterialCategories;
    }
    
    public void setSMaterialCategories(Set<SMaterialCategory> SMaterialCategories) {
        this.SMaterialCategories = SMaterialCategories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SMtfMaterial> getSMtfMaterials() {
        return this.SMtfMaterials;
    }
    
    public void setSMtfMaterials(Set<SMtfMaterial> SMtfMaterials) {
        this.SMtfMaterials = SMtfMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SPo> getSPos() {
        return this.SPos;
    }
    
    public void setSPos(Set<SPo> SPos) {
        this.SPos = SPos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SCompanyCo> getSCompanyCos() {
        return this.SCompanyCos;
    }
    
    public void setSCompanyCos(Set<SCompanyCo> SCompanyCos) {
        this.SCompanyCos = SCompanyCos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SSo> getSSos() {
        return this.SSos;
    }
    
    public void setSSos(Set<SSo> SSos) {
        this.SSos = SSos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SBin> getSBins() {
        return this.SBins;
    }
    
    public void setSBins(Set<SBin> SBins) {
        this.SBins = SBins;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SStk> getSStks() {
        return this.SStks;
    }
    
    public void setSStks(Set<SStk> SStks) {
        this.SStks = SStks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SMtf> getSMtfs() {
        return this.SMtfs;
    }
    
    public void setSMtfs(Set<SMtf> SMtfs) {
        this.SMtfs = SMtfs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SPoMaterial> getSPoMaterials() {
        return this.SPoMaterials;
    }
    
    public void setSPoMaterials(Set<SPoMaterial> SPoMaterials) {
        this.SPoMaterials = SPoMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStatusDic")
    public Set<SLinkman> getSLinkmans() {
        return this.SLinkmans;
    }
    
    public void setSLinkmans(Set<SLinkman> SLinkmans) {
        this.SLinkmans = SLinkmans;
    }




}


