package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SStk generated by hbm2java
 */
@Entity
@Table(name="s_stk"
    ,catalog="jms3"
)
public class SStk  implements java.io.Serializable {


     private Long id;
     private Company company;
     private SStatusDic SStatusDic;
     private Users users;
     private String name;
     private String des;
     private String address;
     private String operator;
     private Date creationTime;
     private Set<SDoMaterial> SDoMaterials = new HashSet<SDoMaterial>(0);
     private Set<SPo> SPos = new HashSet<SPo>(0);
     private Set<SIncomeMaterial> SIncomeMaterials = new HashSet<SIncomeMaterial>(0);
     private Set<SSo> SSos = new HashSet<SSo>(0);
     private Set<SBin> SBins = new HashSet<SBin>(0);
     private Set<SMrb> SMrbs = new HashSet<SMrb>(0);
     private Set<SRma> SRmas = new HashSet<SRma>(0);

    public SStk() {
    }

    public SStk(Company company, SStatusDic SStatusDic, Users users, String name, String des, String address, String operator, Date creationTime, Set<SDoMaterial> SDoMaterials, Set<SPo> SPos, Set<SIncomeMaterial> SIncomeMaterials, Set<SSo> SSos, Set<SBin> SBins, Set<SMrb> SMrbs, Set<SRma> SRmas) {
       this.company = company;
       this.SStatusDic = SStatusDic;
       this.users = users;
       this.name = name;
       this.des = des;
       this.address = address;
       this.operator = operator;
       this.creationTime = creationTime;
       this.SDoMaterials = SDoMaterials;
       this.SPos = SPos;
       this.SIncomeMaterials = SIncomeMaterials;
       this.SSos = SSos;
       this.SBins = SBins;
       this.SMrbs = SMrbs;
       this.SRmas = SRmas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="address", length=256)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="operator", length=64)
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SDoMaterial> getSDoMaterials() {
        return this.SDoMaterials;
    }
    
    public void setSDoMaterials(Set<SDoMaterial> SDoMaterials) {
        this.SDoMaterials = SDoMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SPo> getSPos() {
        return this.SPos;
    }
    
    public void setSPos(Set<SPo> SPos) {
        this.SPos = SPos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SIncomeMaterial> getSIncomeMaterials() {
        return this.SIncomeMaterials;
    }
    
    public void setSIncomeMaterials(Set<SIncomeMaterial> SIncomeMaterials) {
        this.SIncomeMaterials = SIncomeMaterials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SSo> getSSos() {
        return this.SSos;
    }
    
    public void setSSos(Set<SSo> SSos) {
        this.SSos = SSos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SBin> getSBins() {
        return this.SBins;
    }
    
    public void setSBins(Set<SBin> SBins) {
        this.SBins = SBins;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SMrb> getSMrbs() {
        return this.SMrbs;
    }
    
    public void setSMrbs(Set<SMrb> SMrbs) {
        this.SMrbs = SMrbs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SRma> getSRmas() {
        return this.SRmas;
    }
    
    public void setSRmas(Set<SRma> SRmas) {
        this.SRmas = SRmas;
    }




}


