package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SStk generated by hbm2java
 */
@Entity
@Table(name="s_stk"
)
public class SStk  implements java.io.Serializable {


     private Long id;
     private Company company;
     private SStatusDic SStatusDic;
     private Users users;
     private SStkTypeDic SStkTypeDic;
     private String stkName;
     private String des;
     private String address;
     private String manager;
     private Set<SMtf> SMtfsForToStk = new HashSet<SMtf>(0);
     private Set<SBin> SBins = new HashSet<SBin>(0);
     private Set<SMtf> SMtfsForFromStk = new HashSet<SMtf>(0);

    public SStk() {
    }

    public SStk(Company company, SStatusDic SStatusDic, Users users, SStkTypeDic SStkTypeDic, String stkName, String des, String address, String manager, Set<SMtf> SMtfsForToStk, Set<SBin> SBins, Set<SMtf> SMtfsForFromStk) {
       this.company = company;
       this.SStatusDic = SStatusDic;
       this.users = users;
       this.SStkTypeDic = SStkTypeDic;
       this.stkName = stkName;
       this.des = des;
       this.address = address;
       this.manager = manager;
       this.SMtfsForToStk = SMtfsForToStk;
       this.SBins = SBins;
       this.SMtfsForFromStk = SMtfsForFromStk;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SStatusDic getSStatusDic() {
        return this.SStatusDic;
    }
    
    public void setSStatusDic(SStatusDic SStatusDic) {
        this.SStatusDic = SStatusDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_stk_type")
    public SStkTypeDic getSStkTypeDic() {
        return this.SStkTypeDic;
    }
    
    public void setSStkTypeDic(SStkTypeDic SStkTypeDic) {
        this.SStkTypeDic = SStkTypeDic;
    }
    
    @Column(name="stk_name", length=64)
    public String getStkName() {
        return this.stkName;
    }
    
    public void setStkName(String stkName) {
        this.stkName = stkName;
    }
    
    @Column(name="des", length=1024)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="address", length=256)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="manager", length=20)
    public String getManager() {
        return this.manager;
    }
    
    public void setManager(String manager) {
        this.manager = manager;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStkByToStk")
    public Set<SMtf> getSMtfsForToStk() {
        return this.SMtfsForToStk;
    }
    
    public void setSMtfsForToStk(Set<SMtf> SMtfsForToStk) {
        this.SMtfsForToStk = SMtfsForToStk;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStk")
    public Set<SBin> getSBins() {
        return this.SBins;
    }
    
    public void setSBins(Set<SBin> SBins) {
        this.SBins = SBins;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="SStkByFromStk")
    public Set<SMtf> getSMtfsForFromStk() {
        return this.SMtfsForFromStk;
    }
    
    public void setSMtfsForFromStk(Set<SMtf> SMtfsForFromStk) {
        this.SMtfsForFromStk = SMtfsForFromStk;
    }




}


