package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * STermDic generated by hbm2java
 */
@Entity
@Table(name="s_term_dic"
    ,catalog="jms4"
)
public class STermDic  implements java.io.Serializable {


     private Long id;
     private String name;
     private String des;
     private String source;
     private Set<SSo> SSosForPaymentTerm = new HashSet<SSo>(0);
     private Set<SSo> SSosForFreightTerm = new HashSet<SSo>(0);
     private Set<SCompanyCo> SCompanyCosForFreightTerm = new HashSet<SCompanyCo>(0);
     private Set<SCompanyCo> SCompanyCosForPaymentTerm = new HashSet<SCompanyCo>(0);
     private Set<SPo> SPosForPaymentTerm = new HashSet<SPo>(0);
     private Set<SPo> SPosForFreightTerm = new HashSet<SPo>(0);

    public STermDic() {
    }

	
    public STermDic(Long id) {
        this.id = id;
    }
    public STermDic(Long id, String name, String des, String source, Set<SSo> SSosForPaymentTerm, Set<SSo> SSosForFreightTerm, Set<SCompanyCo> SCompanyCosForFreightTerm, Set<SCompanyCo> SCompanyCosForPaymentTerm, Set<SPo> SPosForPaymentTerm, Set<SPo> SPosForFreightTerm) {
       this.id = id;
       this.name = name;
       this.des = des;
       this.source = source;
       this.SSosForPaymentTerm = SSosForPaymentTerm;
       this.SSosForFreightTerm = SSosForFreightTerm;
       this.SCompanyCosForFreightTerm = SCompanyCosForFreightTerm;
       this.SCompanyCosForPaymentTerm = SCompanyCosForPaymentTerm;
       this.SPosForPaymentTerm = SPosForPaymentTerm;
       this.SPosForFreightTerm = SPosForFreightTerm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=64)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="source", length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SSo> getSSosForPaymentTerm() {
        return this.SSosForPaymentTerm;
    }
    
    public void setSSosForPaymentTerm(Set<SSo> SSosForPaymentTerm) {
        this.SSosForPaymentTerm = SSosForPaymentTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SSo> getSSosForFreightTerm() {
        return this.SSosForFreightTerm;
    }
    
    public void setSSosForFreightTerm(Set<SSo> SSosForFreightTerm) {
        this.SSosForFreightTerm = SSosForFreightTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SCompanyCo> getSCompanyCosForFreightTerm() {
        return this.SCompanyCosForFreightTerm;
    }
    
    public void setSCompanyCosForFreightTerm(Set<SCompanyCo> SCompanyCosForFreightTerm) {
        this.SCompanyCosForFreightTerm = SCompanyCosForFreightTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SCompanyCo> getSCompanyCosForPaymentTerm() {
        return this.SCompanyCosForPaymentTerm;
    }
    
    public void setSCompanyCosForPaymentTerm(Set<SCompanyCo> SCompanyCosForPaymentTerm) {
        this.SCompanyCosForPaymentTerm = SCompanyCosForPaymentTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SPo> getSPosForPaymentTerm() {
        return this.SPosForPaymentTerm;
    }
    
    public void setSPosForPaymentTerm(Set<SPo> SPosForPaymentTerm) {
        this.SPosForPaymentTerm = SPosForPaymentTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SPo> getSPosForFreightTerm() {
        return this.SPosForFreightTerm;
    }
    
    public void setSPosForFreightTerm(Set<SPo> SPosForFreightTerm) {
        this.SPosForFreightTerm = SPosForFreightTerm;
    }




}


