package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * STermDic generated by hbm2java
 */
@Entity
@Table(name="s_term_dic"
    ,catalog="jms3"
)
public class STermDic  implements java.io.Serializable {


     private Long id;
     private String name;
     private String des;
     private String source;
     private Set<SRma> SRmasForFreightTerm = new HashSet<SRma>(0);
     private Set<SSo> SSosForPaymentTerm = new HashSet<SSo>(0);
     private Set<SSo> SSosForFreightTerm = new HashSet<SSo>(0);
     private Set<SCompanyCo> SCompanyCosForFreightTerm = new HashSet<SCompanyCo>(0);
     private Set<SCompanyCo> SCompanyCosForPaymentTerm = new HashSet<SCompanyCo>(0);
     private Set<SPo> SPosForFreightTerm = new HashSet<SPo>(0);
     private Set<SPo> SPosForPaymentTerm = new HashSet<SPo>(0);
     private Set<SMrb> SMrbsForPaymentTerm = new HashSet<SMrb>(0);
     private Set<SMrb> SMrbsForFreightTerm = new HashSet<SMrb>(0);
     private Set<SRma> SRmasForPaymentTerm = new HashSet<SRma>(0);

    public STermDic() {
    }

    public STermDic(String name, String des, String source, Set<SRma> SRmasForFreightTerm, Set<SSo> SSosForPaymentTerm, Set<SSo> SSosForFreightTerm, Set<SCompanyCo> SCompanyCosForFreightTerm, Set<SCompanyCo> SCompanyCosForPaymentTerm, Set<SPo> SPosForFreightTerm, Set<SPo> SPosForPaymentTerm, Set<SMrb> SMrbsForPaymentTerm, Set<SMrb> SMrbsForFreightTerm, Set<SRma> SRmasForPaymentTerm) {
       this.name = name;
       this.des = des;
       this.source = source;
       this.SRmasForFreightTerm = SRmasForFreightTerm;
       this.SSosForPaymentTerm = SSosForPaymentTerm;
       this.SSosForFreightTerm = SSosForFreightTerm;
       this.SCompanyCosForFreightTerm = SCompanyCosForFreightTerm;
       this.SCompanyCosForPaymentTerm = SCompanyCosForPaymentTerm;
       this.SPosForFreightTerm = SPosForFreightTerm;
       this.SPosForPaymentTerm = SPosForPaymentTerm;
       this.SMrbsForPaymentTerm = SMrbsForPaymentTerm;
       this.SMrbsForFreightTerm = SMrbsForFreightTerm;
       this.SRmasForPaymentTerm = SRmasForPaymentTerm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="des", length=64)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    
    @Column(name="source", length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SRma> getSRmasForFreightTerm() {
        return this.SRmasForFreightTerm;
    }
    
    public void setSRmasForFreightTerm(Set<SRma> SRmasForFreightTerm) {
        this.SRmasForFreightTerm = SRmasForFreightTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SSo> getSSosForPaymentTerm() {
        return this.SSosForPaymentTerm;
    }
    
    public void setSSosForPaymentTerm(Set<SSo> SSosForPaymentTerm) {
        this.SSosForPaymentTerm = SSosForPaymentTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SSo> getSSosForFreightTerm() {
        return this.SSosForFreightTerm;
    }
    
    public void setSSosForFreightTerm(Set<SSo> SSosForFreightTerm) {
        this.SSosForFreightTerm = SSosForFreightTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SCompanyCo> getSCompanyCosForFreightTerm() {
        return this.SCompanyCosForFreightTerm;
    }
    
    public void setSCompanyCosForFreightTerm(Set<SCompanyCo> SCompanyCosForFreightTerm) {
        this.SCompanyCosForFreightTerm = SCompanyCosForFreightTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SCompanyCo> getSCompanyCosForPaymentTerm() {
        return this.SCompanyCosForPaymentTerm;
    }
    
    public void setSCompanyCosForPaymentTerm(Set<SCompanyCo> SCompanyCosForPaymentTerm) {
        this.SCompanyCosForPaymentTerm = SCompanyCosForPaymentTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SPo> getSPosForFreightTerm() {
        return this.SPosForFreightTerm;
    }
    
    public void setSPosForFreightTerm(Set<SPo> SPosForFreightTerm) {
        this.SPosForFreightTerm = SPosForFreightTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SPo> getSPosForPaymentTerm() {
        return this.SPosForPaymentTerm;
    }
    
    public void setSPosForPaymentTerm(Set<SPo> SPosForPaymentTerm) {
        this.SPosForPaymentTerm = SPosForPaymentTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SMrb> getSMrbsForPaymentTerm() {
        return this.SMrbsForPaymentTerm;
    }
    
    public void setSMrbsForPaymentTerm(Set<SMrb> SMrbsForPaymentTerm) {
        this.SMrbsForPaymentTerm = SMrbsForPaymentTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByFreightTerm")
    public Set<SMrb> getSMrbsForFreightTerm() {
        return this.SMrbsForFreightTerm;
    }
    
    public void setSMrbsForFreightTerm(Set<SMrb> SMrbsForFreightTerm) {
        this.SMrbsForFreightTerm = SMrbsForFreightTerm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STermDicByPaymentTerm")
    public Set<SRma> getSRmasForPaymentTerm() {
        return this.SRmasForPaymentTerm;
    }
    
    public void setSRmasForPaymentTerm(Set<SRma> SRmasForPaymentTerm) {
        this.SRmasForPaymentTerm = SRmasForPaymentTerm;
    }




}


