package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * STypeDic generated by hbm2java
 */
@Entity
@Table(name="s_type_dic"
    ,catalog="jms4"
)
public class STypeDic  implements java.io.Serializable {


     private Long id;
     private String name;
     private Set<SCompanyCo> SCompanyCos = new HashSet<SCompanyCo>(0);

    public STypeDic() {
    }

	
    public STypeDic(Long id) {
        this.id = id;
    }
    public STypeDic(Long id, String name, Set<SCompanyCo> SCompanyCos) {
       this.id = id;
       this.name = name;
       this.SCompanyCos = SCompanyCos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="STypeDic")
    public Set<SCompanyCo> getSCompanyCos() {
        return this.SCompanyCos;
    }
    
    public void setSCompanyCos(Set<SCompanyCo> SCompanyCos) {
        this.SCompanyCos = SCompanyCos;
    }




}


