package com.jms.domain.db;
// Generated 2015-5-31 12:27:01 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysDicD generated by hbm2java
 */
@Entity
@Table(name="sys_dic_d"
    ,catalog="jms"
)
public class SysDicD  implements java.io.Serializable {


     private int idDic;
     private SysDic sysDic;
     private String name;
     private int enabled;
     private String description;
     private Set<Company> companiesForCompanyType = new HashSet<Company>(0);
     private Set<Company> companiesForCompanySize = new HashSet<Company>(0);

    public SysDicD() {
    }

	
    public SysDicD(int idDic, String name, int enabled, String description) {
        this.idDic = idDic;
        this.name = name;
        this.enabled = enabled;
        this.description = description;
    }
    public SysDicD(int idDic, SysDic sysDic, String name, int enabled, String description, Set<Company> companiesForCompanyType, Set<Company> companiesForCompanySize) {
       this.idDic = idDic;
       this.sysDic = sysDic;
       this.name = name;
       this.enabled = enabled;
       this.description = description;
       this.companiesForCompanyType = companiesForCompanyType;
       this.companiesForCompanySize = companiesForCompanySize;
    }
   
     @Id 
    
    @Column(name="ID_DIC", unique=true, nullable=false)
    public int getIdDic() {
        return this.idDic;
    }
    
    public void setIdDic(int idDic) {
        this.idDic = idDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE")
    public SysDic getSysDic() {
        return this.sysDic;
    }
    
    public void setSysDic(SysDic sysDic) {
        this.sysDic = sysDic;
    }
    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="ENABLED", nullable=false)
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sysDicDByCompanyType")
    public Set<Company> getCompaniesForCompanyType() {
        return this.companiesForCompanyType;
    }
    
    public void setCompaniesForCompanyType(Set<Company> companiesForCompanyType) {
        this.companiesForCompanyType = companiesForCompanyType;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sysDicDByCompanySize")
    public Set<Company> getCompaniesForCompanySize() {
        return this.companiesForCompanySize;
    }
    
    public void setCompaniesForCompanySize(Set<Company> companiesForCompanySize) {
        this.companiesForCompanySize = companiesForCompanySize;
    }




}


