package com.jms.domain.db;
// Generated 2015-6-6 20:38:20 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaskDoc generated by hbm2java
 */
@Entity
@Table(name="task_doc"
    ,catalog="jms"
)
public class TaskDoc  implements java.io.Serializable {


     private TaskDocId id;
     private Documents documents;
     private Task task;
     private Integer publish;

    public TaskDoc() {
    }

	
    public TaskDoc(TaskDocId id, Documents documents, Task task) {
        this.id = id;
        this.documents = documents;
        this.task = task;
    }
    public TaskDoc(TaskDocId id, Documents documents, Task task, Integer publish) {
       this.id = id;
       this.documents = documents;
       this.task = task;
       this.publish = publish;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idTask", column=@Column(name="ID_TASK", nullable=false) ), 
        @AttributeOverride(name="idDocument", column=@Column(name="ID_DOCUMENT", nullable=false) ) } )
    public TaskDocId getId() {
        return this.id;
    }
    
    public void setId(TaskDocId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOCUMENT", nullable=false, insertable=false, updatable=false)
    public Documents getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Documents documents) {
        this.documents = documents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TASK", nullable=false, insertable=false, updatable=false)
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }
    
    @Column(name="PUBLISH")
    public Integer getPublish() {
        return this.publish;
    }
    
    public void setPublish(Integer publish) {
        this.publish = publish;
    }




}


