package com.jms.domain.db;
// Generated 2015-5-30 22:39:13 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskComment generated by hbm2java
 */
@Entity
@Table(name="task_comment"
    ,catalog="jms"
)
public class TaskComment  implements java.io.Serializable {


     private Integer idComment;
     private Documents documents;
     private TaskComment taskComment;
     private Users users;
     private Task task;
     private String comment;
     private Date creationTime;
     private Date modificationTime;
     private Set<TaskComment> taskComments = new HashSet<TaskComment>(0);

    public TaskComment() {
    }

	
    public TaskComment(TaskComment taskComment) {
        this.taskComment = taskComment;
    }
    public TaskComment(Documents documents, TaskComment taskComment, Users users, Task task, String comment, Date creationTime, Date modificationTime, Set<TaskComment> taskComments) {
       this.documents = documents;
       this.taskComment = taskComment;
       this.users = users;
       this.task = task;
       this.comment = comment;
       this.creationTime = creationTime;
       this.modificationTime = modificationTime;
       this.taskComments = taskComments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_COMMENT", unique=true, nullable=false)
    public Integer getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOCUMENT")
    public Documents getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Documents documents) {
        this.documents = documents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMMENT", unique=true, nullable=false, insertable=false, updatable=false)
    public TaskComment getTaskComment() {
        return this.taskComment;
    }
    
    public void setTaskComment(TaskComment taskComment) {
        this.taskComment = taskComment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USER")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TASK")
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }
    
    @Column(name="COMMENT", length=512)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATION_TIME", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="MODIFICATION_TIME", length=10)
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="taskComment")
    public Set<TaskComment> getTaskComments() {
        return this.taskComments;
    }
    
    public void setTaskComments(Set<TaskComment> taskComments) {
        this.taskComments = taskComments;
    }




}


