package com.jms.domain.db;
// Generated 2016-3-9 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="jms4"
)
public class Users  implements java.io.Serializable {


     private Long idUser;
     private SysDicD sysDicDByLocale;
     private SysDicD sysDicDByStatus;
     private Company company;
     private District district;
     private Document documentByPic;
     private SysDicD sysDicDByScheme;
     private SysDicD sysDicDByGender;
     private Users users;
     private Document documentByCv;
     private Date creationTime;
     private String username;
     private String mobile;
     private String email;
     private String password;
     private String idcard;
     private String name;
     private String address;
     private String ext;
     private String ENo;
     private String school;
     private Date gradTime;
     private String major;
     private String degree;
     private String emergencyHp;
     private Long enabled;
     private String description;
     private Date birthday;
     private Date lastLogin;
     private String token;
     private Long userType;
     private Set<WProject> WProjects = new HashSet<WProject>(0);
     private Set<Notice> notices = new HashSet<Notice>(0);
     private Set<SPo> SPos = new HashSet<SPo>(0);
     private Set<PAttDraw> PAttDraws = new HashSet<PAttDraw>(0);
     private Set<PPollParticipant> PPollParticipants = new HashSet<PPollParticipant>(0);
     private Set<WIssueComment> WIssueComments = new HashSet<WIssueComment>(0);
     private Set<AApprovalPhase> AApprovalPhases = new HashSet<AApprovalPhase>(0);
     private Set<WProjectParticipant> WProjectParticipants = new HashSet<WProjectParticipant>(0);
     private Set<Notification> notifications = new HashSet<Notification>(0);
     private Set<SStk> SStks = new HashSet<SStk>(0);
     private Set<AApprovalType> AApprovalTypes = new HashSet<AApprovalType>(0);
     private Set<QFaiInFinal> QFaiInFinalsForInspector = new HashSet<QFaiInFinal>(0);
     private Set<QFaiInFinal> QFaiInFinalsForShiftLeader = new HashSet<QFaiInFinal>(0);
     private Set<QFaiInFinal> QFaiInFinalsForOp = new HashSet<QFaiInFinal>(0);
     private Set<AApprovalCc> AApprovalCcs = new HashSet<AApprovalCc>(0);
     private Set<MRepairHistory> MRepairHistoriesForOp = new HashSet<MRepairHistory>(0);
     private Set<PPoll> PPolls = new HashSet<PPoll>(0);
     private Set<MRepairHistory> MRepairHistoriesForMaintainer = new HashSet<MRepairHistory>(0);
     private Set<MRepairHistory> MRepairHistoriesForConfirmor = new HashSet<MRepairHistory>(0);
     private Set<QDimensionReport> QDimensionReportsForCheckBy = new HashSet<QDimensionReport>(0);
     private Set<MRepairHistory> MRepairHistoriesForRepair = new HashSet<MRepairHistory>(0);
     private Set<QDimensionReport> QDimensionReportsForInspector = new HashSet<QDimensionReport>(0);
     private Set<PWorkCenter> PWorkCenters = new HashSet<PWorkCenter>(0);
     private Set<Document> documentsForModifyBy = new HashSet<Document>(0);
     private Set<PBomLabel> PBomLabels = new HashSet<PBomLabel>(0);
     private Set<QNcp> QNcpsForApproval02 = new HashSet<QNcp>(0);
     private Set<Document> documentsForCreator = new HashSet<Document>(0);
     private Set<QNcp> QNcpsForApproval03 = new HashSet<QNcp>(0);
     private Set<QNcp> QNcpsForAudit03 = new HashSet<QNcp>(0);
     private Set<SCompanyCo> SCompanyCos = new HashSet<SCompanyCo>(0);
     private Set<QNcp> QNcpsForResponse = new HashSet<QNcp>(0);
     private Set<SSo> SSos = new HashSet<SSo>(0);
     private Set<EEhs> EEhsesForSupervisor = new HashSet<EEhs>(0);
     private Set<QNcp> QNcpsForPublish = new HashSet<QNcp>(0);
     private Set<QNcp> QNcpsForAudit01 = new HashSet<QNcp>(0);
     private Set<SAttachment> SAttachments = new HashSet<SAttachment>(0);
     private Set<GroupMembers> groupMemberses = new HashSet<GroupMembers>(0);
     private Set<Groups> groupses = new HashSet<Groups>(0);
     private Set<PRoutineD> PRoutineDs = new HashSet<PRoutineD>(0);
     private Set<EEhs> EEhsesForOp = new HashSet<EEhs>(0);
     private Set<PCPp> PCPps = new HashSet<PCPp>(0);
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<MMainRecord> MMainRecords = new HashSet<MMainRecord>(0);
     private Set<WTask> WTasks = new HashSet<WTask>(0);
     private Set<QNcp> QNcpsForAudit02 = new HashSet<QNcp>(0);
     private Set<QNcp> QNcpsForCountersign = new HashSet<QNcp>(0);
     private Set<SPic> SPics = new HashSet<SPic>(0);
     private Set<QNcp> QNcpsForOwner = new HashSet<QNcp>(0);
     private Set<WTaskParticipant> WTaskParticipants = new HashSet<WTaskParticipant>(0);
     private Set<CSchedule> CSchedules = new HashSet<CSchedule>(0);
     private Set<WIssue> WIssues = new HashSet<WIssue>(0);
     private Set<SMtf> SMtfs = new HashSet<SMtf>(0);
     private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
     private Set<QAtt> QAtts = new HashSet<QAtt>(0);
     private Set<AApplication> AApplications = new HashSet<AApplication>(0);
     private Set<CScheduleWatcher> CScheduleWatchers = new HashSet<CScheduleWatcher>(0);
     private Set<WTaskComment> WTaskComments = new HashSet<WTaskComment>(0);
     private Set<QNcrPic> QNcrPics = new HashSet<QNcrPic>(0);
     private Set<PCheckPlan> PCheckPlansForCreator = new HashSet<PCheckPlan>(0);
     private Set<PCheckPlan> PCheckPlansForChecker = new HashSet<PCheckPlan>(0);
     private Set<Company> companiesForCreator = new HashSet<Company>(0);
     private Set<Company> companiesForModifyBy = new HashSet<Company>(0);
     private Set<PWo> PWos = new HashSet<PWo>(0);

    public Users() {
    }

	
    public Users(String password, Long enabled) {
        this.password = password;
        this.enabled = enabled;
    }
    public Users(SysDicD sysDicDByLocale, SysDicD sysDicDByStatus, Company company, District district, Document documentByPic, SysDicD sysDicDByScheme, SysDicD sysDicDByGender, Users users, Document documentByCv, Date creationTime, String username, String mobile, String email, String password, String idcard, String name, String address, String ext, String ENo, String school, Date gradTime, String major, String degree, String emergencyHp, Long enabled, String description, Date birthday, Date lastLogin, String token, Long userType, Set<WProject> WProjects, Set<Notice> notices, Set<SPo> SPos, Set<PAttDraw> PAttDraws, Set<PPollParticipant> PPollParticipants, Set<WIssueComment> WIssueComments, Set<AApprovalPhase> AApprovalPhases, Set<WProjectParticipant> WProjectParticipants, Set<Notification> notifications, Set<SStk> SStks, Set<AApprovalType> AApprovalTypes, Set<QFaiInFinal> QFaiInFinalsForInspector, Set<QFaiInFinal> QFaiInFinalsForShiftLeader, Set<QFaiInFinal> QFaiInFinalsForOp, Set<AApprovalCc> AApprovalCcs, Set<MRepairHistory> MRepairHistoriesForOp, Set<PPoll> PPolls, Set<MRepairHistory> MRepairHistoriesForMaintainer, Set<MRepairHistory> MRepairHistoriesForConfirmor, Set<QDimensionReport> QDimensionReportsForCheckBy, Set<MRepairHistory> MRepairHistoriesForRepair, Set<QDimensionReport> QDimensionReportsForInspector, Set<PWorkCenter> PWorkCenters, Set<Document> documentsForModifyBy, Set<PBomLabel> PBomLabels, Set<QNcp> QNcpsForApproval02, Set<Document> documentsForCreator, Set<QNcp> QNcpsForApproval03, Set<QNcp> QNcpsForAudit03, Set<SCompanyCo> SCompanyCos, Set<QNcp> QNcpsForResponse, Set<SSo> SSos, Set<EEhs> EEhsesForSupervisor, Set<QNcp> QNcpsForPublish, Set<QNcp> QNcpsForAudit01, Set<SAttachment> SAttachments, Set<GroupMembers> groupMemberses, Set<Groups> groupses, Set<PRoutineD> PRoutineDs, Set<EEhs> EEhsesForOp, Set<PCPp> PCPps, Set<Users> userses, Set<MMainRecord> MMainRecords, Set<WTask> WTasks, Set<QNcp> QNcpsForAudit02, Set<QNcp> QNcpsForCountersign, Set<SPic> SPics, Set<QNcp> QNcpsForOwner, Set<WTaskParticipant> WTaskParticipants, Set<CSchedule> CSchedules, Set<WIssue> WIssues, Set<SMtf> SMtfs, Set<Feedback> feedbacks, Set<QAtt> QAtts, Set<AApplication> AApplications, Set<CScheduleWatcher> CScheduleWatchers, Set<WTaskComment> WTaskComments, Set<QNcrPic> QNcrPics, Set<PCheckPlan> PCheckPlansForCreator, Set<PCheckPlan> PCheckPlansForChecker, Set<Company> companiesForCreator, Set<Company> companiesForModifyBy, Set<PWo> PWos) {
       this.sysDicDByLocale = sysDicDByLocale;
       this.sysDicDByStatus = sysDicDByStatus;
       this.company = company;
       this.district = district;
       this.documentByPic = documentByPic;
       this.sysDicDByScheme = sysDicDByScheme;
       this.sysDicDByGender = sysDicDByGender;
       this.users = users;
       this.documentByCv = documentByCv;
       this.creationTime = creationTime;
       this.username = username;
       this.mobile = mobile;
       this.email = email;
       this.password = password;
       this.idcard = idcard;
       this.name = name;
       this.address = address;
       this.ext = ext;
       this.ENo = ENo;
       this.school = school;
       this.gradTime = gradTime;
       this.major = major;
       this.degree = degree;
       this.emergencyHp = emergencyHp;
       this.enabled = enabled;
       this.description = description;
       this.birthday = birthday;
       this.lastLogin = lastLogin;
       this.token = token;
       this.userType = userType;
       this.WProjects = WProjects;
       this.notices = notices;
       this.SPos = SPos;
       this.PAttDraws = PAttDraws;
       this.PPollParticipants = PPollParticipants;
       this.WIssueComments = WIssueComments;
       this.AApprovalPhases = AApprovalPhases;
       this.WProjectParticipants = WProjectParticipants;
       this.notifications = notifications;
       this.SStks = SStks;
       this.AApprovalTypes = AApprovalTypes;
       this.QFaiInFinalsForInspector = QFaiInFinalsForInspector;
       this.QFaiInFinalsForShiftLeader = QFaiInFinalsForShiftLeader;
       this.QFaiInFinalsForOp = QFaiInFinalsForOp;
       this.AApprovalCcs = AApprovalCcs;
       this.MRepairHistoriesForOp = MRepairHistoriesForOp;
       this.PPolls = PPolls;
       this.MRepairHistoriesForMaintainer = MRepairHistoriesForMaintainer;
       this.MRepairHistoriesForConfirmor = MRepairHistoriesForConfirmor;
       this.QDimensionReportsForCheckBy = QDimensionReportsForCheckBy;
       this.MRepairHistoriesForRepair = MRepairHistoriesForRepair;
       this.QDimensionReportsForInspector = QDimensionReportsForInspector;
       this.PWorkCenters = PWorkCenters;
       this.documentsForModifyBy = documentsForModifyBy;
       this.PBomLabels = PBomLabels;
       this.QNcpsForApproval02 = QNcpsForApproval02;
       this.documentsForCreator = documentsForCreator;
       this.QNcpsForApproval03 = QNcpsForApproval03;
       this.QNcpsForAudit03 = QNcpsForAudit03;
       this.SCompanyCos = SCompanyCos;
       this.QNcpsForResponse = QNcpsForResponse;
       this.SSos = SSos;
       this.EEhsesForSupervisor = EEhsesForSupervisor;
       this.QNcpsForPublish = QNcpsForPublish;
       this.QNcpsForAudit01 = QNcpsForAudit01;
       this.SAttachments = SAttachments;
       this.groupMemberses = groupMemberses;
       this.groupses = groupses;
       this.PRoutineDs = PRoutineDs;
       this.EEhsesForOp = EEhsesForOp;
       this.PCPps = PCPps;
       this.userses = userses;
       this.MMainRecords = MMainRecords;
       this.WTasks = WTasks;
       this.QNcpsForAudit02 = QNcpsForAudit02;
       this.QNcpsForCountersign = QNcpsForCountersign;
       this.SPics = SPics;
       this.QNcpsForOwner = QNcpsForOwner;
       this.WTaskParticipants = WTaskParticipants;
       this.CSchedules = CSchedules;
       this.WIssues = WIssues;
       this.SMtfs = SMtfs;
       this.feedbacks = feedbacks;
       this.QAtts = QAtts;
       this.AApplications = AApplications;
       this.CScheduleWatchers = CScheduleWatchers;
       this.WTaskComments = WTaskComments;
       this.QNcrPics = QNcrPics;
       this.PCheckPlansForCreator = PCheckPlansForCreator;
       this.PCheckPlansForChecker = PCheckPlansForChecker;
       this.companiesForCreator = companiesForCreator;
       this.companiesForModifyBy = companiesForModifyBy;
       this.PWos = PWos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_user", unique=true, nullable=false)
    public Long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="locale")
    public SysDicD getSysDicDByLocale() {
        return this.sysDicDByLocale;
    }
    
    public void setSysDicDByLocale(SysDicD sysDicDByLocale) {
        this.sysDicDByLocale = sysDicDByLocale;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SysDicD getSysDicDByStatus() {
        return this.sysDicDByStatus;
    }
    
    public void setSysDicDByStatus(SysDicD sysDicDByStatus) {
        this.sysDicDByStatus = sysDicDByStatus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_district")
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pic")
    public Document getDocumentByPic() {
        return this.documentByPic;
    }
    
    public void setDocumentByPic(Document documentByPic) {
        this.documentByPic = documentByPic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="scheme")
    public SysDicD getSysDicDByScheme() {
        return this.sysDicDByScheme;
    }
    
    public void setSysDicDByScheme(SysDicD sysDicDByScheme) {
        this.sysDicDByScheme = sysDicDByScheme;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gender")
    public SysDicD getSysDicDByGender() {
        return this.sysDicDByGender;
    }
    
    public void setSysDicDByGender(SysDicD sysDicDByGender) {
        this.sysDicDByGender = sysDicDByGender;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cv")
    public Document getDocumentByCv() {
        return this.documentByCv;
    }
    
    public void setDocumentByCv(Document documentByCv) {
        this.documentByCv = documentByCv;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    
    @Column(name="username", length=64)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="mobile", length=64)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="email", length=64)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="password", nullable=false, length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="idcard", length=18)
    public String getIdcard() {
        return this.idcard;
    }
    
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="address", length=128)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="ext", length=20)
    public String getExt() {
        return this.ext;
    }
    
    public void setExt(String ext) {
        this.ext = ext;
    }
    
    @Column(name="e_no", length=20)
    public String getENo() {
        return this.ENo;
    }
    
    public void setENo(String ENo) {
        this.ENo = ENo;
    }
    
    @Column(name="school", length=128)
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="grad_time", length=10)
    public Date getGradTime() {
        return this.gradTime;
    }
    
    public void setGradTime(Date gradTime) {
        this.gradTime = gradTime;
    }
    
    @Column(name="major", length=64)
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    
    @Column(name="degree", length=64)
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    
    @Column(name="emergency_hp", length=64)
    public String getEmergencyHp() {
        return this.emergencyHp;
    }
    
    public void setEmergencyHp(String emergencyHp) {
        this.emergencyHp = emergencyHp;
    }
    
    @Column(name="enabled", nullable=false)
    public Long getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Long enabled) {
        this.enabled = enabled;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login", length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    
    @Column(name="token", length=128)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    
    @Column(name="user_type")
    public Long getUserType() {
        return this.userType;
    }
    
    public void setUserType(Long userType) {
        this.userType = userType;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<WProject> getWProjects() {
        return this.WProjects;
    }
    
    public void setWProjects(Set<WProject> WProjects) {
        this.WProjects = WProjects;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Notice> getNotices() {
        return this.notices;
    }
    
    public void setNotices(Set<Notice> notices) {
        this.notices = notices;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<SPo> getSPos() {
        return this.SPos;
    }
    
    public void setSPos(Set<SPo> SPos) {
        this.SPos = SPos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PAttDraw> getPAttDraws() {
        return this.PAttDraws;
    }
    
    public void setPAttDraws(Set<PAttDraw> PAttDraws) {
        this.PAttDraws = PAttDraws;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PPollParticipant> getPPollParticipants() {
        return this.PPollParticipants;
    }
    
    public void setPPollParticipants(Set<PPollParticipant> PPollParticipants) {
        this.PPollParticipants = PPollParticipants;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<WIssueComment> getWIssueComments() {
        return this.WIssueComments;
    }
    
    public void setWIssueComments(Set<WIssueComment> WIssueComments) {
        this.WIssueComments = WIssueComments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<AApprovalPhase> getAApprovalPhases() {
        return this.AApprovalPhases;
    }
    
    public void setAApprovalPhases(Set<AApprovalPhase> AApprovalPhases) {
        this.AApprovalPhases = AApprovalPhases;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<WProjectParticipant> getWProjectParticipants() {
        return this.WProjectParticipants;
    }
    
    public void setWProjectParticipants(Set<WProjectParticipant> WProjectParticipants) {
        this.WProjectParticipants = WProjectParticipants;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Notification> getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set<Notification> notifications) {
        this.notifications = notifications;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<SStk> getSStks() {
        return this.SStks;
    }
    
    public void setSStks(Set<SStk> SStks) {
        this.SStks = SStks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<AApprovalType> getAApprovalTypes() {
        return this.AApprovalTypes;
    }
    
    public void setAApprovalTypes(Set<AApprovalType> AApprovalTypes) {
        this.AApprovalTypes = AApprovalTypes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByInspector")
    public Set<QFaiInFinal> getQFaiInFinalsForInspector() {
        return this.QFaiInFinalsForInspector;
    }
    
    public void setQFaiInFinalsForInspector(Set<QFaiInFinal> QFaiInFinalsForInspector) {
        this.QFaiInFinalsForInspector = QFaiInFinalsForInspector;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByShiftLeader")
    public Set<QFaiInFinal> getQFaiInFinalsForShiftLeader() {
        return this.QFaiInFinalsForShiftLeader;
    }
    
    public void setQFaiInFinalsForShiftLeader(Set<QFaiInFinal> QFaiInFinalsForShiftLeader) {
        this.QFaiInFinalsForShiftLeader = QFaiInFinalsForShiftLeader;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByOp")
    public Set<QFaiInFinal> getQFaiInFinalsForOp() {
        return this.QFaiInFinalsForOp;
    }
    
    public void setQFaiInFinalsForOp(Set<QFaiInFinal> QFaiInFinalsForOp) {
        this.QFaiInFinalsForOp = QFaiInFinalsForOp;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<AApprovalCc> getAApprovalCcs() {
        return this.AApprovalCcs;
    }
    
    public void setAApprovalCcs(Set<AApprovalCc> AApprovalCcs) {
        this.AApprovalCcs = AApprovalCcs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByOp")
    public Set<MRepairHistory> getMRepairHistoriesForOp() {
        return this.MRepairHistoriesForOp;
    }
    
    public void setMRepairHistoriesForOp(Set<MRepairHistory> MRepairHistoriesForOp) {
        this.MRepairHistoriesForOp = MRepairHistoriesForOp;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PPoll> getPPolls() {
        return this.PPolls;
    }
    
    public void setPPolls(Set<PPoll> PPolls) {
        this.PPolls = PPolls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByMaintainer")
    public Set<MRepairHistory> getMRepairHistoriesForMaintainer() {
        return this.MRepairHistoriesForMaintainer;
    }
    
    public void setMRepairHistoriesForMaintainer(Set<MRepairHistory> MRepairHistoriesForMaintainer) {
        this.MRepairHistoriesForMaintainer = MRepairHistoriesForMaintainer;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByConfirmor")
    public Set<MRepairHistory> getMRepairHistoriesForConfirmor() {
        return this.MRepairHistoriesForConfirmor;
    }
    
    public void setMRepairHistoriesForConfirmor(Set<MRepairHistory> MRepairHistoriesForConfirmor) {
        this.MRepairHistoriesForConfirmor = MRepairHistoriesForConfirmor;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByCheckBy")
    public Set<QDimensionReport> getQDimensionReportsForCheckBy() {
        return this.QDimensionReportsForCheckBy;
    }
    
    public void setQDimensionReportsForCheckBy(Set<QDimensionReport> QDimensionReportsForCheckBy) {
        this.QDimensionReportsForCheckBy = QDimensionReportsForCheckBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByRepair")
    public Set<MRepairHistory> getMRepairHistoriesForRepair() {
        return this.MRepairHistoriesForRepair;
    }
    
    public void setMRepairHistoriesForRepair(Set<MRepairHistory> MRepairHistoriesForRepair) {
        this.MRepairHistoriesForRepair = MRepairHistoriesForRepair;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByInspector")
    public Set<QDimensionReport> getQDimensionReportsForInspector() {
        return this.QDimensionReportsForInspector;
    }
    
    public void setQDimensionReportsForInspector(Set<QDimensionReport> QDimensionReportsForInspector) {
        this.QDimensionReportsForInspector = QDimensionReportsForInspector;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PWorkCenter> getPWorkCenters() {
        return this.PWorkCenters;
    }
    
    public void setPWorkCenters(Set<PWorkCenter> PWorkCenters) {
        this.PWorkCenters = PWorkCenters;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByModifyBy")
    public Set<Document> getDocumentsForModifyBy() {
        return this.documentsForModifyBy;
    }
    
    public void setDocumentsForModifyBy(Set<Document> documentsForModifyBy) {
        this.documentsForModifyBy = documentsForModifyBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PBomLabel> getPBomLabels() {
        return this.PBomLabels;
    }
    
    public void setPBomLabels(Set<PBomLabel> PBomLabels) {
        this.PBomLabels = PBomLabels;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByApproval02")
    public Set<QNcp> getQNcpsForApproval02() {
        return this.QNcpsForApproval02;
    }
    
    public void setQNcpsForApproval02(Set<QNcp> QNcpsForApproval02) {
        this.QNcpsForApproval02 = QNcpsForApproval02;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByCreator")
    public Set<Document> getDocumentsForCreator() {
        return this.documentsForCreator;
    }
    
    public void setDocumentsForCreator(Set<Document> documentsForCreator) {
        this.documentsForCreator = documentsForCreator;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByApproval03")
    public Set<QNcp> getQNcpsForApproval03() {
        return this.QNcpsForApproval03;
    }
    
    public void setQNcpsForApproval03(Set<QNcp> QNcpsForApproval03) {
        this.QNcpsForApproval03 = QNcpsForApproval03;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByAudit03")
    public Set<QNcp> getQNcpsForAudit03() {
        return this.QNcpsForAudit03;
    }
    
    public void setQNcpsForAudit03(Set<QNcp> QNcpsForAudit03) {
        this.QNcpsForAudit03 = QNcpsForAudit03;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<SCompanyCo> getSCompanyCos() {
        return this.SCompanyCos;
    }
    
    public void setSCompanyCos(Set<SCompanyCo> SCompanyCos) {
        this.SCompanyCos = SCompanyCos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByResponse")
    public Set<QNcp> getQNcpsForResponse() {
        return this.QNcpsForResponse;
    }
    
    public void setQNcpsForResponse(Set<QNcp> QNcpsForResponse) {
        this.QNcpsForResponse = QNcpsForResponse;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<SSo> getSSos() {
        return this.SSos;
    }
    
    public void setSSos(Set<SSo> SSos) {
        this.SSos = SSos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersBySupervisor")
    public Set<EEhs> getEEhsesForSupervisor() {
        return this.EEhsesForSupervisor;
    }
    
    public void setEEhsesForSupervisor(Set<EEhs> EEhsesForSupervisor) {
        this.EEhsesForSupervisor = EEhsesForSupervisor;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByPublish")
    public Set<QNcp> getQNcpsForPublish() {
        return this.QNcpsForPublish;
    }
    
    public void setQNcpsForPublish(Set<QNcp> QNcpsForPublish) {
        this.QNcpsForPublish = QNcpsForPublish;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByAudit01")
    public Set<QNcp> getQNcpsForAudit01() {
        return this.QNcpsForAudit01;
    }
    
    public void setQNcpsForAudit01(Set<QNcp> QNcpsForAudit01) {
        this.QNcpsForAudit01 = QNcpsForAudit01;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<SAttachment> getSAttachments() {
        return this.SAttachments;
    }
    
    public void setSAttachments(Set<SAttachment> SAttachments) {
        this.SAttachments = SAttachments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<GroupMembers> getGroupMemberses() {
        return this.groupMemberses;
    }
    
    public void setGroupMemberses(Set<GroupMembers> groupMemberses) {
        this.groupMemberses = groupMemberses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Groups> getGroupses() {
        return this.groupses;
    }
    
    public void setGroupses(Set<Groups> groupses) {
        this.groupses = groupses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PRoutineD> getPRoutineDs() {
        return this.PRoutineDs;
    }
    
    public void setPRoutineDs(Set<PRoutineD> PRoutineDs) {
        this.PRoutineDs = PRoutineDs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByOp")
    public Set<EEhs> getEEhsesForOp() {
        return this.EEhsesForOp;
    }
    
    public void setEEhsesForOp(Set<EEhs> EEhsesForOp) {
        this.EEhsesForOp = EEhsesForOp;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PCPp> getPCPps() {
        return this.PCPps;
    }
    
    public void setPCPps(Set<PCPp> PCPps) {
        this.PCPps = PCPps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<MMainRecord> getMMainRecords() {
        return this.MMainRecords;
    }
    
    public void setMMainRecords(Set<MMainRecord> MMainRecords) {
        this.MMainRecords = MMainRecords;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<WTask> getWTasks() {
        return this.WTasks;
    }
    
    public void setWTasks(Set<WTask> WTasks) {
        this.WTasks = WTasks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByAudit02")
    public Set<QNcp> getQNcpsForAudit02() {
        return this.QNcpsForAudit02;
    }
    
    public void setQNcpsForAudit02(Set<QNcp> QNcpsForAudit02) {
        this.QNcpsForAudit02 = QNcpsForAudit02;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByCountersign")
    public Set<QNcp> getQNcpsForCountersign() {
        return this.QNcpsForCountersign;
    }
    
    public void setQNcpsForCountersign(Set<QNcp> QNcpsForCountersign) {
        this.QNcpsForCountersign = QNcpsForCountersign;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<SPic> getSPics() {
        return this.SPics;
    }
    
    public void setSPics(Set<SPic> SPics) {
        this.SPics = SPics;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByOwner")
    public Set<QNcp> getQNcpsForOwner() {
        return this.QNcpsForOwner;
    }
    
    public void setQNcpsForOwner(Set<QNcp> QNcpsForOwner) {
        this.QNcpsForOwner = QNcpsForOwner;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<WTaskParticipant> getWTaskParticipants() {
        return this.WTaskParticipants;
    }
    
    public void setWTaskParticipants(Set<WTaskParticipant> WTaskParticipants) {
        this.WTaskParticipants = WTaskParticipants;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<CSchedule> getCSchedules() {
        return this.CSchedules;
    }
    
    public void setCSchedules(Set<CSchedule> CSchedules) {
        this.CSchedules = CSchedules;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<WIssue> getWIssues() {
        return this.WIssues;
    }
    
    public void setWIssues(Set<WIssue> WIssues) {
        this.WIssues = WIssues;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<SMtf> getSMtfs() {
        return this.SMtfs;
    }
    
    public void setSMtfs(Set<SMtf> SMtfs) {
        this.SMtfs = SMtfs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Feedback> getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<QAtt> getQAtts() {
        return this.QAtts;
    }
    
    public void setQAtts(Set<QAtt> QAtts) {
        this.QAtts = QAtts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<AApplication> getAApplications() {
        return this.AApplications;
    }
    
    public void setAApplications(Set<AApplication> AApplications) {
        this.AApplications = AApplications;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<CScheduleWatcher> getCScheduleWatchers() {
        return this.CScheduleWatchers;
    }
    
    public void setCScheduleWatchers(Set<CScheduleWatcher> CScheduleWatchers) {
        this.CScheduleWatchers = CScheduleWatchers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<WTaskComment> getWTaskComments() {
        return this.WTaskComments;
    }
    
    public void setWTaskComments(Set<WTaskComment> WTaskComments) {
        this.WTaskComments = WTaskComments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<QNcrPic> getQNcrPics() {
        return this.QNcrPics;
    }
    
    public void setQNcrPics(Set<QNcrPic> QNcrPics) {
        this.QNcrPics = QNcrPics;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByCreator")
    public Set<PCheckPlan> getPCheckPlansForCreator() {
        return this.PCheckPlansForCreator;
    }
    
    public void setPCheckPlansForCreator(Set<PCheckPlan> PCheckPlansForCreator) {
        this.PCheckPlansForCreator = PCheckPlansForCreator;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByChecker")
    public Set<PCheckPlan> getPCheckPlansForChecker() {
        return this.PCheckPlansForChecker;
    }
    
    public void setPCheckPlansForChecker(Set<PCheckPlan> PCheckPlansForChecker) {
        this.PCheckPlansForChecker = PCheckPlansForChecker;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByCreator")
    public Set<Company> getCompaniesForCreator() {
        return this.companiesForCreator;
    }
    
    public void setCompaniesForCreator(Set<Company> companiesForCreator) {
        this.companiesForCreator = companiesForCreator;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usersByModifyBy")
    public Set<Company> getCompaniesForModifyBy() {
        return this.companiesForModifyBy;
    }
    
    public void setCompaniesForModifyBy(Set<Company> companiesForModifyBy) {
        this.companiesForModifyBy = companiesForModifyBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<PWo> getPWos() {
        return this.PWos;
    }
    
    public void setPWos(Set<PWo> PWos) {
        this.PWos = PWos;
    }




}


