package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WIssue generated by hbm2java
 */
@Entity
@Table(name="w_issue"
    ,catalog="jms5"
)
public class WIssue  implements java.io.Serializable {


     private Long idIssue;
     private SysDicD sysDicDByStatus;
     private SysDicD sysDicDBySourceType;
     private Users users;
     private SysDicD sysDicDByPriority;
     private String title;
     private String description;
     private Date creationTime;
     private Long source;
     private Set<WIssueComment> WIssueComments = new HashSet<WIssueComment>(0);
     private Set<WIssueDoc> WIssueDocs = new HashSet<WIssueDoc>(0);

    public WIssue() {
    }

    public WIssue(SysDicD sysDicDByStatus, SysDicD sysDicDBySourceType, Users users, SysDicD sysDicDByPriority, String title, String description, Date creationTime, Long source, Set<WIssueComment> WIssueComments, Set<WIssueDoc> WIssueDocs) {
       this.sysDicDByStatus = sysDicDByStatus;
       this.sysDicDBySourceType = sysDicDBySourceType;
       this.users = users;
       this.sysDicDByPriority = sysDicDByPriority;
       this.title = title;
       this.description = description;
       this.creationTime = creationTime;
       this.source = source;
       this.WIssueComments = WIssueComments;
       this.WIssueDocs = WIssueDocs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_issue", unique=true, nullable=false)
    public Long getIdIssue() {
        return this.idIssue;
    }
    
    public void setIdIssue(Long idIssue) {
        this.idIssue = idIssue;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SysDicD getSysDicDByStatus() {
        return this.sysDicDByStatus;
    }
    
    public void setSysDicDByStatus(SysDicD sysDicDByStatus) {
        this.sysDicDByStatus = sysDicDByStatus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="source_type")
    public SysDicD getSysDicDBySourceType() {
        return this.sysDicDBySourceType;
    }
    
    public void setSysDicDBySourceType(SysDicD sysDicDBySourceType) {
        this.sysDicDBySourceType = sysDicDBySourceType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="priority")
    public SysDicD getSysDicDByPriority() {
        return this.sysDicDByPriority;
    }
    
    public void setSysDicDByPriority(SysDicD sysDicDByPriority) {
        this.sysDicDByPriority = sysDicDByPriority;
    }
    
    @Column(name="title", length=64)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    
    @Column(name="source")
    public Long getSource() {
        return this.source;
    }
    
    public void setSource(Long source) {
        this.source = source;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WIssue")
    public Set<WIssueComment> getWIssueComments() {
        return this.WIssueComments;
    }
    
    public void setWIssueComments(Set<WIssueComment> WIssueComments) {
        this.WIssueComments = WIssueComments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WIssue")
    public Set<WIssueDoc> getWIssueDocs() {
        return this.WIssueDocs;
    }
    
    public void setWIssueDocs(Set<WIssueDoc> WIssueDocs) {
        this.WIssueDocs = WIssueDocs;
    }




}


