package com.jms.domain.db;
// Generated 2016-3-31 16:15:17 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WProjectDoc generated by hbm2java
 */
@Entity
@Table(name="w_project_doc"
    ,catalog="jms5"
)
public class WProjectDoc  implements java.io.Serializable {


     private WProjectDocId id;
     private Document document;
     private WProject WProject;
     private Long publish;

    public WProjectDoc() {
    }

	
    public WProjectDoc(WProjectDocId id, Document document, WProject WProject) {
        this.id = id;
        this.document = document;
        this.WProject = WProject;
    }
    public WProjectDoc(WProjectDocId id, Document document, WProject WProject, Long publish) {
       this.id = id;
       this.document = document;
       this.WProject = WProject;
       this.publish = publish;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idProject", column=@Column(name="id_project", nullable=false) ), 
        @AttributeOverride(name="idDocument", column=@Column(name="id_document", nullable=false) ) } )
    public WProjectDocId getId() {
        return this.id;
    }
    
    public void setId(WProjectDocId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_document", nullable=false, insertable=false, updatable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_project", nullable=false, insertable=false, updatable=false)
    public WProject getWProject() {
        return this.WProject;
    }
    
    public void setWProject(WProject WProject) {
        this.WProject = WProject;
    }
    
    @Column(name="publish")
    public Long getPublish() {
        return this.publish;
    }
    
    public void setPublish(Long publish) {
        this.publish = publish;
    }




}


