package com.jms.domain.db;
// Generated 2015-12-31 19:48:00 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.jms.domain.db.AbstractSecuredEntity;
import com.jms.domain.db.Users;

/**
 * WProject generated by hbm2java
 */
@Entity
@Table(name="w_project"
    ,catalog="jms3"
)
public class WProject extends AbstractSecuredEntity  implements java.io.Serializable {


     private Long idProject;
     private SysDicD sysDicDByStatus;
     private Company company;
     private WProject WProject;
     private Users users;
     private SysDicD sysDicDByPriority;
     private String projectName;
     private String description;
     private String projectNumber;
     private Date planStartTime;
     private Date planEndTime;
     private Date startTime;
     private Date endTime;
     private Long process;
     private Set<WProjectParticipant> WProjectParticipants = new HashSet<WProjectParticipant>(0);
     private Set<WProjectDoc> WProjectDocs = new HashSet<WProjectDoc>(0);
     private Set<WTask> WTasks = new HashSet<WTask>(0);
     private Set<WProject> WProjects = new HashSet<WProject>(0);

    public WProject() {
    }

	
    public WProject(String projectName) {
        this.projectName = projectName;
    }
    public WProject(SysDicD sysDicDByStatus, Company company, WProject WProject, Users users, SysDicD sysDicDByPriority, String projectName, String description, String projectNumber, Date planStartTime, Date planEndTime, Date startTime, Date endTime, Long process, Set<WProjectParticipant> WProjectParticipants, Set<WProjectDoc> WProjectDocs, Set<WTask> WTasks, Set<WProject> WProjects) {
       this.sysDicDByStatus = sysDicDByStatus;
       this.company = company;
       this.WProject = WProject;
       this.users = users;
       this.sysDicDByPriority = sysDicDByPriority;
       this.projectName = projectName;
       this.description = description;
       this.projectNumber = projectNumber;
       this.planStartTime = planStartTime;
       this.planEndTime = planEndTime;
       this.startTime = startTime;
       this.endTime = endTime;
       this.process = process;
       this.WProjectParticipants = WProjectParticipants;
       this.WProjectDocs = WProjectDocs;
       this.WTasks = WTasks;
       this.WProjects = WProjects;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_project", unique=true, nullable=false)
    public Long getIdProject() {
        return this.idProject;
    }
    
    public void setIdProject(Long idProject) {
        this.idProject = idProject;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SysDicD getSysDicDByStatus() {
        return this.sysDicDByStatus;
    }
    
    public void setSysDicDByStatus(SysDicD sysDicDByStatus) {
        this.sysDicDByStatus = sysDicDByStatus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent")
    public WProject getWProject() {
        return this.WProject;
    }
    
    public void setWProject(WProject WProject) {
        this.WProject = WProject;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="leader")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="priority")
    public SysDicD getSysDicDByPriority() {
        return this.sysDicDByPriority;
    }
    
    public void setSysDicDByPriority(SysDicD sysDicDByPriority) {
        this.sysDicDByPriority = sysDicDByPriority;
    }
    
    @Column(name="project_name", nullable=false, length=64)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="project_number", length=64)
    public String getProjectNumber() {
        return this.projectNumber;
    }
    
    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="plan_start_time", length=10)
    public Date getPlanStartTime() {
        return this.planStartTime;
    }
    
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="plan_end_time", length=10)
    public Date getPlanEndTime() {
        return this.planEndTime;
    }
    
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="start_time", length=10)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="end_time", length=10)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="process")
    public Long getProcess() {
        return this.process;
    }
    
    public void setProcess(Long process) {
        this.process = process;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WProject")
    public Set<WProjectParticipant> getWProjectParticipants() {
        return this.WProjectParticipants;
    }
    
    public void setWProjectParticipants(Set<WProjectParticipant> WProjectParticipants) {
        this.WProjectParticipants = WProjectParticipants;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WProject")
    public Set<WProjectDoc> getWProjectDocs() {
        return this.WProjectDocs;
    }
    
    public void setWProjectDocs(Set<WProjectDoc> WProjectDocs) {
        this.WProjectDocs = WProjectDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WProject")
    public Set<WTask> getWTasks() {
        return this.WTasks;
    }
    
    public void setWTasks(Set<WTask> WTasks) {
        this.WTasks = WTasks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WProject")
    public Set<WProject> getWProjects() {
        return this.WProjects;
    }
    
    public void setWProjects(Set<WProject> WProjects) {
        this.WProjects = WProjects;
    }

    @Override @Transient
    public Long getId() {
        return this.getIdProject();
    }
   @Override  @Transient
  	public Users getUser() {
  		return this.getUsers();
  	}

	@Override
	public String toString()
	{
		return "项目名: " + this.getProjectName() +", 描述：" + this.getDescription();
	}



}


