package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WTaskParticipantId generated by hbm2java
 */
@Embeddable
public class WTaskParticipantId  implements java.io.Serializable {


     private Long idTask;
     private Long idUser;

    public WTaskParticipantId() {
    }

    public WTaskParticipantId(Long idTask, Long idUser) {
       this.idTask = idTask;
       this.idUser = idUser;
    }
   

    @Column(name="id_task", nullable=false)
    public Long getIdTask() {
        return this.idTask;
    }
    
    public void setIdTask(Long idTask) {
        this.idTask = idTask;
    }

    @Column(name="id_user", nullable=false)
    public Long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WTaskParticipantId) ) return false;
		 WTaskParticipantId castOther = ( WTaskParticipantId ) other; 
         
		 return ( (this.getIdTask()==castOther.getIdTask()) || ( this.getIdTask()!=null && castOther.getIdTask()!=null && this.getIdTask().equals(castOther.getIdTask()) ) )
 && ( (this.getIdUser()==castOther.getIdUser()) || ( this.getIdUser()!=null && castOther.getIdUser()!=null && this.getIdUser().equals(castOther.getIdUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTask() == null ? 0 : this.getIdTask().hashCode() );
         result = 37 * result + ( getIdUser() == null ? 0 : this.getIdUser().hashCode() );
         return result;
   }   


}


