package com.jms.domain.db;
// Generated 2016-1-6 12:39:14 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WTask generated by hbm2java
 */
@Entity
@Table(name="w_task"
    ,catalog="jms3"
)
public class WTask  implements java.io.Serializable {


     private Long idTask;
     private SysDicD sysDicDByStatus;
     private Users users;
     private WProject WProject;
     private SysDicD sysDicDByPriority;
     private String name;
     private String description;
     private Date creationTime;
     private Date modificationTime;
     private Date planStartTime;
     private Date planEndTime;
     private Long planDuration;
     private Date startTime;
     private Date endTime;
     private Long duration;
     private Long seq;
     private Set<WTaskDoc> WTaskDocs = new HashSet<WTaskDoc>(0);
     private Set<WTaskComment> WTaskComments = new HashSet<WTaskComment>(0);
     private Set<WTaskParticipant> WTaskParticipants = new HashSet<WTaskParticipant>(0);

    public WTask() {
    }

	
    public WTask(String name, Date planStartTime, Date planEndTime) {
        this.name = name;
        this.planStartTime = planStartTime;
        this.planEndTime = planEndTime;
    }
    public WTask(SysDicD sysDicDByStatus, Users users, WProject WProject, SysDicD sysDicDByPriority, String name, String description, Date creationTime, Date modificationTime, Date planStartTime, Date planEndTime, Long planDuration, Date startTime, Date endTime, Long duration, Long seq, Set<WTaskDoc> WTaskDocs, Set<WTaskComment> WTaskComments, Set<WTaskParticipant> WTaskParticipants) {
       this.sysDicDByStatus = sysDicDByStatus;
       this.users = users;
       this.WProject = WProject;
       this.sysDicDByPriority = sysDicDByPriority;
       this.name = name;
       this.description = description;
       this.creationTime = creationTime;
       this.modificationTime = modificationTime;
       this.planStartTime = planStartTime;
       this.planEndTime = planEndTime;
       this.planDuration = planDuration;
       this.startTime = startTime;
       this.endTime = endTime;
       this.duration = duration;
       this.seq = seq;
       this.WTaskDocs = WTaskDocs;
       this.WTaskComments = WTaskComments;
       this.WTaskParticipants = WTaskParticipants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_task", unique=true, nullable=false)
    public Long getIdTask() {
        return this.idTask;
    }
    
    public void setIdTask(Long idTask) {
        this.idTask = idTask;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public SysDicD getSysDicDByStatus() {
        return this.sysDicDByStatus;
    }
    
    public void setSysDicDByStatus(SysDicD sysDicDByStatus) {
        this.sysDicDByStatus = sysDicDByStatus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_project")
    public WProject getWProject() {
        return this.WProject;
    }
    
    public void setWProject(WProject WProject) {
        this.WProject = WProject;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="priority")
    public SysDicD getSysDicDByPriority() {
        return this.sysDicDByPriority;
    }
    
    public void setSysDicDByPriority(SysDicD sysDicDByPriority) {
        this.sysDicDByPriority = sysDicDByPriority;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", length=1024)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="modification_time", length=10)
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="plan_start_time", nullable=false, length=10)
    public Date getPlanStartTime() {
        return this.planStartTime;
    }
    
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="plan_end_time", nullable=false, length=10)
    public Date getPlanEndTime() {
        return this.planEndTime;
    }
    
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }
    
    @Column(name="plan_duration")
    public Long getPlanDuration() {
        return this.planDuration;
    }
    
    public void setPlanDuration(Long planDuration) {
        this.planDuration = planDuration;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="start_time", length=10)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="end_time", length=10)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="duration")
    public Long getDuration() {
        return this.duration;
    }
    
    public void setDuration(Long duration) {
        this.duration = duration;
    }
    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WTask")
    public Set<WTaskDoc> getWTaskDocs() {
        return this.WTaskDocs;
    }
    
    public void setWTaskDocs(Set<WTaskDoc> WTaskDocs) {
        this.WTaskDocs = WTaskDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WTask")
    public Set<WTaskComment> getWTaskComments() {
        return this.WTaskComments;
    }
    
    public void setWTaskComments(Set<WTaskComment> WTaskComments) {
        this.WTaskComments = WTaskComments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="WTask")
    public Set<WTaskParticipant> getWTaskParticipants() {
        return this.WTaskParticipants;
    }
    
    public void setWTaskParticipants(Set<WTaskParticipant> WTaskParticipants) {
        this.WTaskParticipants = WTaskParticipants;
    }




}


