package com.jms.domain.db;
// Generated 2015-7-5 7:21:02 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * IssueComment generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "issue_comment_AUD")
@Entity
@Table(name="issue_comment"
    ,catalog="jms"
)
public class IssueComment  implements java.io.Serializable {


     private Long idIssueComment;
     private Issue issue;
     private IssueComment issueComment;
     private Users users;
     private Date creationTime;
     private String comment;
     private Date modificationTime;
     private Set<IssueDoc> issueDocs = new HashSet<IssueDoc>(0);
     private Set<IssueComment> issueComments = new HashSet<IssueComment>(0);

    public IssueComment() {
    }

	
    public IssueComment(IssueComment issueComment) {
        this.issueComment = issueComment;
    }
    public IssueComment(Issue issue, IssueComment issueComment, Users users, Date creationTime, String comment, Date modificationTime, Set<IssueDoc> issueDocs, Set<IssueComment> issueComments) {
       this.issue = issue;
       this.issueComment = issueComment;
       this.users = users;
       this.creationTime = creationTime;
       this.comment = comment;
       this.modificationTime = modificationTime;
       this.issueDocs = issueDocs;
       this.issueComments = issueComments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_ISSUE_COMMENT", unique=true, nullable=false)
    public Long getIdIssueComment() {
        return this.idIssueComment;
    }
    
    public void setIdIssueComment(Long idIssueComment) {
        this.idIssueComment = idIssueComment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ISSUE")
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ISSUE_COMMENT", unique=true, nullable=false, insertable=false, updatable=false)
    public IssueComment getIssueComment() {
        return this.issueComment;
    }
    
    public void setIssueComment(IssueComment issueComment) {
        this.issueComment = issueComment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATOR")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATION_TIME", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    
    @Column(name="COMMENT", length=1024)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="MODIFICATION_TIME", length=10)
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="issueComment")
    public Set<IssueDoc> getIssueDocs() {
        return this.issueDocs;
    }
    
    public void setIssueDocs(Set<IssueDoc> issueDocs) {
        this.issueDocs = issueDocs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="issueComment")
    public Set<IssueComment> getIssueComments() {
        return this.issueComments;
    }
    
    public void setIssueComments(Set<IssueComment> issueComments) {
        this.issueComments = issueComments;
    }




}


