package com.jms.domain.db;
// Generated 2015-7-5 7:21:02 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * Poll generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "poll_AUD")
@Entity
@Table(name="poll"
    ,catalog="jms"
)
public class Poll  implements java.io.Serializable {


     private Long idPoll;
     private SysDicD sysDicD;
     private Users users;
     private String title;
     private String description;
     private Long maxItems;
     private Date creationTime;
     private Date endTime;
     private Long isAnonymous;
     private Long showResults;
     private String conclusion;
     private String url;
     private Set<PollParticipant> pollParticipants = new HashSet<PollParticipant>(0);
     private Set<PollItems> pollItemses = new HashSet<PollItems>(0);

    public Poll() {
    }

    public Poll(SysDicD sysDicD, Users users, String title, String description, Long maxItems, Date creationTime, Date endTime, Long isAnonymous, Long showResults, String conclusion, String url, Set<PollParticipant> pollParticipants, Set<PollItems> pollItemses) {
       this.sysDicD = sysDicD;
       this.users = users;
       this.title = title;
       this.description = description;
       this.maxItems = maxItems;
       this.creationTime = creationTime;
       this.endTime = endTime;
       this.isAnonymous = isAnonymous;
       this.showResults = showResults;
       this.conclusion = conclusion;
       this.url = url;
       this.pollParticipants = pollParticipants;
       this.pollItemses = pollItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_POLL", unique=true, nullable=false)
    public Long getIdPoll() {
        return this.idPoll;
    }
    
    public void setIdPoll(Long idPoll) {
        this.idPoll = idPoll;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public SysDicD getSysDicD() {
        return this.sysDicD;
    }
    
    public void setSysDicD(SysDicD sysDicD) {
        this.sysDicD = sysDicD;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATOR")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="TITLE", length=64)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="DESCRIPTION", length=1024)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="MAX_ITEMS")
    public Long getMaxItems() {
        return this.maxItems;
    }
    
    public void setMaxItems(Long maxItems) {
        this.maxItems = maxItems;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION_TIME", length=19)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_TIME", length=19)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="IS_ANONYMOUS")
    public Long getIsAnonymous() {
        return this.isAnonymous;
    }
    
    public void setIsAnonymous(Long isAnonymous) {
        this.isAnonymous = isAnonymous;
    }
    
    @Column(name="SHOW_RESULTS")
    public Long getShowResults() {
        return this.showResults;
    }
    
    public void setShowResults(Long showResults) {
        this.showResults = showResults;
    }
    
    @Column(name="CONCLUSION", length=512)
    public String getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }
    
    @Column(name="URL", length=512)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="poll")
    public Set<PollParticipant> getPollParticipants() {
        return this.pollParticipants;
    }
    
    public void setPollParticipants(Set<PollParticipant> pollParticipants) {
        this.pollParticipants = pollParticipants;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="poll")
    public Set<PollItems> getPollItemses() {
        return this.pollItemses;
    }
    
    public void setPollItemses(Set<PollItems> pollItemses) {
        this.pollItemses = pollItemses;
    }




}


