package com.jms.domain.db;
// Generated 2015-7-5 7:21:02 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * Sector generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "sector_AUD")
@Entity
@Table(name="sector"
    ,catalog="jms"
)
public class Sector  implements java.io.Serializable {


     private Long idSector;
     private Company company;
     private String sector;
     private String description;
     private Long seq;
     private Long enabled;
     private Set<Roles> roleses = new HashSet<Roles>(0);
     private Set<SectorMember> sectorMembers = new HashSet<SectorMember>(0);
     private Set<Notice> notices = new HashSet<Notice>(0);

    public Sector() {
    }

	
    public Sector(Company company) {
        this.company = company;
    }
    public Sector(Company company, String sector, String description, Long seq, Long enabled, Set<Roles> roleses, Set<SectorMember> sectorMembers, Set<Notice> notices) {
       this.company = company;
       this.sector = sector;
       this.description = description;
       this.seq = seq;
       this.enabled = enabled;
       this.roleses = roleses;
       this.sectorMembers = sectorMembers;
       this.notices = notices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_SECTOR", unique=true, nullable=false)
    public Long getIdSector() {
        return this.idSector;
    }
    
    public void setIdSector(Long idSector) {
        this.idSector = idSector;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMPANY", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="SECTOR", length=64)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }
    
    @Column(name="Description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SEQ")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }
    
    @Column(name="ENABLED")
    public Long getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Long enabled) {
        this.enabled = enabled;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sector")
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sector")
    public Set<SectorMember> getSectorMembers() {
        return this.sectorMembers;
    }
    
    public void setSectorMembers(Set<SectorMember> sectorMembers) {
        this.sectorMembers = sectorMembers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sector")
    public Set<Notice> getNotices() {
        return this.notices;
    }
    
    public void setNotices(Set<Notice> notices) {
        this.notices = notices;
    }




}


