package com.jms.domain.db;
// Generated 2015-7-5 7:21:02 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

/**
 * TaskDoc generated by hbm2java
 */
@Audited
@AuditTable(catalog="jms_aud", value = "task_doc_AUD")
@Entity
@Table(name="task_doc"
    ,catalog="jms"
)
public class TaskDoc  implements java.io.Serializable {


     private TaskDocId id;
     private Document document;
     private Task task;
     private Long publish;

    public TaskDoc() {
    }

	
    public TaskDoc(TaskDocId id, Document document, Task task) {
        this.id = id;
        this.document = document;
        this.task = task;
    }
    public TaskDoc(TaskDocId id, Document document, Task task, Long publish) {
       this.id = id;
       this.document = document;
       this.task = task;
       this.publish = publish;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idTask", column=@Column(name="ID_TASK", nullable=false) ), 
        @AttributeOverride(name="idDocument", column=@Column(name="ID_DOCUMENT", nullable=false) ) } )
    public TaskDocId getId() {
        return this.id;
    }
    
    public void setId(TaskDocId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOCUMENT", nullable=false, insertable=false, updatable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TASK", nullable=false, insertable=false, updatable=false)
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }
    
    @Column(name="PUBLISH")
    public Long getPublish() {
        return this.publish;
    }
    
    public void setPublish(Long publish) {
        this.publish = publish;
    }




}


